### ISSUE TITLE
updating all replicas

### ISSUE THREAD

**Issue by pigay** [irods/python-irodsclient#100]
Hi,

I want to use DataObjectManager.put() method in order to overwrite all replicas of a file (same as `iput -af`).

I tried the following:
```python
do_mgr.put(local_filename, irods_path, options={kw.FORCE_FLAG_KW: '', kw.ALL_KW: ''})
```
The first replica is overwritten, but not the others.

Did I miss something?

Thanks in advance,

Pierre

**Comment by adetorcy** [comment]
I will double check. FYI, please note that as of commit 7853df4 put and other IO options are now passed as keyword arguments, e.g:
```python
options={kw.FORCE_FLAG_KW: '', kw.ALL_KW: ''}
do_mgr.put(local_filename, irods_path, **options)
```
This will be part of the release notes for 0.7.0

**Comment by pigay** [comment]
I didn't mention that my server is iRODS v3.
Looking through wireshark and comparing iput and python-irodsclient suggests that options are not passed the same way to the server. Did the protocol change on this matter?

**Comment by adetorcy** [comment]
I am observing this behaviour with iRODS 4. It is likely caused by PRC doing an open-write-close rather than calling the put API, in which case `ALL_KW` has no effect. For the same reason you will overwrite an existing object even without `FORCE_FLAG_KW`. I will need to address this after the 0.7.0 release. In the meantime a potential workaround to update all replicas might be:
```python
options={kw.ALL_KW: ''}
do_mgr.put(local_filename, irods_path)
do_mgr.replicate(irods_path, **options)
```

**Comment by trel** [comment]
I think this is the same behavior as https://github.com/irods/irods_client_fuse/issues/12

**Comment by adetorcy** [comment]
It is not an `oprType` issue. It is likely because `rsDataObjClose` doesn't do something like this:
https://github.com/irods/irods/blob/master/server/api/src/rsDataObjPut.cpp#L160-L161
and
https://github.com/irods/irods/blob/master/server/api/src/rsDataObjPut.cpp#L170-L177

**Comment by pigay** [comment]
I encounter another problem when trying to implement the workaround: `do_mgr.put()` doesn't update the first replica checksum. Then, `do_mgr.replicate()` raises  `USER_CHKSUM_MISMATCH`

I tried to add `REG_CHKSUM_KW` to the put operation in hope it could help, but without effect.

**Comment by adetorcy** [comment]
I would not recommend using `data_object_manager.put()` with older servers. It calls `rsDataObjOpen()` with the `O_CREAT` flag which IIRC doesn't work before 4.1.5.

In your case to be on the safe side you might want to write your own put function that does an object create/open/write/close, and possibly check for the object's presence beforehand.

**Comment by pigay** [comment]
Strangely, the 3.3.1 server doesn't complain about that `O_CREAT` flag and the file creation occurs smoothly.

I gave a try to you 3e4a5533448fa3623063a36e855fb745676cef4e commit and it does something I didn't expect: it creates a replica of the file on each resources of the resource group I'm using for default resource.

I may have misunderstood the meaning of the `ALL_KW`. I thought it would act as a `iput -a` (at least in 3.3.1, it updates existing replicas of a already present file but doesn't create new replicas).

More explicitly, I'm looking to have the same behavior of a `iput -aKf` on existing data object. I tried several combination of keywords but failed to reproduce it.

Do you know how I could make it work?

**Comment by adetorcy** [comment]
That seems consistent with the [documentation](https://github.com/irods/irods-legacy/blob/master/iRODS/clients/icommands/src/irepl.c#L145-L146)  of `irepl -a` in iRODS 3.

What happens if you repave one replica with `iput -Kf` and then update the others with `irepl -U`?

**Comment by pigay** [comment]
1. `iput -Kf` updates first replica along with its checksum. Other replicas are marked "stale".
2. `irepl -U` updates stale replicas and their checksum. They are no longer marked stale.

This seems to be the same as `-aKf`.

What combination of keywords should I use to get the same behavior? I tried with 39ff60b9b749320293b28c6529e06d203976f310 but still get `USER_CHKSUM_MISMATCH`.

**Comment by adetorcy** [comment]
I would try to do an equivalent of those two steps with PRC.

If `data_object_manager.put()` works with iRODS 3.3.1 you can try something like:
```python
options={kw.VERIFY_CHKSUM_KW: ''}
objects.put(local_path, irods_path, **options)
options={kw.ALL_KW: '', kw.UPDATE_REPL_KW: ''}
objects.replicate(irods_path, **options)
```
Otherwise step 1 can be done as open/write/close with the options on open.

Another approach could be to repave and replicate first and then have the checksums computed by `msiSysChksumDataObj` post replication.

**Comment by pigay** [comment]
I finally managed to get what I want.

I was completely missing that the option  `kw.VERIFY_CHKSUM_KW` has an argument which is the md5 of the file to be put into iRODS. Computing local file md5sum and providing it as the option value does the trick :)
 
Your `data_object_manager.put()` works perfectly.

Many thanks for your help!

Pierre

**Comment by pigay** [comment]
But...

Strangely, it works if the new file is larger than the data_object in iRODS and fails with CHKSUM_MISMATCH when it is shorter.

`iput -aKf` is ok with shortening the files.

**Comment by pigay** [comment]
e77b529 solves the last problem!
Now, `data_object_manager.put()` works well with `VERIFY_CHKSUM_KW`, `ALL_KW` and `UPDATE_REPL_KW` together.

Thank you for your help.

Pierre
