### ISSUE TITLE
iRODS v3 exception logging in iRODSDataObject.__init__

### ISSUE THREAD

**Issue by pigay** [irods/python-irodsclient#101]
Hi,

I'm trying to use ptyhon-irodsclient with a iRODS v3 catalog. Every time I create a DataObject form a collection (by using `collectin.data_object`), i get the following logging message:
```
2017-11-29 12:34:34,273 irods.data_object-ERROR [/home/pigay/local/lib/python2.7/site-packages/python_irodsclient-0.7.0a0-py2.7.egg/irods/data_object.py 53] Unable to set data object attribute
Traceback (most recent call last):
  File "/home/pigay/local/lib/python2.7/site-packages/python_irodsclient-0.7.0a0-py2.7.egg/irods/data_object.py", line 49, in __init__
    setattr(self, attr, results[0][value])
```

It appears to be a call to `logging.exception()` from the `iRODSDataObject` constructor. I managed to get rid of the message by raising the loglevel to CRITICAL, but it's only a ugly workaround.

Do you think this message could be lowered to DEBUG level? Maybe it would be worth to check against this particular error and lower the loglevel only in that case?

Regards,

Pierre

**Comment by adetorcy** [comment]
The line in question: https://github.com/irods/python-irodsclient/blob/master/irods/data_object.py#L52

How about making that a `logger.warning()` call?

**Comment by adetorcy** [comment]
Upon further thought we should have access to the server version at this point so we can check if it's less than 4.0.0 and do nothing in that case, otherwise re-raise.

**Comment by pigay** [comment]
Checking the server version before re-raise seems ok.

I can make a PR for that if you want.

**Comment by adetorcy** [comment]
Thanks. I looked into it out of curiosity and I think I should have a small fix shortly.

**Comment by pigay** [comment]
Thanks for the fix.

Cheers,
Pierre
