### ISSUE TITLE
MSG_WAITALL problem on Windows 7

### ISSUE THREAD

**Issue by pigay** [irods/python-irodsclient#103]
Hi,

I'm trying to use irodsclient on Windows 7. The Python I installed is 3.6.3.

Instead of ValueError like in #53, I get OSError in [sock.recv()](https://github.com/irods/python-irodsclient/blob/b99f4c721de461c0e1161a545e2b26cfdb074eb0/irods/message/__init__.py#L27)

Adding `OSError` in the list of caught exceptions is sufficient to have it work, but is it the good think to do?

Cheers,

Pierre

**Comment by adetorcy** [comment]
Can you print the full traceback?

**Comment by pigay** [comment]
Here it is. sorry for the screenshot, I failed to use my VM copy/paste...

![msg_waitall_tb](https://user-images.githubusercontent.com/754327/33824717-99aedf6a-de5f-11e7-9510-53cd5eb9c577.png)

**Comment by adetorcy** [comment]
That seems reasonable. I will look into this and #104 once version 0.7.0 is out. There may be other parts of the code that expect a *nix environment.
Windows support is not a priority at this point but I will try to make the code portable as much as possible.

**Comment by pigay** [comment]
I understand that Windows is not in your top priorities. Your help is much appreciated.

If you agree, I would like to propose PRs to fix the issues I encounter. You could accept/reject/discuss them at your convenience, after 0.7.0 is released for example.

**Comment by adetorcy** [comment]
Yes, absolutely. Thank you.
