### ISSUE TITLE
Add recursive collection creation

### ISSUE THREAD

**Issue by froggleston** [irods/python-irodsclient#109]
Unless I'm mistaken (and I often am!) the CollectionManager.create() function doesn't take any user supplied **options (e.g. RECURSIVE_OPR__KW), so an action like creating collections including any requisite parent directories is not possible. Can this be added?

Cheers!

Rob

**Comment by trel** [comment]
Other methods of the collection manager support options so it should be similarly possible.

Antoine has taken another job, so our ability to respond/iterate will be reduced for a bit.  Pull requests are always helpful if you're feeling capable/generous :)

**Comment by froggleston** [comment]
Thanks for the info! I've created a pull request with an initial go at the changes. I haven't tested these yet, so I apologise if things break!

**Comment by trel** [comment]
fixed by #110
