### ISSUE TITLE
 Children are not returned when retrieving a resource.

### ISSUE THREAD

**Issue by lwesterhof** [irods/python-irodsclient#111]
iRODS 4.2.1 / python-irodsclient 0.7.0

The children are not returned when retrieving a resource.

The following resource tree is present:
![ilsresc](https://user-images.githubusercontent.com/29246264/35973967-a39e8e52-0cd7-11e8-9b67-c2667475058e.png)

While retrieving the resource, for example:
` resource = session.resources.get(dev001_p2)`

resource.children is None, but should be dev001_2.

**Comment by trel** [comment]
`resource.children` should now return a list of children resources.
