### ISSUE TITLE
Triggering event hooks in iRODS

### ISSUE THREAD

**Issue by chStaiger** [irods/python-irodsclient#117]
Hello, 

I working with iRODS 4.1.11 and 4.2.1. I configured some eventhooks and peps in my core.re. However, these seem not be triggered when placing data with the python-irodsclient into iRODS.

This is my setup for post processing of a put:

```c
acPostProcForPut {
  ON($objPath like "/$rodsZoneClient/home/$userNameClient/event/*"){
    msiAddKeyVal(*Keyval, "TRIGGER", "acPostProcForPut");
    msiGetObjType($objPath, *objType);
    msiSetKeyValuePairsToObj(*Keyval, $objPath, *objType);
  }
}

acPostProcForPut { }
pep_api_data_obj_put_post(*COMM, *DATAOBJINP, *BUFFER, *PORTAL_OPR_OUT) { acPostProcForPut; }
```

The setup works for the icommands and the C API.
Any help how to trigger event hooks with the python API is very welcome.

Many thanks.

**Comment by trel** [comment]
I think this should now be working with v0.7.0 (fixed via https://github.com/irods/python-irodsclient/issues/86).

Are you using the latest release?

**Comment by chStaiger** [comment]
I am using the latest release:

```
pip freeze | grep irods
python-irodsclient==0.7.0
```

**Comment by chStaiger** [comment]
To create new data objects I followed the readme of this git. Maybe I am doing something strange here:

```py
iPath = '/saladZone/home/christine/event/apiDump.txt'
obj = sess.data_objects.create(iPath)
content = 'My contents!'
with obj.open('w') as obj_desc:
    obj_desc.write(content)
```

**Comment by chStaiger** [comment]
Ah, I see, I need to use a different function.
I will try.

Thanks.

**Comment by trel** [comment]
Yes, I believe the `create()` method is using the open/write/close streaming approach to getting data into iRODS - and this doesn't trigger the same PEPs.

**Comment by chStaiger** [comment]
I tried right now the `put()` method:

```py
import irods.keywords as kw
options = {kw.OPR_TYPE_KW: 1}
sess.data_objects.put('test.txt', '/saladZone/home/christine/event/test_event.txt', options)
```

```sh
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-d1e4348ad995> in <module>()
----> 1 sess.data_objects.put('test.txt', '/saladZone/home/christine/event/test_event.txt', options)

TypeError: put() takes exactly 3 arguments (4 given)
```

Without the `options` the eventhook does not get triggered.

**Comment by chStaiger** [comment]
Ahhh, found it. That works:

```py
sess.data_objects.put('test.txt', '/saladZone/home/christine/event/test_event.txt', **options)
```

Many thanks.

**Comment by trel** [comment]
Oh good, you had me worried.

**Comment by chStaiger** [comment]
Sorry.

**Comment by trel** [comment]
I just tested it as well, and you can also just use:
```
sess.data_objects.put('test.txt', '/saladZone/home/christine/event/test_event.txt')
```
I will update the README.md with the put() method and an explanation.   Thanks.
