### ISSUE TITLE
Sample code for removing replicas aka `itrim`

### ISSUE THREAD

**Issue by kript** [irods/python-irodsclient#121]
Apologies if you can already do this, but reading through the code, I can only see options to unlink  a file, rather than a replica. 

Is it possible to unlink a specific replica of a file with the irodsclient?
If so, would you be so kind as to provide some illustrated examples for listing, and then removing, a specific replica number?

If not, could I add it as a feature request please?

Thanks,

John

**Comment by pigay** [comment]
Hi,
You may use unlink with option like shown in the test directory:
https://github.com/irods/python-irodsclient/blob/902000a5ebecea0ea753ce86a08111ff666b620d/irods/test/data_obj_test.py#L520

Cheers

**Comment by trel** [comment]
This works as shown in the test.

Closing.
