### ISSUE TITLE
replica object does not contain size

### ISSUE THREAD

**Issue by kript** [irods/python-irodsclient#126]
https://github.com/irods/python-irodsclient/blob/1cc23fc06ed213acb2d1dcc0d6156f9968e8f989/irods/data_object.py#L59

One can get every other replica information you can retrieve with `ils` apart from that (unless I've missed something);

```
import os
from irods.session import iRODSSession
try:
    env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
    env_file = os.path.expanduser('~/.irods/irods_environment.json')

session = iRODSSession(irods_env_file=env_file)

obj = session.data_objects.get("/seq/home/jc18#Sanger1/irods-resource-4.0.0-64bit.deb")

for replica in obj.replicas:
    print(replica.resource_name)
    print(replica.number)
    print(replica.path)
    print(replica.status)
    print(replica.checksum)
```
```
./test_python.py 
root
0
/irods-seq-i23-de/home/jc18#Sanger1/irods-resource-4.0.0-64bit.deb
1
02b7dd912af6e615f4680594fe3e2dc8
Traceback (most recent call last):
  File "./test_python.py", line 19, in <module>
    print(replica.size)
AttributeError: 'iRODSReplica' object has no attribute 'size'
```
This would help with [Issue 3930](https://github.com/irods/irods/issues/3930)

**Comment by d-w-moore** [comment]
Unsatisfactory for general purposes maybe - and only a valid approach if the bad replicas were accessible via OS calls from the local filesystem -  but if the goal is to  cull the undesired replicas mentioned in [3090](https://github.com/irods/irods/issues/3930) one possibility would be to stat the physical paths of all "good" (repl.status == '1')  replicas of all DataObjects on the affected resource(s). For those returning zero size( ie., os.stat(repl.path).st_size==0) , you could make a PRC call to remove them. It would require running as the service account user, however, as only that user would has general access to all the local physical paths.

**Comment by d-w-moore** [comment]
Extra note to the above :  I'm  fairly new in python  iRODS client programming myself,  but it happens that I've done the above mentioned replica deletion elsewhere with e.g. : "dataObj.unlink(replNum=N)"
