### ISSUE TITLE
Support for OpenID authentication scheme

### ISSUE THREAD

**Issue by theferrit32** [irods/python-irodsclient#130]
- [x] allow user to log in with an existing session token they received from iinit

- [ ] enable client application code to perform interactive logins, using authorization urls generated by iRODS (and using the iRODS system as the 3rd leg in the oauth2 flow). 

- [ ] enable use of 'externally generated' tokens for various providers.  This use case is for when iRODS/token service was not used as the 3rd leg in an oauth2 flow (ie: not using iinit), however the user has come into possession of a valid `openid` access token and wants to login into their iRODS account with it.  The oidc token service used by iRODS has an endpoint which can already perform this operation against an identity provider's api, but the plugin does not yet have the ability to accept and handle those tokens.

**Comment by RubenGarcia** [comment]
Hello. Can you give us an update on the status of checkboxes 2 and 3? Thank you.

**Comment by theferrit32** [comment]
@RubenGarcia all three items are completed and in a branch here:
https://github.com/theferrit32/python-irodsclient

There are some examples seeking to replicate common icommands here:
https://github.com/theferrit32/python-irodsclient/tree/openid/examples

The 3rd item is completed in the openid plugin for iRODS but is not not shown in these examples, but you can sort of see the method to invoke it in the link below.  These attributes are set by adding them as kwargs to the `IRODSSession` [constructor](https://github.com/theferrit32/python-irodsclient/blob/openid/examples/pyiget.py#L44).  So an `access_token` kwarg can be passed there, and read in from a file, or from stdin.
https://github.com/theferrit32/python-irodsclient/blob/openid/irods/connection.py#L393

**Comment by RubenGarcia** [comment]
Excellent news! Thank you.

**Comment by RubenGarcia** [comment]
The token is too long to traverse the irods-server <-> irods_client interface.

**Comment by RubenGarcia** [comment]
I recreated the container. I am no longer getting the USER_PACKSTRUCT_INPUT_ERR, strangely.
However, my keycloak token is not being accepted, and I'm still getting a OpenID Authorization URL:
https://keycloak... line.

**Comment by RubenGarcia** [comment]
I created an issue https://github.com/irods/python-irodsclient/issues/177 to document what happens, since I'm getting different results from different tokens.

**Comment by trel** [comment]
Closing.   This will not be handled in this library directly.

The iRODS HTTP API is adding OIDC support - https://github.com/irods/irods_client_http_api
