### ISSUE TITLE
ssl_certificate_chain_file

### ISSUE THREAD

**Issue by mheijink** [irods/python-irodsclient#134]
How do you pass "irods_ssl_certificate_chain_file" to the python-irodsclient

**Comment by mheijink** [comment]
I got it working by creating a ssl context and used the chain certificate file instead of th ca file

        context = ssl.create_default_context(
            purpose=ssl.Purpose.SERVER_AUTH, 
            cafile=....., 
            capath=None, 
            cadata=None)

        ssl_settings = {'client_server_negotiation': 'request_server_negotiation',
                        'client_server_policy': 'CS_NEG_REQUIRE',
                        'encryption_algorithm': 'AES-256-CBC',
                        'encryption_key_size': 32,
                        'encryption_num_hash_rounds': 16,
                        'encryption_salt_size': 8,                        
                        'ssl_context': context}
    
        super(tuRODSSession, self).__init__(
            host=host, 
            port=port, 
            user=user, 
            password=password, 
            zone=zone, 
            client_user=client_user,
            **ssl_settings
            )

**Comment by trel** [comment]
Glad you got it working.

Could you contextualize a bit more and add this to the README.md?
