### ISSUE TITLE
Filter chaining in queries not working as expected for multiple criteria on the same column

### ISSUE THREAD

**Issue by mikkonie** [irods/python-irodsclient#135]
I was in need to do a query on the ICAT database for data objects within a certain collection, where the name of the data object would contain "XXX" and would NOT contain "YYY". I tried to achieve this with the following query:

```
session.query(DataObject).filter(
    Criterion('like', DataObject.path, '%/some/path')).filter(
        Criterion('like', DataObject.name, '%XXX%')).filter(
            Criterion('not like', DataObject.name, '%YYY%'))
```

Expected outcome: Returning DataObjects under the path with name containing "XXX" but not containing "YYY"

Actual outcome: Returns all DataObjects under the path which don't contain "YYY". The filter for "like %XXX%" is not applied.

In this case, only the first and last filters get applied to the query. If I reverse the order of the last two filters, again the middle one gets omitted. It seems that if there are multiple filters on the same column, only the last one of them affects the query.

Now, this might not be the most optimal way to do this query. I in fact solved the issue on my end by instead doing a raw SQL query using SpecificQuery. But I thought this was still worth reporting.

**Comment by trel** [comment]
Confirmed this behavior - only the last use of a particular column is honored.

Even splitting the filtering across the saving of results stomps the earlier filtering.

135.py:
```python
from irods.column import Criterion
from irods.models import DataObject
from irods.session import iRODSSession
import os
env_file = os.path.expanduser('~/.irods/irods_environment.json')
with iRODSSession(irods_env_file=env_file) as session:
    # with chaining
    print('----')
    results = session.query(DataObject).filter( \
        Criterion('like', DataObject.name, '%b%')).filter( \
        Criterion('not like', DataObject.name, '%a%'))
    for r in results:
        print(r[DataObject.name])

    # without direct chaining
    print('----')
    results = session.query(DataObject).filter( \
        Criterion('like', DataObject.name, '%b%'))
    for r in results:
        print(r[DataObject.name])
    print('-')
    fewer = results.filter(Criterion('not like', DataObject.name, '%a%'))
    for r in fewer:
        print(r[DataObject.name])
```

```bash
$ ils
/tempZone/home/rods:
  aaa
  aaaaa
  bbb
  bbbbb
  ccc
  ccccc

$ python 135.py 
----
bbb
bbbbb
ccc
ccccc
----
bbb
bbbbb
-
bbb
bbbbb
ccc
ccccc
```

**Comment by RubenGarcia** [comment]
I am also affected by this.

**Comment by d-w-moore** [comment]
For now, until this is fixed, I'd recommend using Python's set comprehensions in the case of "like X but not like Y"  (untested):

  q = session.query(DataObject,Collection).filter (*list_of_other_conditions_not_involving_LIKE)
  q1 = list(q.filter(Like(DataObject.name,"{}".format(X)))
  q2 = list(q.filter(Like(DataObject.name, "{}".format(Y))))
  matching_objects = { res[Collection.name] + "/" + res[DataObject.name] for res in q if res in q1 and res not in q2}
