### ISSUE TITLE
Integers to metadata

### ISSUE THREAD

**Issue by jjkoehorst** [irods/python-irodsclient#144]
When adding metadata to an object I noticed it is only possible to store strings or is there another way to store floats, integers, etc?

**Comment by trel** [comment]
The database schema for iRODS stores only strings for AVUs at this time.

You would need to do any conversion / analysis on the client side to give those strings meaning for your use case(s).

That said, there are some basic manipulations / comparisons that can be done via `imeta qu`:
  https://docs.irods.org/4.2.4/icommands/metadata/#qu
