### ISSUE TITLE
PAM authentication and irods_environment.json

### ISSUE THREAD

**Issue by pigay** [irods/python-irodsclient#156]
Hi,

I tried to make a session using an `irods_env_file` that uses PAM authentication.

It fails with the `PAM_AUTH_PASSWORD_FAILED` error code because the password is not extracted from `irods_authentication_file` as with native auth.

It would be interesting if the `irods_env_file` could work with PAM auth.

**Comment by trel** [comment]
pinging @mdantonio

**Comment by mdantonio** [comment]
Hello,
I successfully connected by using irods_env_file as described in the [Establishing a connection](https://github.com/irods/python-irodsclient#establishing-a-connection) section of the guide, i.e.:

```
from irods.session import iRODSSession
import os
env_file = os.path.expanduser('~/.irods/irods_environment.json')
with iRODSSession(irods_env_file=env_file) as session:
    session.collections.get(mypath).path
```

with env_file = 

```
{
    "irods_host": "myhost",
    "irods_port": myport,
    "irods_user_name": "myusername",
    "irods_password": "mypassword",
    "irods_zone_name": "myzone",
    "irods_home": "myhome",
    "irods_authentication_scheme": "PAM"
}
```

Of course if I remove irods_password from irods_environment.json I obtain `irods.exception.PAM_AUTH_PASSWORD_FAILED`

I'm also able to connect by mixing irods_environment.json with other options, i.e.:

```
from irods.session import iRODSSession
import os
env_file = os.path.expanduser('~/.irods/irods_environment.json')
with iRODSSession(irods_env_file=env_file, password='mypassword') as session:
    session.collections.get(mypath).path
```

Could you provide me with more information about your use case? Maybe are you trying to connect by using the scrambled password saved into the ~/.irods/.irodsA file?

**Comment by pigay** [comment]
Hello Mattia,

> Could you provide me with more information about your use case? Maybe are you trying to connect by using the scrambled password saved into the ~/.irods/.irodsA file?

I tried to used a scrambled password indeed. It seems that `iRODSSession._configure_account` handles this only with native authentication.

It would be nice if it could work with PAM auth too.

Regards,
Pierre

**Comment by pigay** [comment]
I tried with your commit and it still fails with the test code.

I think this is because `session.pool.account.password` is still scrambled after `iRODSSession._configure_account()` (I suppose `Connection._login_pam()` needs an unscrambled password).

**Comment by mdantonio** [comment]
Hello and sorry for the late response.

You suppose right, login_pam needs an unscrambled password and by default _configure_account() does not care about this.

What I introduced with my commit is that:

https://github.com/mdantonio/python-irodsclient/blob/master/irods/session.py#L78

Now PAM authscheme will follow the native authscheme and no longer return unscrambled password but should continue and execute this:

`creds['password'] = self.get_irods_password(**creds)`

So that after the execution of _configure_account()  creds['password'] should contains a unscrambled password

Could you put some prints somewhere to verify this?

**Comment by pigay** [comment]
Hello Mattia,

I printed the contents of `creds['password']` after the call to `self.get_irods_password(**creds)` (line https://github.com/mdantonio/python-irodsclient/blob/master/irods/session.py#L87 ).

The value stored is still scrambled, this is why `Connection._login_pam()` will fail.

**Comment by mdantonio** [comment]
It is still scrambled and identical to the content of .irodsA file?
Or the content changed? In this case the decode function seems to fail, maybe the user_id used to decode differs from the one used to encode?

Could you provide instructions on how to reproduce your case?

**Comment by dupuisIRT** [comment]
Hi @pigay, I am facing the same problem, did you manage to uses PAM authentication with scrambled password ?

**Comment by pigay** [comment]
Hi @dupuisIRT,

I didn't look further. I don't actually understand why the value returned by `get_irods_password()` is not the one stored in the file (or isn't correctly unscrambled).

I hope @mdantonio could help.

**Comment by trel** [comment]
PR #191 appears to close this.

@pigay @dupuisIRT @mdantonio can anyone confirm the fix and/or provide a test?

**Comment by trel** [comment]
This is now working and tested at the bench - test harness coming soon for #209 and #151.
