### ISSUE TITLE
session.data_objects.get cannot find data objects in remote zone

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#163]
This issue was originally reported [here](https://groups.google.com/d/msg/irod-chat/oYTYBvpGt54/cDzDATSKBgAJ).

For two federated zones, if a user `alice#localZone` owns a remote object with a logical path of:
```
/remoteZone/home/alice#localZone/a
```
and attempts to access it in the manner of:
```
iRODSSession(...).data_objects.get("/remoteZone/home/alice#localZone/a")
```
 a python error of type  `irods.exception.DataObjectDoesNotExist` is generated.

Within the demonstration to follow, this python script (as `dataobj_cross_fedn.py`) can be used to reproduce the error:

```
#!/usr/bin/env python
from __future__ import print_function
from sys import argv
import os
from irods.session import iRODSSession
try:
    env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
    env_file = os.path.expanduser('~/.irods/irods_environment.json')
with iRODSSession(irods_env_file=env_file) as session:
    if len(argv ) >= 3:
        if argv[1] == 'c':     # access collection
            coln = session.collections.get(argv[2])
            print ('sub objects = ' )
            for dataObject in coln.data_objects: print ('\t' + dataObject.path) 
        elif argv[1] == 'd':  # access data object
            dobj = session.data_objects.get(argv[2])
            print (dobj.path + ' found, has size = ' + str(dobj.size))
```

------
## Demonstration of the issue

This session shows that although a remote data object's existence can be verified via its parent collection's index of child objects, it cannot then be accessed (as we'd expect to) by means of specifying its path to the get method of the session's data_objects accessor. With the `ubuntu` user logged in as alice in  `localZone` (federated to `remoteZone`) we see it if we do the following:

```
ubuntu@u16host:~$ ils /remoteZone/home/alice#localZone
/remoteZone/home/alice#localZone:
  a
ubuntu@u16host:~$ chmod +x dataobj_cross_fedn.py 
ubuntu@u16host:~$ ./dataobj_cross_fedn.py  c "/remoteZone/home/alice#localZone"
sub objects = 
	/remoteZone/home/alice#localZone/a
ubuntu@u16host:~$ ./dataobj_cross_fedn.py  d "/remoteZone/home/alice#localZone/a"
Traceback (most recent call last):
  File "./dataobj_cross_fedn.py", line 18, in <module>
    dobj = session.data_objects.get(argv[2])
  File "/usr/local/lib/python2.7/dist-packages/irods/manager/data_object_manager.py", line 56, in get
    raise ex.DataObjectDoesNotExist()
irods.exception.DataObjectDoesNotExist
```

Whereas the same script can be verified to work for objects within the `localZone`; i.e., if we have an object `/localZone/home/alice/b` the script has no problems accessing the object in question:

```
ubuntu@u16host:~$ ./dataobj_cross_fedn.py  c "/localZone/home/alice"
sub objects = 
	/localZone/home/alice/b
ubuntu@u16host:~$ ./dataobj_cross_fedn.py  d "/localZone/home/alice/b"
/localZone/home/alice/b found, has size = 12
```

**Comment by kript** [comment]
One of our users is hitting this as we use Federation and they only have access to the top level Zone. 
Do you have a workaround, or expected release for a fix?

cheers!

**Comment by d-w-moore** [comment]
I think there is a workaround currently that involves doing a get on the Collection object (the one containing the data object) and enumerating the data objects that are its children.  Can you be more specific about your users are encountering, does it involve both querying and accessing the data objects?

**Comment by prete** [comment]
My irods_enviroment.json 
```json
{
    "irods_authentication_scheme": "native",
    "irods_host": "irods.host.at.some.place",
    "irods_port": 1247,
    "irods_user_name": "superCoolUsername",
    "irods_zone_name": "zone2"
}
```

If I run

```bash
imeta qu -z zone1 -d foo = bar
```

I get
```
----
collection: /zone1/foobar
dataObj: foo_file.bam
```

However, if I create a session with the same credentials and run this
```python
with iRODSSession(host=irods_host, port=irods_port, user=irods_user_name, password=irods_password, zone=irods_zone_name) as session:
    query = session.query(DataObject, DataObjectMeta).filter(Criterion('=', DataObjectMeta.name, "foo")).filter(Criterion('=', DataObjectMeta.value, "bar"))
    for result in query:
        print(result)
```
I don't get any results. There is no parameter or argument to query between zones.

---

A similar thing happens when trying to get a data object from another zone.
The following code gets me nothing
```python
path = "/zone1/foo/bar"
with iRODSSession(host=irods_host, port=irods_port, user=irods_user_name, password=irods_password, zone=irods_zone_name) as session:
    data_object = session.data_objects.get(path)
```

My workaround for this one was to walk the collection *(which I can get from another zone)* and get the file:
```python
collection_path = "/".join(path.split("/")[:-1])
file_name = path.split("/")[-1]
with iRODSSession(host=irods_host, port=irods_port, user=irods_user_name, password=irods_password, zone=irods_zone_name) as session:
    data_object = [d for d in session.collections.get(collection_path).data_objects if d.name == file_name][0]
```

But I don't really have a workaround for `imeta` without waking EVERY collection and checking EVERY file myself.

**Comment by d-w-moore** [comment]
A candidate pull request https://github.com/irods/python-irodsclient/pull/174 for addressing this issue. Any query object can now be augmented with a keyword option,  such as (in this case) `irods.keywords.ZONE_KW` .
