### ISSUE TITLE
Backtick (`) encoding issue in iRODS XML protocol handling

### ISSUE THREAD

**Issue by cjsmeele** [irods/python-irodsclient#170]
When using the XML-based protocol, iRODS encodes backticks as `&apos;`, deviating from the XML standard. Clients such as PRC and irods-php that use an XML library for decoding iRODS messages incorrectly produce apostrophe (`'`) characters wherever backticks are encountered (e.g. file names).

See the original iRODS issue: irods/irods#4132

We are running into this problem because we encounter file names with backticks in them, and are getting the exact result demonstrated by @alanking in the linked iRODS issue.

How should this incompatibility best be handled?
I made a (experimental / fragile) work-around by using a simple string replace on received messages here: https://github.com/cjsmeele/python-irodsclient/commit/80d4cdec269ecccf331b8e3eff9ae52d8c2bfcce ... however I'm really not sure whether this is the appropriate place to do this or whether this even works reliably.

An additional note: I noticed no problems with *outgoing* backticks and apostrophes, as can be produced with query parameters. I could only find an issue with received messages.

**Comment by trel** [comment]
Yes, the biggest problem is that we cannot change packStruct and remain compatible back to iRODS 3.x.  We're not sure how to handle this correctly at this time - and are open to suggestions.

**Comment by trel** [comment]
@d-w-moore how does this conversation look now?   can we update/close this?  if so, let's point to the relevant commits/discussions.

**Comment by d-w-moore** [comment]
So , let's see.  We now have  iRODS  speaking backtick now thanks to @korydraughn , yes?

We also can't forget that  in the linked issue  #4132 we have this [comment](https://github.com/irods/irods/issues/4132#issuecomment-528786460) regarding problems when embedding nonprintable / control codes in object names.  (On this slight aside, @SwooshyCueb is it possible to communicate these non-printable characters through standard XML ? I don't think even CDATA sections let you do this. Just a guess, but maybe Unicode is the recommended way?)  iCommands accomplish these weird embeddings without benefit of the native binary protocol (Environment: irodsProt=0) so I without going out on a limb I can't guarantee  iRODS even speaks a standard dialect of XML.  If we made it conform to the Standard, would the ability to have weird characters in file names suddenly break ? 

As you pointed out @trel can' really change packStruct anyway without some iRODS 3.x headaches.

Finally I think there's always the possibility of getting PRC to speak the binary protocol, at least for just covering the corner cases like these. I think `struct.pack` and `struct.unpack` would help there.

**Comment by trel** [comment]
Seems fair.  So, we can probably close this particular backtick issue as 'solved'.    And we should open a new enhancement issue for PRC to learn to speak the binary protocol upon request (or as a fallback/retry... or perhaps... always?).

**Comment by trel** [comment]
Reopening for one more tweak.

@d-w-moore please add a note in the README on how to hold this new switchable solution (and why).

**Comment by d-w-moore** [comment]
ok , will do.
