### ISSUE TITLE
create and modify times do not exist in Metadata models

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#187]
In the Python iRods Client currently, iRODS objects with a type in *(User, Resource, DataObject, Collection)* have create_time and modify_time fields that can be queried as columns (compared against datetime module's UTC time-tuples, for example, to determine age) , but the same is not true of their *(UserMeta, ResourceMeta, DataObjectMeta, CollectionMeta)* counterparts.   

So in iquest / LIGQ genquery syntax we can use either of:
```
select COLL_NAME where   COLL_CREATE_TIME > '01234567890'
```
or
```
select COLL_NAME where   META_COLL_CREATE_TIME > '01234567890'
```
but we cannot do this in PRC:
```
from datetime import datetime, timedelta
q = session.query( Collection , CollectionMeta ) .filter(  
   CollectionMeta.modify_time >= datetime.utcnow( ) - timedelta ( seconds=60 ))
```

**Comment by trel** [comment]
please close if complete
