### ISSUE TITLE
Executing a rule requires reconnection / reauthentication to iRODS

### ISSUE THREAD

**Issue by cjsmeele** [irods/python-irodsclient#190]
Currently, after executing a rule, the PRC automatically closes its
iRODS connection: https://github.com/irods/python-irodsclient/blob/d1a46ace868deeabff3895de77a0d8b7528e2972/irods/rule.py#L78

We've found that when executing multiple relatively fast (~10ms) rules
in succession, or when performing any other PRC action after a PRC rule
call, that the steps needed to re-open a connection to iRODS, negotiate
and (PAM) authenticate, add significant performance overhead. In this
case, a multiple of the duration of the rule execution itself.

Removing the line mentioned above appears to allow continued use of the
iRODS session, which makes me wonder why it is there. Other API calls
via PRC (e.g. genquery) leave the connection open for reuse.

I do see the irodsServer (4.2.6) process increase memory consumption
after each (python) rule call -- scaling with the amount of queries
performed by the rule -- until the connection is closed, so there does
appear to be a memory leak on the server side for longer-lived
connections with rule calls.

Could the need for reconnection be eliminated?

**Comment by d-w-moore** [comment]
You may be right about the possibility of streamlining this.  We would have to be cautious before retiring the cleanup( ) and write some tests around possible edge cases; of course, I'm not sure what those would be  at the moment, not having  studied the PRC's connection pool .

**Comment by gscteam** [comment]
It seems that there is some caching made per connection, the cleanup is the only way (apparently) to get updated information. I am running into this right now, and having to cleanup at every interaction is less than ideal.

**Comment by PaulVanSchayck** [comment]
We're also facing this issue, and experience a slow user experience when executing several rules for displaying a web page.

How about we add a `session_cleanup=True` parameter to `execute()`? Or to the `Rule` class as parameter? So, that when you know that your rule does not require an update of information to the client, you can choose to keep the connection alive. By setting the default to true, the old behavior remains intact.

**Comment by d-w-moore** [comment]
I don't see a reason the session would need `cleanup` to be called in that particular place unless someone was just being conservative.  As for automatic session cleanup at program exit, I've had that in the wings for a while on [this dev branch](https://github.com/d-w-moore/python-irodsclient/commit/6ca64df7d69d9d8acc3b0038f086aa51a5f47684).  Perhaps by early next week I could get all of this all merged together into the main namespace....

**Comment by PaulVanSchayck** [comment]
So, you're proposing to simply remove that `self.session.cleanup() ` from the Rule `execute()`? We're also fine with that.

Yes, an automatic session cleanup on program exit is a nice addition. Would make a lot of sense. We were actually surprised to find that this wasn't already implemented.

**Comment by d-w-moore** [comment]
> It seems that there is some caching made per connection, the cleanup is the only way (apparently) to get updated information. I am running into this right now, and having to cleanup at every interaction is less than ideal.
@gscteam

**Comment by d-w-moore** [comment]
I'm still adapting other fixes-and-features-to-come into the PRC for the journey to 4.2.9, so I haven't gotten to this quite yet as promised, but it will be addressed soon.  And to revise what I've said above, I think I now prefer the following approach that @PaulVanSchayck suggested above
 
> How about we add a `session_cleanup=True` parameter to `execute()`? Or to the `Rule` class as parameter? So, that when you know that your rule does not require an update of information to the client, you can choose to keep the connection alive. By setting the default to true, the old behavior remains intact.

That way @gscteam  can force the updates they want, and even if sessions are (deliberately) left not cleaned up, I'll be putting in my commit for auto `cleanup` at program exit, so we're still fine.
