### ISSUE TITLE
retrieve zip files

### ISSUE THREAD

**Issue by ataravarice** [irods/python-irodsclient#201]
Hi @trel,

I tried to download zip files using irodsclient, but I only get an archive message

My code is :
```python
#get data from cyverse using irods.py
import os
import ssl
from irods.session import iRODSSession
try:
   env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
   env_file = os.path.expanduser('~/.irods/irods_environment.json')
with iRODSSession(host='data.cyverse.org', port=1247, user='', password='', zone='iplant') as session:
   pass
coll = session.collections.get("/iplant/home/shared/iVirus/GOV2.0")
for obj in coll.data_objects:
   open(obj.name,'wb').write(obj.open().read())
```
and I get a file including a message but not the file itself:
```
      1 Archive:  GOV2_viral_populations_larger_than_10KB_or_circular.zip
      2 [GOV2_viral_populations_larger_than_10KB_or_circular.zip]
      3   End-of-central-directory signature not found.  Either this file is not
      4   a zipfile, or it constitutes one disk of a multi-part archive.  In the
      5   latter case the central directory and zipfile comment will be found on
      6   the last disk(s) of this archive.
      7 zipinfo:  cannot find zipfile directory in one of GOV2_viral_populations_larger_than_10      7 KB_or_circular.zip or
      8           GOV2_viral_populations_larger_than_10KB_or_circular.zip.zip, and cannot find      8 GOV2_viral_populations_larger_than_10KB_or_circular.zip.ZIP, period.
```
I also tried 
  `open('outfile.txt','w').write(obj.open().read().decode())` and only get the same archive file 

Is there away of retrieving zip files from iRODS and store it locally?

**Comment by d-w-moore** [comment]
hello ataravarice,

Perhaps you could try an equivalent iget command and mail us the results, specifically whether the same thing happens.

i.e., does

  iget -r /iplant/home/shared/iVirus/GOV2.0

yield the same result?

thanks,

Daniel Moore
Applications Engineer
iRODS Consortium, RENCI, UNC Chapel Hill
(919) 445-9616

________________________________

**Comment by ataravarice** [comment]
Dear Moore:

Thanks for your reply, I tried "iget -r "/iplant/home/shared/iVirus/GOV2.0"" but it didn't work

my result is,the data is actually exist:
>>> obj
<iRODSDataObject 567298399 Read_me.txt>
>>> coll
<iRODSCollection 466998855 b'GOV2.0'>

but iget command cannot work:
>>> iget -r /iplant/home/shared/iVirus/GOV2.0
  File "<stdin>", line 1
    iget -r /iplant/home/shared/iVirus/GOV2.0
                                            ^
SyntaxError: invalid syntax
>>> iget -r "/iplant/home/shared/iVirus/GOV2.0"
  File "<stdin>", line 1
    iget -r "/iplant/home/shared/iVirus/GOV2.0"
                                              ^
SyntaxError: invalid syntax
>>> iget -r coll
  File "<stdin>", line 1
    iget -r coll
               ^
SyntaxError: invalid syntax
>>> 

sincerely
ataravarice

2020-06-05 

Huang Xingyu 



发件人：d-w-moore <notifications@github.com>
发送时间：2020-06-05 21:02
主题：Re: [irods/python-irodsclient] retrieve zip files (#201)
收件人："irods/python-irodsclient"<python-irodsclient@noreply.github.com>
抄送："ataravarice"<huanggreatyu@126.com>,"Author"<author@noreply.github.com>

hello ataravarice,

Perhaps you could try an equivalent iget command and mail us the results, specifically whether the same thing happens.

i.e., does

iget -r /iplant/home/shared/iVirus/GOV2.0

yield the same result?

thanks,

Daniel Moore
Applications Engineer
iRODS Consortium, RENCI, UNC Chapel Hill
(919) 445-9616

________________________________

**Comment by d-w-moore** [comment]
hi ataravarice,

The 'iget' command should be typed at the prompt (assuming you have the icommands client programs installed).

Daniel Moore
Applications Engineer
iRODS Consortium, RENCI, UNC Chapel Hill
(919) 445-9616

________________________________

**Comment by ataravarice** [comment]
Daniel Moore 

I installed icommands and tried iget -r "/iplant/home/shared/iVirus/GOV2.0" command. This method meets problems when downloading:

While it did connect to the databases,but it cannot download. The result is:

ataravarice@ubuntu:~$ ils
/iplant/home/ataravarice:
  10kb_Virsorter_95percent_cutoff.faa
  3ice_viruses_3methodsviralcontigs_10kb.faa
  3ice_viruses_contig_uniq_10kb.fa
  3ice_viruses_contig_uniq_10kb.faa
  3ice_viruses_contig_uniq_10kb_gene2genomemerge.csv
  3ice_viruses_contig_uniq_10kb_prodigaloriginal.faa
  DFL12phage_proteins.fa
  N4-likephageproteins.faa
  melt_2_core.faa
  out.fasta
  pre-vcontact.prodigal.fasta
  C- /iplant/home/ataravarice/analyses
ataravarice@ubuntu:~$ ipwd
/iplant/home/ataravarice
ataravarice@ubuntu:~$ iget DFL12phage_proteins.fa
ERROR: [-] iRODS/lib/core/src/procApiRequest.cpp:268:readAndProcApiReply :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message []
 [-] iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message [failed to call 'read header']
  [-] libtcp.cpp:193:tcp_read_msg_header :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message []
   [-] libtcp.cpp:74:tcp_socket_read :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message [error reading from socket after [0] bytes read]

[-] libnative.cpp:239:native_auth_client_request :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message [Call to rcAuthRequest failed.]

 failed with error -116104 SYS_SOCK_READ_ERR Connection reset by peer
ERROR: [-] iRODS/lib/core/src/rcConnect.cpp:265:rcDisconnect :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
 [-] iRODS/lib/core/src/sockComm.cpp:1385:sendRodsMsg :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [failed to call 'write body']
  [-] libtcp.cpp:358:tcp_send_rods_msg :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [writeMsgHeader failed]
   [-] iRODS/lib/core/src/sockComm.cpp:473:writeMsgHeader :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
    [-] libtcp.cpp:279:tcp_write_msg_header :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected -1946157056]

ataravarice@ubuntu:~$ iget "DFL12phage_proteins.fa"
ERROR: [-] iRODS/lib/core/src/procApiRequest.cpp:268:readAndProcApiReply :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message []
 [-] iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message [failed to call 'read header']
  [-] libtcp.cpp:193:tcp_read_msg_header :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message []
   [-] libtcp.cpp:74:tcp_socket_read :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message [error reading from socket after [0] bytes read]

[-] libnative.cpp:239:native_auth_client_request :  status [SYS_SOCK_READ_ERR]  errno [Connection reset by peer] -- message [Call to rcAuthRequest failed.]

 failed with error -116104 SYS_SOCK_READ_ERR Connection reset by peer
ERROR: [-] iRODS/lib/core/src/rcConnect.cpp:265:rcDisconnect :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
 [-] iRODS/lib/core/src/sockComm.cpp:1385:sendRodsMsg :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [failed to call 'write body']
  [-] libtcp.cpp:358:tcp_send_rods_msg :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [writeMsgHeader failed]
   [-] iRODS/lib/core/src/sockComm.cpp:473:writeMsgHeader :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
    [-] libtcp.cpp:279:tcp_write_msg_header :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected -1946157056]


Hope to get your reply

sincerely

Ataravarice

2020-06-06 iget

Huang Xingyu 



发件人：d-w-moore <notifications@github.com>
发送时间：2020-06-06 00:50
主题：Re: [irods/python-irodsclient] retrieve zip files (#201)
收件人："irods/python-irodsclient"<python-irodsclient@noreply.github.com>
抄送："ataravarice"<huanggreatyu@126.com>,"Author"<author@noreply.github.com>

hi ataravarice, 

The 'iget' command should be typed at the prompt (assuming you have the icommands client programs installed). 

Daniel Moore 
Applications Engineer 
iRODS Consortium, RENCI, UNC Chapel Hill 
(919) 445-9616 

________________________________

**Comment by d-w-moore** [comment]
ataravarice,

Possibly, you are encountering firewall problems that are preventing iRODS parallel downloads.  Files larger than a certain size (32 Megabytes or greater, if that setting is at its default in the  iRODS server configuration) will trigger a parallel-mode download, requiring the TCP ports from 20000 through 20199 to be allowed outgoing from the firewall.

An administrator will probably need to white-list those ports in the firewall, for connections outgoing from the server.

Daniel Moore
Applications Engineer
iRODS Consortium, RENCI, UNC Chapel Hill
(919) 445-9616

________________________________

**Comment by ataravarice** [comment]
Thanks a lot!

2020-06-09 

Huang Xingyu 



发件人：d-w-moore <notifications@github.com>
发送时间：2020-06-06 23:01
主题：Re: [irods/python-irodsclient] retrieve zip files (#201)
收件人："irods/python-irodsclient"<python-irodsclient@noreply.github.com>
抄送："ataravarice"<huanggreatyu@126.com>,"Author"<author@noreply.github.com>

ataravarice, 

Possibly, you are encountering firewall problems that are preventing iRODS parallel downloads. Files larger than a certain size (32 Megabytes or greater, if that setting is at its default in the iRODS server configuration) will trigger a parallel-mode download, requiring the TCP ports from 20000 through 20199 to be allowed outgoing from the firewall. 

An administrator will probably need to white-list those ports in the firewall, for connections outgoing from the server. 

Daniel Moore 
Applications Engineer 
iRODS Consortium, RENCI, UNC Chapel Hill 
(919) 445-9616 

________________________________

**Comment by trel** [comment]
Closing this - nothing actionable at this time.
