### ISSUE TITLE
Use of PAM auth without environment file or SSL sends password unencrypted

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#205]
If neither configured for SSL nor to go through the iRODS environment file mechanism, a request from the Python iRODS client  to authenticate to a server with PAM will send the password over the network without any kind of scrambling or encryption.

Demo script:

```python
from socket import gethostname 
from irods.session import iRODSSession

ses = iRODSSession( 
        host=gethostname(),
	user='alissa',
	zone='tempZone',
	authentication_scheme='pam',
	password='test123',
	port= 1247
)
coll_name = '/{ses.zone}/home/{ses.username}'.format(**locals())
homecol = ses.collections.get(coll_name)
print homecol
```

The traffic can be trapped using `tcpdump -vv -i lo -A  'port 1247'` and grepped for the password.

**Comment by MarkBruurmijn** [comment]
How are we now supposed to send the password for PAM authentication? Could this be added in README.rst? I'm a bit puzzled. ;)
