### ISSUE TITLE
Provide mechanism for reporting client application name to iRODS server

### ISSUE THREAD

**Issue by tedgin** [irods/python-irodsclient#211]
When an iRODS server knows the name of a connecting application, the server can provide the name in reports generated for `ips`. The iCommands do this. To let the server know its name, each iCommand populates the `option` field in the the `StartupPack_PI` XML message sent when establishing a session.

Identifying the client application in this way, would also allow a proxy, like HAProxy, to be smarter about routing iRODS clients. Since the `StartupPack_PI` message comes across as plain text, event when TLS encryption is used, a proxy could inspect this message to determine the connecting client application and possibly choose an iRODS server optimized for handling requests from this application.

Would you please extend the PRC so that an application using this library can identify itself by setting its name in the `StartupPack_PI`'s `option` field? A default value of `PRC` could be used if the application developer chooses not to identify the application.

**Comment by kript** [comment]
Does the undocumented `spOption` work for this? e.g.

`spOption=trace_me ./samtools_irods reheader -i _hdr irods:/seq/test/jkb/9233_8#168.cram`
(This will now show up via ips as application trace_me)

**Comment by d-w-moore** [comment]
I don't see the spOption environment variable being consulted, but we could consider its value in setting the client application name.

**Comment by trel** [comment]
Right, I think the behavior we could have is...

1) provide a default for all PRC connections (possibly 'python-irodsclient')
2) consult the spOption (or some better named ENV variable)
3) provide a facility for easily setting the PRC application name in Python (an optional `application_name` parameter to `iRODSSession`)

Open question would be priority of 2) ENV over 3) application_name, or vice versa...

Or, even better, not to offer 2) ENV at all... (I'm leaning towards this solution).

**Comment by d-w-moore** [comment]
I'm good either way... some of the icommands (notably `irule`) respect spOption.

**Comment by kript** [comment]
We make use of `spOption` a lot to show versions of tools like baton, tears etc, its very helpful to have something like that, so I'd rather it wasn't deprecated (which might be the implication of @trel suggestion above) at least without it being replaced by something consistently across icomands/this/others. 

However, I think people would appreciate it being documented if its honoured, but that's out of the scope of this request!

**Comment by trel** [comment]
Good to know - didn't realize you were using this regularly.

I was not suggesting it be deprecated where it already works - just not adding an esoterically-named thing to the PRC if we don't have to.

@kript Would it be sufficient for you to have just 1) and 3)?   No use of ENV at all for a Python application?

**Comment by trel** [comment]
@d-w-moore this is done?   can we close?

**Comment by trel** [comment]
commit 6f7be52 sets the following, with highest precedence first...
1) environment variable `spOption`
2) 'application_name' set in `StartupPack()` and/or connection pool creation
3) default `python-irodsclient`

**Comment by d-w-moore** [comment]
Yes, this issue can be closed.
