### ISSUE TITLE
Need to renew stale connections being reactivated from idle pool

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#220]
We need to detect if connections being brought out of an idle pool have been dropped by the iRODS server to which they were last connected.  Ultimately it would be nice to do this through some empirical but non-invasive operation (ie attempting a NOP and catching the socket errors) done when the idle connection is being brought back into service, but for now it would suffice to time them out based on a predetermined interval.

See discussion in #218

**Comment by trel** [comment]
re-opening for a fix
