### ISSUE TITLE
no kerberos support

### ISSUE THREAD

**Issue by cmeesters** [irods/python-irodsclient#223]
Hi,

our irods server is authenticated by kerberos. Hence, the configuration reads

`"irods_authentication_scheme": "KRB"`

Consequently python-irodsclient fails with `Unknown authentication scheme krb`

Thing is, that on our cluster we have a global "irods_environment.json" and there is no good alternative to kerberos with our setup (which has to be global on the entire campus). Hence, the workflow would be to get a kerberos ticket and subsequently all i-commands will be able to access the irods-host. This could be done prior to working with the python-irodsclient-module.

Has a support for kerberos ever been contemplated? Currently, there are "only"  NATIVE_AUTH_SCHEME, GSI_AUTH_SCHEME, resp. PAM_AUTH_SCHEME. 

Best regards,
Christian Meesters

**Comment by trel** [comment]
similar/identical to https://github.com/irods/python-irodsclient/issues/34

**Comment by cmeesters** [comment]
Missed this one (you just opened it), sorry. Could you elaborate how you would like to proceed in this regard? #34 mentions version 4.2 as a milestone, where this should be implemented. We are running 4.2.6 (which is fairly recent).

**Comment by trel** [comment]
We have not had any demand/conversation around this since late 2016.   Not sure if @boombard made any progress in copying the GSI work.

I'm going to mark this as duplicate - let's move back over to #34 in case they know things...
