### ISSUE TITLE
Cannot set password of users with no current password

### ISSUE THREAD

**Issue by RubenGarcia** [irods/python-irodsclient#224]
Running
```
session = iRODSSession(...)
session.users.modify(user, "password", password, zone)
```
on a user without a password fails with
```
TypeError: 'NoneType' object is not subscriptable
```
because the new password is being scrambled with the old one in /irods/password_obfuscation.py#L267.
If oldpassword is None, possibly use empty string instead? Or a random string?

**Comment by d-w-moore** [comment]
@RubenGarcia I haven't been able to reproduce this issue using the current _python-irodsclient_ release. I've created a user **alice** on irods 4.2.8 
```
 irods$ mkuser alice rodsuser
```
without setting her password, and then run the following code using a rodsadmin authentication session:
```
session.users.modify("alice","password","alice99","tempZone")
```
I was then able to authenticate alice to iinit using the password "alice99" (on a separate /home/ubuntu account)
Maybe I'm missing something in my interpretation.

**Comment by RubenGarcia** [comment]
Can you confirm the value of second_key on
```
def scramble_v2(s, first_key, second_key):
    to_scramble = random.SystemRandom().choice(string.printable) + v2_prefix[1:10] + s[:150]
    key = first_key[:90] + second_key[:100]
```
when you do that? Because when I do it, second_key==None

**Comment by RubenGarcia** [comment]
We are using https://github.com/theferrit32/python-irodsclient/tree/openid so there may have been a bugfix in the mean time. I'll try to merge and investigate.

**Comment by RubenGarcia** [comment]
I applied the latest changes, but I still get the same error.

**Comment by RubenGarcia** [comment]
After evaluation, it's conn.client_signature the None which is giving issues.

**Comment by d-w-moore** [comment]
Ok, I will need to set up a test bed with OpenID . I am not terribly familiar with it nor with Kyle's fork of the python irods client, so it may take a little while.

**Comment by d-w-moore** [comment]
@RubenGarcia I'm a little bit unclear on the changing of one's own password. In the irods native scheme, that would only work if the user in question were a rods admin , because admin API's are closed to rods users.  If it's the OpenID password we're changing, seems then we would need a totally new hook for that, which will be independent of the native scheme, yes?

**Comment by RubenGarcia** [comment]
I'm trying to change a user password while being authentificated as the rods user via OpenID.
But I'm surprised you don't have any issue with the old user password being None, in the NATIVE_AUTH_SCHEME.

**Comment by d-w-moore** [comment]
Forcing the password value of None to an empty string before sending it through obfuscation does seem a good idea.  Of course, I'd like to put some tests around that and the OpenID if we were looking at merging it into an official iRODS release.

**Comment by RubenGarcia** [comment]
Looks like a good plan for me.

**Comment by trel** [comment]
Closing - as related to https://github.com/irods/python-irodsclient/issues/130
