### ISSUE TITLE
Setting permissions for users from a different zone gives CAT_INVALID_ARGUMENT

### ISSUE THREAD

**Issue by RubenGarcia** [irods/python-irodsclient#231]
```
user='user'
session.users.create(user, user_type, zone, auth_str)
home_dir = "/" + zone + "/home/" + user
home_coll = session.collections.get(home_dir)

session.users.create(user, user_type, fed_zone, auth_str)
acl_user_fed = iRODSAccess("own", home_coll, user, fed_zone)
#everything looks ok until this line
session.permissions.set(acl_user_fed)
#^this line fails
```
fails with the following error:
```
CAT_INVALID_ARGUMENT
Input path is not a collection and not a dataObj: <iRODSCollection 40432 b'user'>
```
The error seems bogus, since iRODSCollection is obviously a collection. Can anybody confirm the error and investigate?
Thank you.

**Comment by d-w-moore** [comment]
@RubenGarcia   - did some investigation. 

Are you sure your  _home_dir_  path  in the above example
 (a) is a pre-existing collection and  
 (b) has **own** permissions already set for the holder of the `session` object trying to grant access for the other-zone user?

Given that these two conditions are satisfied, I wasn't able to reproduce your error (here I'm the `rods` admin):
```
## --- example giving bobby#zoneB own permissions on /zoneA/public/home/forbobbyB ---
user='bobby'
user_type = 'rodsuser'
zone = this_zone = 'zoneA' ; fed_zone = 'zoneB'
auth_str = ''
_bobby_zoneB = session.users.create(user , user_type , fed_zone , auth_str)
from irods.access import iRODSAccess
acl_user_fed = iRODSAccess("own", "/zoneA/home/public/forbobbyB",  (_bobby_zoneB).name , (_bobby_zoneB).zone )
session.permissions.set(acl_user_fed)  #__>> no error here ... and affirmed that bobby#zoneB could see the colln from his zone

```
However, if  I try  giving access  to a not-already-existing collection , I get your error:
```
>>> acl_user_fed = iRODSAccess("own", "/zoneA/home/public/forbobbyBCDEF", user, fed_zone)
session.permissions.set(acl_user_fed)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "irods/manager/access_manager.py", line 130, in set
    response = conn.recv()
  File "irods/connection.py", line 102, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_INVALID_ARGUMENT: Input path is not a collection and not a dataObj: /zoneA/home/public/fo
rbobbyBCDEF

```

**Comment by d-w-moore** [comment]
@trel - I dont think this is a bug; at worst, it appears to be a bad error message

**Comment by trel** [comment]
okay, if there is a better error message, let's propose it and still call it a bug :)

**Comment by d-w-moore** [comment]
Agreed. Error message could be better. And in the meantime, @RubenGarcia I've seen that if the permissions-setting user local to the zone does not own the target collection, the error will be a irods.exception.CAT_NO_ACCESS_PERMISSION instead.

So, I suspect this is a case of the target collection not existing. Hence the "is not a collection and not a dataObj"

**Comment by RubenGarcia** [comment]
Interesting. As you see in my example, I'm using the home directory of the user, which should exist. But I will verify in case there is something funny going on.

**Comment by d-w-moore** [comment]
@RubenGarcia I think the home directory will be of the form /thisZone/home/user#thatZone, as opposed to just /thisZone/home/user , as I believe your initial example would have assumed.

**Comment by RubenGarcia** [comment]
The main zone is ZoneA. The federated zone is ZoneB.
When I created the user for ZoneA, the home is /ZoneA/home/user, not /ZoneA/home/user#ZoneA
I want to give user#ZoneB permission on /ZoneA/home/user.
Code: 
```
  session.users.create(user, user_type, zone, auth_str)
    group.add_newuser_to_lexis_group(session, user)
    home_dir = "/" + zone + "/home/" + user
    home_coll = session.collections.get(home_dir)
    for fed_zone in federated_zones:
        username = user + "#" + fed_zone
        session.users.create(user, user_type, fed_zone, auth_str)
        group.add_newuser_to_lexis_group(session, username)
        acl_user_fed = iRODSAccess("own", home_coll, user, fed_zone)
        session.permissions.set(acl_user_fed)
```

**Comment by RubenGarcia** [comment]
I am using irods 4.2.3, maybe that is the issue.

**Comment by d-w-moore** [comment]
I wouldn't expect the iRODS version difference to be significant , unless maybe a federation bug was fixed since 4.2.3.  Good point about the <iRODSCollection> vs literal path string in the log text -- it makes me wonder if other differences between the two code-bases that are coming into play here.

**Comment by RubenGarcia** [comment]
I found why I'm getting 
 Input path is not a collection and not a dataObj: <iRODSCollection 40737 b'test1234'>
I was passing a collection and not a path. 
May be we could change the error to indicate explicitly "The input path must be a string"?
Or accept the collections?

**Comment by d-w-moore** [comment]
Maybe. Or, since the managers' methods generally only take strings and options parameters, so perhaps we just add a note to that effect into the readme.

**Comment by RubenGarcia** [comment]
The new code seems to work correctly now, so I'm closing the issue.
