### ISSUE TITLE
Enable Case-Insensitive Queries

### ISSUE THREAD

**Issue by GeoJosh** [irods/python-irodsclient#234]
Currently there appears to be a [placeholder reference](https://github.com/irods/python-irodsclient/blob/master/irods/query.py#L22) to utilize uppercase where queries.

iRODS definitely supports this capability through several iCommands. Furthermore, this capability could be alternately utilized through creation of a `SpecificQueryRequest` with associated SQL. However it would be nice to enable this capability through the generic `Query` object or as a chained function.

**Comment by trel** [comment]
Ah yes.

[The upper flag is used by `iquest`](https://github.com/irods/irods_client_icommands/blob/09d8652839fbd21818a0e088457ceecfab242211/src/iquest.cpp#L42)

**Comment by alanking** [comment]
This has been enabled through the new `case_sensitive` argument in the `Query` object. Closing
