### ISSUE TITLE
DataObjectManager.open() ignores DEST_RESC_HIER_KW

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#243]
As of PRC version 0.8.5 , a data object open( ) call respected DEST_RESC_NAME_KW but ignored DEST_RESC_HIER_STR_KW, so that  low-level open( ) calls from within parallel put  were opening  replicas on the default resource , even if a different resource was being targeted by the put request.

This has been addressed in #236

**Comment by trel** [comment]
just point to this issue in the parallel transfer PR with a particular commit?

**Comment by d-w-moore** [comment]
Yes.Just documenting why the change was done.

**Comment by trel** [comment]
yeps, bread crumbs for the future.

**Comment by d-w-moore** [comment]
Works with automated ingest Operation.PUT .  Will need to test more thoroughly, but I don't anticipate these changes interfere with ingest via registration.

**Comment by d-w-moore** [comment]
Ah, has not been addressed yet, so leaving open
https://github.com/irods/python-irodsclient/blob/e00523bcc159d4e55a7d1920a0bb8e345bf38796/irods/manager/data_object_manager.py#L224
needs to also check for RESC_HIER_STR_KW

**Comment by alanking** [comment]
This has been addressed here: a23f34af6987c3fe12962c8415f81f9f77818146

See also: https://github.com/irods/python-irodsclient/pull/414

**Comment by korydraughn** [comment]
Yeah, let's close this if it has been resolved.
