### ISSUE TITLE
Can multiple AVUs be added to an object/file with one call/exchange with server?

### ISSUE THREAD

**Issue by BlakeGFitch** [irods/python-irodsclient#244]
I'm adding files and then adding ~10 AVUs. Adding the AVUs takes around 3x as long as adding the object. 

Is it possible to have an interfaces that added a set of AVUs to an object with one call and one exchange with server? 

Would doing this reduce the cost of adding AVUs?

Thanks!!

**Comment by trel** [comment]
As of 4.2.8 on the server-side... yes.   

https://github.com/irods/irods/issues/4484

But not yet implemented in the Python client.    We can implement it without too much trouble.

**Comment by trel** [comment]
done!     will be in the next release soon.
