### ISSUE TITLE
ichksum equivalent?

### ISSUE THREAD

**Issue by holtgrewe** [irods/python-irodsclient#246]
Hi, is it possible to implement the equivalent of `ichksum` with python-irodsclient? Eventually I want to roll out a tool on Windows and as irods-icommands are not available there I'm looking for a workaround.

**Comment by trel** [comment]
This should be possible - all the parts exist already, I believe.

**Comment by d-w-moore** [comment]
I expect this is not too difficult.  Query for existing checksums is the easy part, I shall have to check into what the API looks like for getting a server to (re-)compute a checksum

**Comment by trel** [comment]
@korydraughn what's the API for this?     just the same call as 'give me the one that exists'... right?    the server will calculate one if it doesn't already exist...

**Comment by korydraughn** [comment]
Yes. ichksum will return the existing checksum when the force flag is not provided. If the force flag is provided, a new checksum will be calculated and stored in the catalog. If a checksum does not exist, it is calculated and stored in the catalog.

**Comment by d-w-moore** [comment]
Ah, I need to try that out. Probably just need a force flag in **options.  Do we store a checksum per replica now, or is it just one checksum describing the (hopefully "one true") non stale replica?  Or should I expect a different checksum per replica, if I provide a RESC_NAME_KW to the API ?

**Comment by trel** [comment]
Checksum per replica.  Default behavior is to return the value of a good replica.

The help text has been rewritten and should have what you need...

https://github.com/irods/irods_client_icommands/blob/bebb17bdead123579dd41818565f430e1af67875/src/ichksum.cpp#L102-L112

**Comment by d-w-moore** [comment]
Looks like PRC gives per replica access to the different checksums. I should probably write a test around  directing a checksum computation at a specific replica, too.

**Comment by d-w-moore** [comment]
The commits for this checksum feature now sit comfortably inside (near the top of) what I'm now thinking of as the [kitchen sink PR](https://github.com/irods/python-irodsclient/pull/262).  Could go ahead and close the [pull request](https://github.com/irods/python-irodsclient/pull/247) currently associated with this issue, in favor of the other one.

**Comment by trel** [comment]
we'll link to the merged code again once it's landed.    then we'll close this issue.
