### ISSUE TITLE
PRC presents itself to servers as a 4.3.0 compatible client

### ISSUE THREAD

**Issue by korydraughn** [irods/python-irodsclient#253]
https://github.com/irods/python-irodsclient/blob/c2df75236387a5c817f7399cab31aff81680fb99/irods/message/__init__.py#L13
https://github.com/irods/python-irodsclient/blob/c2df75236387a5c817f7399cab31aff81680fb99/irods/message/__init__.py#L203

**Comment by d-w-moore** [comment]
I guess that we can close this one since PRC is now 4.3.0-compatible? Should we replace it with an issue/request about whether PRC should reflect the max server vsn it is capable of communicating with in the relVersion field?

**Comment by korydraughn** [comment]
> I guess that we can close this one since PRC is now 4.3.0-compatible?

Sounds good.

> Should we replace it with an issue/request about whether PRC should reflect the max server vsn it is capable of communicating with in the relVersion field?

I'm not sure what you mean by "replace it with an issue/request". Please explain.

As for whether the PRC should reflect the max server version, yes it should.

**Comment by trel** [comment]
Max server version - in a client?   It will always be slightly out of date and require us to keep updating the value...  or maybe that's what we already have, and we just haven't been updating it very often...

**Comment by korydraughn** [comment]
Good clients must report the server version they are maximally compatible with else they run the risk of using old behavior (e.g. bad packstruct/xml encoding - apos vs graves).

**Comment by trel** [comment]
Fair enough - so... there's nothing to do here?    4.3.0 is... still true.

**Comment by d-w-moore** [comment]
Will close then.  @korydraughn my issue /request question is whether I should open a new issue requesting the continual update of the IRODS_VERSION string to reflect maximum server version with which we're compatible.  Without a reminder we might forget....

**Comment by korydraughn** [comment]
Yeah, I don't think we need an issue for that.

Like @trel said, if we can write a test that fails when the server's version is greater than what is reported by the PRC, then we're good.

**Comment by d-w-moore** [comment]
Closing now that we are compatible at IRODS_VERSION = (4,3,0,'d') and #418 has been opened
