### ISSUE TITLE
error importing iRODSSession

### ISSUE THREAD

**Issue by kript** [irods/python-irodsclient#254]
N.B. I get this with python2 or python3 and whether it's from the git master or for e.g. 0.8.5;

```
root@client:/# python3 -m venv /tmp/prc_v3_git
root@client:/# source /tmp/prc_v3_git/bin/activate
(prc_v3_git) root@client:/# pip install git+https://github.com/irods/python-irodsclient.git
Collecting git+https://github.com/irods/python-irodsclient.git
  Cloning https://github.com/irods/python-irodsclient.git to /tmp/pip-efdmutwe-build
Collecting six>=1.10.0 (from python-irodsclient===0.8.6)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting PrettyTable>=0.7.2 (from python-irodsclient===0.8.6)
  Using cached https://files.pythonhosted.org/packages/94/d5/52e48f3bcf66f838d411ad85c3ac9550c2451d082623e2d4d4df7411ed5c/prettytable-2.0.0-py3-none-any.whl
Collecting xmlrunner>=1.7.7 (from python-irodsclient===0.8.6)
  Using cached https://files.pythonhosted.org/packages/57/c0/a19e29bc6038a56bb690549573af6ea11a9d2a5c07aff2e27ed308c2cab9/xmlrunner-1.7.7.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in /tmp/prc_v3_git/lib/python3.5/site-packages (from PrettyTable>=0.7.2->python-irodsclient===0.8.6)
Collecting wcwidth (from PrettyTable>=0.7.2->python-irodsclient===0.8.6)
  Using cached https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Building wheels for collected packages: xmlrunner
  Running setup.py bdist_wheel for xmlrunner ... error
  Complete output from command /tmp/prc_v3_git/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5bnfh3z4/xmlrunner/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp8s47l5h1pip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for xmlrunner
  Running setup.py clean for xmlrunner
Failed to build xmlrunner
Installing collected packages: six, wcwidth, PrettyTable, xmlrunner, python-irodsclient
  Running setup.py install for xmlrunner ... done
  Running setup.py install for python-irodsclient ... done
Successfully installed PrettyTable-2.0.0 python-irodsclient-0.8.6 six-1.15.0 wcwidth-0.2.5 xmlrunner-1.7.7
You are using pip version 8.1.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(prc_v3_git) root@client:/# python3
Python 3.5.2 (default, Oct  7 2020, 17:19:02)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import ssl
m irods.session import iRODSSession>>> from irods.session import iRODSSession
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/prc_v3_git/lib/python3.5/site-packages/irods/session.py", line 5, in <module>
    from irods.query import Query
  File "/tmp/prc_v3_git/lib/python3.5/site-packages/irods/query.py", line 13, in <module>
    from irods.results import ResultSet, SpecificQueryResultSet
  File "/tmp/prc_v3_git/lib/python3.5/site-packages/irods/results.py", line 2, in <module>
    from prettytable import PrettyTable
  File "/tmp/prc_v3_git/lib/python3.5/site-packages/prettytable/__init__.py", line 3, in <module>
    from .prettytable import (
  File "/tmp/prc_v3_git/lib/python3.5/site-packages/prettytable/prettytable.py", line 250
    raise Exception(f"Index {index} is invalid, must be an integer or slice")
                                                                           ^
SyntaxError: invalid syntax
>>> from irods.session import iRODSSession
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/prc_v3_git/lib/python3.5/site-packages/irods/session.py", line 5, in <module>
    from irods.query import Query
  File "/tmp/prc_v3_git/lib/python3.5/site-packages/irods/query.py", line 13, in <module>
    from irods.results import ResultSet, SpecificQueryResultSet
  File "/tmp/prc_v3_git/lib/python3.5/site-packages/irods/results.py", line 2, in <module>
    from prettytable import PrettyTable
  File "/tmp/prc_v3_git/lib/python3.5/site-packages/prettytable/__init__.py", line 3, in <module>
    from .prettytable import (
  File "/tmp/prc_v3_git/lib/python3.5/site-packages/prettytable/prettytable.py", line 250
    raise Exception(f"Index {index} is invalid, must be an integer or slice")
                                                                           ^
SyntaxError: invalid syntax
```

**Comment by kript** [comment]
It appears [prettytable was bumped to 2.0.0](https://pypi.org/project/prettytable/#history) in November, and this broke something. 1.0.1 still appears to work

**Comment by kript** [comment]
Ah, another hint, it appears that prettytable 2.0.0 has `requires-python:>=3.6` and this is newwer than a lot of people's python, such as the default Ubuntu 16.04 (used by irods-demo's client docker image for example).

**Comment by trel** [comment]
the internet... "e pur si move"

grazie.

**Comment by kript** [comment]
A bit further digging by others at the same time implies that the python client only actually needs `prettytable==0.7.2` to install both python2 and python3. If thats confirmed by your testing, could we get [                        'PrettyTable>=0.7.2',](https://github.com/irods/python-irodsclient/blob/c2df75236387a5c817f7399cab31aff81680fb99/setup.py#L41) changed to `'PrettyTable==0.7.2',`? Happy to do an MR...

**Comment by d-w-moore** [comment]
@kript -  Since the official dropping of support for Python2, we've also encountered problems with pip/virtualenv installs on Python2.7  going sour, and ultimately in most cases it seems to be Python3-centric developmental changes to  pip, PyPI packages and such that cause it. I've [documented](https://github.com/d-w-moore/python-irodsclient/blob/file_desc/PYTHON_install_caveats.rst) this and what to do about it, so what I'll do for now is sugguest you try the below (essentially the python3 version of what I worked out for py-2.7) and see if it works any better.  
It seems to work fine for importing and minimally using  iRODSSession  in my case, on a  sparkly new docker container.

As a non-root user:
```
$ pip3 --version   # should yield something 8- or 9-ish unless you've upgraded; if not, a "rm -fr ~/.local/lib/python3.5" should revert
$ pip3 install --upgrade --user pip==20.3.4    # --> known sane version of pip
$ python3 -m pip install virtualenv
$ python3 -m virtualenv /tmp/py3env ; source /tmp/py3env/bin/activate
(py3env) $ cd ~/python-irodsclient(v0.8.5) ; pip install .
```

**Comment by d-w-moore** [comment]
@kript - one more thing - you may experience this:
```
<error dump including:> ...
FileExistsError: [Errno 17] File exists: '/home/dan/.local/share/virtualenv/wheel/3.5
```
upon your first (but only first apparently) use of the virtualenv command to create a new python environment under python3.5.  It succeeds nonetheless and further uses of virtualenv will be also successful and much less "error-verbose".

Upon installing my own python environments (using the formula i laid out in the last comment) -- one using v0.8.5 and the other from master branch of the Python iRODS client -- I found both working as expected with my PRC / iRODSSession test, and that each  had appropriately chosen the 1.0.1 version of prettytable to install.  I have to conclude there is some internal dependency checking that pip 20.3.4 does better, in terms of servicing the older versions of Python(2.7 and 3.5 included), than do more recent pip versions.

**Comment by kript** [comment]
> 
> @kript - Since the official dropping of support for Python2, we've also encountered problems with pip/virtualenv installs on Python2.7 going sour, and ultimately in most cases it seems to be Python3-centric 

Thanks for the updated virtualenv instructions, some helpful hints - can a pointer for that be added to the Readme on the install instructions please? 
I'll try and test if that removes the requirement for a lower version of PrettyTable on Ubuntu 16.04.

I wasn't aware of the python2 deprecation, especialy as the Readme.rst says;

>Currently supported:
>
>    Python 2.7, 3.4 or newer

Could it be updated please? :-)

**Comment by trel** [comment]
> Since the official dropping of support for Python2

I think Dan was referring to Python2 itself, rather than our support for it.   We will update our documentation to mention Python3 only, as soon as we get all this squared up.

I am assuming as we lean into v1.0.0 of this library, we will support only Python3.

**Comment by d-w-moore** [comment]
Sorry for the confusion. Yes, "Python Official" is no longer supporting older versions, but we are endeavoring to keep 2.7 and >=3.4 compatibility : )

**Comment by kript** [comment]
> 
> 
> Sorry for the confusion. Yes, "Python Official" is no longer supporting older versions, but we are endeavoring to keep 2.7 and >=3.4 compatibility : )

Ah! Thanks folks, I think thats very generous, but having a clear roadmap as to whn you wont will also be appreciated. We've almost converted all of our python2 scripts, but not all, and I'm sure others are in the same boat!

**Comment by trel** [comment]
We are planning to drop support for Python2 with iRODS 4.3.0 and python-irodsclient 1.0.0.

- iRODS 4.3.0 will be as soon after 4.2.9 is safely possible, hoping by June 2021 (iRODS User Group Meeting).
- iRODS python-irodsclient 1.0.0 will be as soon as we have parallel transfer landed and some community members have had a chance to break it for a couple months.

**Comment by kript** [comment]
Thanks Folks - @d-w-moore 's updated `virtualenv` notes worked for me and dont require me to use a downgraded version of prettytable...

**Comment by d-w-moore** [comment]
Also worth noting, substituting `<21.0` for `==20.3.4` in the **pip** version may be more future-proof - reason being version 21 is the established cutoff point  for Python 2 retro-compatibility.
