### ISSUE TITLE
Metadata added by atomic metadata operations not visible during session

### ISSUE THREAD

**Issue by jefscheepers** [irods/python-irodsclient#255]
Hello all,

We recently started using the newly added atomic metadata operations.  
This seems to work fine: if we add avu's to e.g. an object, we can see these afterwards with `imeta ls -d`. 
However, trying to print the newly added metadata during the script (e.g. with `obj.metadata.items()` )  returns an empty list.   
It seems like these added avu's become available only after the irodssession/the running of the script, whereas with the old method of adding metadata, this worked fine. Is this normal?

To illustrate what I mean (using PRC version 0.8.6 in both cases):

* Old method
``` python
list = []
for i in range(5):
    avu = (f"attr{i}", f"val{i}")
    list.append(avu)
for i in list:
    obj.metadata.add(i[0], i[1])
print(obj.metadata.items())
```
Output:
```
[<iRODSMeta 10792926 attr0 val0 None>, <iRODSMeta 10792929 attr1 val1 None>, <iRODSMeta 10792932 attr2 val2 None>, <iRODSMeta 10792935 attr3 val3 None>, <iRODSMeta 10792938 attr4 val4 None>]
[<iRODSMeta 10792926 attr0 val0 None>, <iRODSMeta 10792929 attr1 val1 None>, <iRODSMeta 10792932 attr2 val2 None>, <iRODSMeta 10792935 attr3 val3 None>, <iRODSMeta 10792938 attr4 val4 None>]
```

* Atomic metadata operations
```python
list = []
for i in range(0, 5):
    avu = (f"attr{i}", f"val{i}")
    list.append(avu)
obj.metadata.apply_atomic_operations(*[AVUOperation(operation='add', avu=iRODSMeta(*obj_avu)) for obj_avu in list])
print(obj.metadata.items())
```
Output:
```
[]
[]
```

Result of `imeta ls  -d <filename>` (in both cases):
```
attribute: attr0
value: val0
units:
----
attribute: attr1
value: val1
units:
----
attribute: attr2
value: val2
units:
----
attribute: attr3
value: val3
units:
----
attribute: attr4
value: val4
units:
```

**Comment by trel** [comment]
Thanks @jefscheepers - please confirm this is now working as expected and we'll close it.

**Comment by jefscheepers** [comment]
Thank you for your work, but unfortunately, it doesn't work as expected for me yet.
I downloaded the latest committed version from GitHub, but after assigning metadata through atomic operations, obj.metadata.items() still stays empty for me.

Did the tests you wrote (test_atomic_metadata_operation_for_data_object_244(self)) resolve correctly? I'm just asking because I tried to write something very similar and here again, obj.metadata.items() stayed empty (while the AVU's were actually added, as imeta ls showed).

**Comment by d-w-moore** [comment]
@jefscheepers Perhaps try the following -
```sh
#!/bin/sh
nt=''
for TEST in \
  test_atomic_metadata_operations_244               \
  test_atomic_metadata_operation_for_resource_244    \
  test_atomic_metadata_operation_for_data_object_244 \
  test_atomic_metadata_operations_255
do
    python -m unittest irods.test.meta_test.TestMeta.$TEST || {
        echo "'$TEST' failed."; exit 1;
    }
    nt="$nt."
done
echo "tests passed: " `echo -n $nt |wc -c`
```
If any tests fail (particularly for 255) , then (assuming that you've installed the PRC from a cloned git repository  using something like  `cd python-irodsclient ; pip install -e .`), you can 
try inserting the line `print("*** reset META ***")` at line 105 of `irods/meta.py` (either before or after the call to the _reset_metadata method that was introduced by this [newest](https://github.com/irods/python-irodsclient/commit/13594d06f1806276be568b2b8e32a6d81602b2c0) commit on master - if then you don't see the *** reset META *** message at least once for each of the 4 tests run, it is possible your system doesn't have this latest code installed.
I may  be wrong, but the tests do currently pass on my system.

**Comment by d-w-moore** [comment]
@jefscheepers I also ran the same test code that yielded the empty lists as output in your listing above, and (when the #255 fix is applied) my output lists were not empty, but contained the expected AVU's.

**Comment by d-w-moore** [comment]
@jefscheepers I've split the issue 255 fix from master  [here  ](https://github.com/d-w-moore/python-irodsclient/tree/issue_255_master_split) - so it's more convenient for us both to try the atomic metadata tests (from the Bourne shell script above) both with (SHA = 3e92f701adb3806757bb0a56500547a9c2a7d796) and without (SHA = de34987d4fadcdcc681d48f28d5b5a044f6b146c ) the actual fix. 
The result I get on the tip of this git branch is 4/4 tests passed and, as I'd predict, 3/4 (the test for the issue 255 fix failing) on the next--to-most-recent latest commit of that branch.

Can you test conveniently on your end with an editable pip install in the PRC repo  and let me know if you're still able to reproduce your error?

**Comment by jefscheepers** [comment]
@d-w-moore Thank you for providing the test script. I have  installed the latest version of the PRC in a docker container and am able to confirm that your solution works there. However, so far the solution doesn't work in our production environment, hence my late response.
