### ISSUE TITLE
Is there a way to get SSL without irods_environment.json and without .irodsA ?

### ISSUE THREAD

**Issue by fh-afk** [irods/python-irodsclient#257]
The paragraph about establishing a secure connection is nicely explained, but I do not want to require the users to work with the iRODS cli.
I want the users to be able to establish a secure PAM login with Active Directory credentials with the python-irodsclient, without necessarily having to deal with any other iRODS client, not only for convenience, but also for platform independence.

**Comment by d-w-moore** [comment]
@fh-afk We've verified PAM authentication can be used with or without an environment file. (When the environment is not stored in the filesystem, PAM credentials - including password - can be included within the parameter list given to iRODSSession, as long as the connection uses SSL.) Examples / tests are in : `irods/test/login_auth_test.py`

**Comment by fh-afk** [comment]
Thanks for the hint. It does not look exactly straight forward to understand, but good to know there is a solution for my needs! I will try.

**Comment by trel** [comment]
I'm not sure, but I believe this is the syntax:

```
>>> import ssl
>>> from irods.session import iRODSSession
>>> ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)
>>> ssl_settings = {'ssl_context': ssl_context}
>>> with iRODSSession(host='localhost', port=1247, user='bob', password='1234', zone='tempZone', **ssl_settings) as session: 
...     pass
```

If this is correct - we'll get it into the README as another example.

**Comment by fh-afk** [comment]
trel, if I try that (modified according to my iRODS system) and I have set `acPreConnect(*OUT)` { *OUT="CS_NEG_REQUIRE"; }` on the server, I get `[SSL is required by the server but not requested by the client]` in my rodsLog.
I also tried setting a real certificate file instead of "None" which might be neccessary since I use a self-signed certificate on my test system. Something is still missing.

**Comment by trel** [comment]
Hmm... So, can you connect via SSL without the PAM layer?   Just native iRODS credentials for a new rodsuser, same syntax...?

**Comment by fh-afk** [comment]
The server currently accepts only PAM+SSL, which works just fine with other clients like CLI, metalnx or davrods. To me rodsLog looks like this python code does not actually ask iRODS for an SSL-connection. If I switch to `acPreConnect(*OUT) { *OUT="CS_NEG_DONT_CARE"; }` on the server I get a connection.

**Comment by trel** [comment]
Hmmm, you can set the 'client_server_policy' you send to the server in your `ssl_settings`...

https://github.com/irods/python-irodsclient/issues/134#issuecomment-401008231

```
                    'client_server_policy': 'CS_NEG_REQUIRE',
```

Then both sides will be configured to REQUIRE...

**Comment by fh-afk** [comment]
Like this?
`ssl_settings = {'client_server_policy': 'CS_NEG_REQUIRE','ssl_context': ssl_context}`
No change.

**Comment by trel** [comment]
Ah, probably need all of those settings...
they'd be required in the `irods_environment.json` file if you were using one...

Try...

```python
import ssl
from irods.session import iRODSSession

ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)

ssl_settings = {'client_server_negotiation': 'request_server_negotiation',
                'client_server_policy': 'CS_NEG_REQUIRE',
                'encryption_algorithm': 'AES-256-CBC',
                'encryption_key_size': 32,
                'encryption_num_hash_rounds': 16,
                'encryption_salt_size': 8,                        
                'ssl_context': ssl_context}

with iRODSSession(host='localhost', port=1247, user='bob', password='1234', zone='tempZone', **ssl_settings) as session:
    pass
```

**Comment by d-w-moore** [comment]
@fh-afk After you've gotten the SSL working on its own, using PAM should just be a matter of furnishing the user and password, and adding a keyword of  `authentication_scheme = 'pam'` into the iRODSSession constructor, or add the equivalent keyword/value to any **options dictionary you're using in the call.
https://github.com/d-w-moore/python-irodsclient/blob/c2df75236387a5c817f7399cab31aff81680fb99/irods/test/login_auth_test.py#L256

**Comment by fh-afk** [comment]
PAM already works, I can easily see that when deactivating SSL on the server.
I tried your recent code and this changed something in rodsLog, I now get `[SSL_HANDSHAKE_ERROR]` and `[error calling SSL_accept | error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca]` and my little script threw  `[SSL: CERTIFICATE_VERIFY_FAILED]

I expected this, since my certificate is self-signed, so I changed cafile from "None" to a the real certificate and now the connection seemed to work.
However, my rodsLog showed `[SSL_SHUTDOWN_ERROR]` which can be fixed with `session.cleanup()` So I think the correct syntax for my case is something like this:

import ssl
from irods.session import iRODSSession 

ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile='CERTNAME.crt', capath=None, cadata=None)

ssl_settings = {'client_server_negotiation': 'request_server_negotiation',
                'client_server_policy': 'CS_NEG_REQUIRE',
                'encryption_algorithm': 'AES-256-CBC',
                'encryption_key_size': 32,
                'encryption_num_hash_rounds': 16,
                'encryption_salt_size': 8,                        
                'ssl_context': ssl_context}

with iRODSSession(host='HOSTNAME AS DEFINED BY CERT', port=1247, user='USERNAME', password='PASSWORD', zone='ZONE', **ssl_settings) as session: 
	pass


#actual workload

session.cleanup()

From my point of view, the problem is solved, thank you very much for your quick response, you were very helpful!

**Comment by trel** [comment]
Excellent.   Will add this example to the README.

Note, if you do the workload 'inside' the `with`, I believe the session will cleanup itself.

**Comment by trel** [comment]
@fh-afk can you confirm the behavior of

```
with iRODSSession(host='HOSTNAME AS DEFINED BY CERT', port=1247, user='USERNAME', password='PASSWORD', zone='ZONE', **ssl_settings) as session: 
    #actual workload
```

does not require a call to `session.cleanup()`?

**Comment by fh-afk** [comment]
@trel That seems to work without showing errors in rodsLog.

**Comment by trel** [comment]
Perfect.   Thanks.

**Comment by fh-afk** [comment]
@trel I saw you updated the Readme. Great. However, host='HOSTNAME_DEFINED_IN_CERTNAME.crt' might be a bit confusing since ".crt" should not be part of that string, except of course crt is the top level domain. Just a minor detail, have a nice day.

**Comment by trel** [comment]
fair enough - how about `host='HOSTNAME_DEFINED_IN_CAFILE_ABOVE`?

**Comment by fh-afk** [comment]
host=\'HOSTNAME_DEFINED_IN_CAFILE_ABOVE\' would not confuse me, sounds good.

**Comment by trel** [comment]
sold.  thanks.
