### ISSUE TITLE
Support for permissions management (ACL)

### ISSUE THREAD

**Issue by adetorcy** [irods/python-irodsclient#26]
- [x] Add permissions property to iRODSDataObject and iRODSCollection, much like metadata

**Comment by adetorcy** [comment]
Add permissions property to iRODSDataObject and iRODSCollection, much like metadata

**Comment by kript** [comment]
👍

**Comment by pdonorio** [comment]
Can we help on this issue?

**Comment by adetorcy** [comment]
Sure. Is there something missing in particular that you have in mind?

**Comment by pdonorio** [comment]
I don't know, I'd just like to mess around with ACL like with the icommands. Do you have a list of ACL operations and what is already implemented? I may help on closing what is not in the list.

**Comment by adetorcy** [comment]
You can get and set ACLs on data objects and collections. Example [here](../blob/master/irods/test/access_test.py).

**Comment by pdonorio** [comment]
Uhm, that is great! 
So what is missing here? Why is the issue still opened?
