### ISSUE TITLE
How to iGet a collection using the python client?

### ISSUE THREAD

**Issue by disastrous-charly** [irods/python-irodsclient#265]
Hi, bit of a noob question here,

I'm new using irods and I was wondering how I could retrieve a collection in my local folder store on an irods using this python client. 

If I use `session.collections.get` it doesn't fetch the data on local drive. 

How can I achieve that?

**Comment by trel** [comment]
This may do something like you're expecting - but I have not tried it myself.

https://github.com/Computational-Plant-Science/irods_python_client

**Comment by trel** [comment]
This is their implementation of walking the children and getting any data objects, recursively:

https://github.com/Computational-Plant-Science/irods_python_client/blob/0d9724810f58cde003f17aa84c3b2a10d68f0391/pyicmd/functional.py#L21-L33
```python
    if session.data_objects.exists(irods_path):
        to_file_path = os.path.join(local_path, os.path.basename(irods_path))
        session.data_objects.get(irods_path, file=to_file_path)
    elif session.collections.exists(irods_path):
        if recursive:
            coll = session.collections.get(irods_path)
            local_path = os.path.join(local_path, os.path.basename(irods_path))
            os.mkdir(local_path)


            for file_object in coll.data_objects:
                get(session, os.path.join(irods_path, file_object.path), local_path, True)
            for collection in coll.subcollections:
                get(session, collection.path, local_path, True)```

**Comment by disastrous-charly** [comment]
That's very helpful! Thanks a lot for your quick answer.
