### ISSUE TITLE
PRC gives different serialized parameters than iCommand when a PEP is triggered

### ISSUE THREAD

**Issue by mstfdkmn** [irods/python-irodsclient#266]
Hello,

We used the following PEP for a rule but later we figure it out that our rule is blocking metadata operation executed by PRC.

```
pep_api_mod_avu_metadata_pre(*INSTANCE_NAME, *COMM, *MODAVUMETAINP) {

   writeLine("serverLog" , "avu metadata: instance *INSTANCE_NAME, comm *COMM, object *MODAVUMETAINP");
}
```

The issue here is that "modAVUMetadataInp" argument gives arg5 as the last key by the PRC whereas iCommand generates keys up to arg9. Please see the differences below.

Add metadata by iCommand:

`Apr 29 12:27:16 pid:2773893 NOTICE: writeLine: inString = avu metadata: instance api_instance, comm auth_scheme=native++++client_addr=10.0.2.100++++proxy_auth_info_auth_flag=5++++proxy_auth_info_auth_scheme=++++proxy_auth_info_auth_str=++++proxy_auth_info_flag=0++++proxy_auth_info_host=++++proxy_auth_info_ppid=0++++proxy_rods_zone=tempZone++++proxy_sys_uid=0++++proxy_user_name=rods++++proxy_user_other_info_user_comments=++++proxy_user_other_info_user_create=++++proxy_user_other_info_user_info=++++proxy_user_other_info_user_modify=++++proxy_user_type=++++user_auth_info_auth_flag=5++++user_auth_info_auth_scheme=++++user_auth_info_auth_str=++++user_auth_info_flag=0++++user_auth_info_host=++++user_auth_info_ppid=0++++user_rods_zone=tempZone++++user_sys_uid=0++++user_user_name=rods++++user_user_other_info_user_comments=++++user_user_other_info_user_create=++++user_user_other_info_user_info=++++user_user_other_info_user_modify=++++user_user_type=, object arg0=rm++++arg1=-d++++arg2=/tempZone/home/rods/exim/daily/test.txt++++arg3=key1++++arg4=value1++++arg5=units1++++arg6=++++arg7=++++arg8=++++arg9=`

Add metadata by PRC

`Apr 29 12:27:35 pid:2773955 NOTICE: writeLine: inString = avu metadata: instance api_instance, comm auth_scheme=native++++client_addr=10.0.2.100++++proxy_auth_info_auth_flag=5++++proxy_auth_info_auth_scheme=++++proxy_auth_info_auth_str=++++proxy_auth_info_flag=0++++proxy_auth_info_host=++++proxy_auth_info_ppid=0++++proxy_rods_zone=tempZone++++proxy_sys_uid=0++++proxy_user_name=rods++++proxy_user_other_info_user_comments=++++proxy_user_other_info_user_create=++++proxy_user_other_info_user_info=++++proxy_user_other_info_user_modify=++++proxy_user_type=++++user_auth_info_auth_flag=5++++user_auth_info_auth_scheme=++++user_auth_info_auth_str=++++user_auth_info_flag=0++++user_auth_info_host=++++user_auth_info_ppid=0++++user_rods_zone=tempZone++++user_sys_uid=0++++user_user_name=rods++++user_user_other_info_user_comments=++++user_user_other_info_user_create=++++user_user_other_info_user_info=++++user_user_other_info_user_modify=++++user_user_type=, object arg0=add++++arg1=-d++++arg2=/tempZone/home/rods/exim/daily/test.txt++++arg3=key1++++arg4=value1++++arg5=units1`

We selected this PEP to be used since it is triggered by most of metadata operations.

Do you think this difference is normal? If so, we will need to change our rule structure.

**Comment by trel** [comment]
Your iCommand appears to be an `add`, while the PRC call appears to be an `rm`.

That could be the difference...

**Comment by mstfdkmn** [comment]
Sorry, right I pasted here different metadata operations result. But as you can see below the same operation `add` gives the different results depending on the client that we use.

iCommand result:
`Apr 29 21:44:29 pid:2808122 NOTICE: writeLine: inString = avu metadata: instance api_instance, comm auth_scheme=native++++client_addr=10.0.2.100++++proxy_auth_info_auth_flag=5++++proxy_auth_info_auth_scheme=++++proxy_auth_info_auth_str=++++proxy_auth_info_flag=0++++proxy_auth_info_host=++++proxy_auth_info_ppid=0++++proxy_rods_zone=tempZone++++proxy_sys_uid=0++++proxy_user_name=rods++++proxy_user_other_info_user_comments=++++proxy_user_other_info_user_create=++++proxy_user_other_info_user_info=++++proxy_user_other_info_user_modify=++++proxy_user_type=++++user_auth_info_auth_flag=5++++user_auth_info_auth_scheme=++++user_auth_info_auth_str=++++user_auth_info_flag=0++++user_auth_info_host=++++user_auth_info_ppid=0++++user_rods_zone=tempZone++++user_sys_uid=0++++user_user_name=rods++++user_user_other_info_user_comments=++++user_user_other_info_user_create=++++user_user_other_info_user_info=++++user_user_other_info_user_modify=++++user_user_type=, object arg0=add++++arg1=-d++++arg2=/tempZone/home/rods/exim/daily/test.txt++++arg3=atr++++arg4=val++++arg5=++++arg6=++++arg7=++++arg8=++++arg9=`

PRC result:
`Apr 29 21:44:42 pid:2808183 NOTICE: writeLine: inString = avu metadata: instance api_instance, comm auth_scheme=native++++client_addr=10.0.2.100++++proxy_auth_info_auth_flag=5++++proxy_auth_info_auth_scheme=++++proxy_auth_info_auth_str=++++proxy_auth_info_flag=0++++proxy_auth_info_host=++++proxy_auth_info_ppid=0++++proxy_rods_zone=tempZone++++proxy_sys_uid=0++++proxy_user_name=rods++++proxy_user_other_info_user_comments=++++proxy_user_other_info_user_create=++++proxy_user_other_info_user_info=++++proxy_user_other_info_user_modify=++++proxy_user_type=++++user_auth_info_auth_flag=5++++user_auth_info_auth_scheme=++++user_auth_info_auth_str=++++user_auth_info_flag=0++++user_auth_info_host=++++user_auth_info_ppid=0++++user_rods_zone=tempZone++++user_sys_uid=0++++user_user_name=rods++++user_user_other_info_user_comments=++++user_user_other_info_user_create=++++user_user_other_info_user_info=++++user_user_other_info_user_modify=++++user_user_type=, object arg0=add++++arg1=-d++++arg2=/tempZone/home/rods/exim/daily/test.txt++++arg3=key1++++arg4=value1++++arg5=units1`

**Comment by trel** [comment]
I don't think it's a problem.   The different `imeta` operations use a different number of the available arguments in the data structure (`modAVUMetadataInp`), depending on what they're needing to do.  

`add` uses up to `arg5`, if the units are declared (only `arg4` without)
`rm` uses up to `arg5`, if the units are declared (only `arg4` without)

`modAVUMetadata` uses up to `arg8`.

https://github.com/irods/irods_client_icommands/blob/1737dcef861bf81437971edd4525845076daa3f1/src/imeta.cpp#L1125-L1155

```cpp
modAVUMetadata( char *arg0, char *arg1, char *arg2, char *arg3,
                char *arg4, char *arg5, char *arg6, char *arg7, char *arg8 ) {
    modAVUMetadataInp_t modAVUMetadataInp;
    char fullName[MAX_NAME_LEN];


    if ( strcmp( arg1, "-R" ) == 0 || strcmp( arg1, "-r" ) == 0 ||
            strcmp( arg1, "-u" ) == 0 ) {
        snprintf( fullName, sizeof( fullName ), "%s", arg2 );
    }
    else if ( strlen( arg2 ) > 0 ) {
        if ( *arg2 == '/' ) {
            snprintf( fullName, sizeof( fullName ), "%s", arg2 );
        }
        else {
            snprintf( fullName, sizeof( fullName ), "%s/%s", cwd, arg2 );
        }
    }
    else {
        snprintf( fullName, sizeof( fullName ), "%s", cwd );
    }


    modAVUMetadataInp.arg0 = arg0;
    modAVUMetadataInp.arg1 = arg1;
    modAVUMetadataInp.arg2 = fullName;
    modAVUMetadataInp.arg3 = arg3;
    modAVUMetadataInp.arg4 = arg4;
    modAVUMetadataInp.arg5 = arg5;
    modAVUMetadataInp.arg6 = arg6;
    modAVUMetadataInp.arg7 = arg7;
    modAVUMetadataInp.arg8 = arg8;
    modAVUMetadataInp.arg9 = "";
```

No operation appears to use `arg9`, it's just part of the data structure.

How is this affecting your policy?  I think you have all the information you would need to make decisions.

Can you explain what you mean here?
> our rule is blocking metadata operation executed by PRC

**Comment by mstfdkmn** [comment]
We would like to write some rules that should lock some certain actions in iRODS based on given metadata flags. These are still in the dev phase and we want some part of those will be working with the storage tiering at the end. A snipped is given below.

```
pep_api_mod_avu_metadata_pre(*INSTANCE_NAME, *COMM, *MODAVUMETAINP) {
  writeLine("serverLog" , "avu metadata: instance *INSTANCE_NAME, comm *COMM, object *MODAVUMETAINP");

  if (*MODAVUMETAINP.arg3 == "__locked" || *MODAVUMETAINP.arg6 == "__locked") {
    if (lockingIsAdmin(*COMM)) {
      succeed;
    }

    cut;
    msiOprDisallowed;
  }
}
```
As seen, it is checking whether the metadata attribute name is "something" both for add and mod. When we modify metadata, it will look at the modAVUMetadataInp.arg3 = arg6 like it does for the modAVUMetadataInp.arg3 = arg3 in adding. So, I thought the issue here is that via iCommand the PEP provides args up to the arg9 whereas it doesn't do the same via PRC.

**Comment by trel** [comment]
Consider making your logic more dependent on the operation itself - so you know which arg you're interested in.

Something like...
```
  if ( (*MODAVUMETAINP.arg0 == "add" && *MODAVUMETAINP.arg3 == "__locked") ||
       (*MODAVUMETAINP.arg0 == "mod" && *MODAVUMETAINP.arg6 == "__locked")) {
```

**Comment by mstfdkmn** [comment]
Hi Terrell,

I am closing this because we indeed see no issue after we change codes in our rule as you pointed. Thanks for that.

**Comment by trel** [comment]
Excellent.
