### ISSUE TITLE
Long PAM password/token string causes PACKSTRUCT error

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#279]
We currently use authPlugin* structures for handling PAM authentication from the Python iRODS Client(PRC), and this results in the context_ part of the structure being greater than MAX_NAME_LEN characters if the password/token submitted to the API (1201 = AUTH_PLUG_REQ_AN) is too long.  

This is being seen in Utrecht University's Yoda project, as they are porting its code from a PHP iRODS  client (which sends OpenID tokens through a pamAuth* iRODS API (725) and accordingly uses its pack structures, which are more permissive of long strings) to use the PRC.

**Comment by trel** [comment]
We've got the code to fix this - PR and merge coming.
