### ISSUE TITLE
Improve data object I/O performance

### ISSUE THREAD

**Issue by adetorcy** [irods/python-irodsclient#28]
[From iRODS-Chat](https://groups.google.com/forum/#!topic/irod-chat/fHtHxbcbIVk/discussion)

Hi,

I tried the python-irods-client.
Reading a simple 12 MB file like this, may take up to 200 seconds!

``` python
obj = sess.data_objects.get(mseedFile)
with obj.open('r+') as f:
        for line in f:
                print line
```

``` bash
time ./rsc.py > output
```

I patched the `irods/data_object.py` file, to specify a big buffer:

``` diff
1c61
<         return BufferedRandom(iRODSDataObjectFileRaw(conn, desc))

---
>         return BufferedRandom(iRODSDataObjectFileRaw(conn, desc),buffer_size=1000000)
```

Then, it took "only" 7 seconds to read the file. But it's still 10 times more than a simple iget.

Furthermore, if I use a library like "obspy" (`obspy.core.read(f)`), we are back to 200 seconds, even with this buffering trick.

What read/write performance are we suppose to expect using the irods api?

Best regards

**Comment by bzizou** [comment]
Test file, readable by obspy:
wget -O - http://ciment.ujf-grenoble.fr/misc/ZZ.YZEH.00.BAE.D.2008.001 > ZZ.YZEH.00.BAE.D.2008.001

**Comment by orzel** [comment]
We are currently testing, and when sending a file (everything else being equal), we got
* 132 Mb/s using the python-irodsclient
* 830 MB/s using the 'iput' command, without any specific option. The physical link is 1Gb/s, and it seems fairly optimal. 

One thing to note, is that the bandwidth is very steady using the python binding, while it's far more variable with iput.

We have the 'feeling' that somehow there's something blocking the bandwidth in the python code.

We are aware of optimisation options in iput (threading, bulk upload, datagram protocol..), and that the python code doesn't provide yet those optimisation. But we don't know if this really is the reason for such bad performance.

**Comment by alexlemann** [comment]
I have written a command line interface to some of the python-irodsclient features which may be useful for benchmark comparison. Check it out over at [python-irods-cli](https://github.com/alexlemann/python-irods-cli).

Of note, I have noticed that using the standard icommands, `iget -N 0` is slower than higher `-N` values, implying that single threads are not able to saturate even relatively modest links.

It would be possible to test this more thoroughly using [python-irods-cli](https://github.com/alexlemann/python-irods-cli) given that it uses **gevent to provide parallel client downloads**.

**Comment by trel** [comment]
@alexlemann and @orzel would you like to profile the master branch again?

#114 has improved the get() performance by ~30%

if there is nothing else actionable on this issue, we can close it.

**Comment by trel** [comment]
Closing - if specific performance issues need to be addressed, please open a new issue.  Thanks.
