### ISSUE TITLE
iRODSDataObject method **options docstrings

### ISSUE THREAD

**Issue by kjsanger** [irods/python-irodsclient#282]
I'm workinng out what values are available or legal for use for some methods of iRODSDataObject. E.g. the `checksum` method requires some options that (I expect) allow lookup of the checksum without auto-vivifying (if it hasn't been created) or to force update a checksum that already exists. The code in the tests doesn't offer examples in this case.

https://github.com/irods/python-irodsclient/blob/232a2d73d496f77d11060495fbb4fac7ab099f56/irods/data_object.py#L92

It would be helpful to have some informative docstrings where there are splatted options.

**Comment by d-w-moore** [comment]
@kjames In this case does auto-vivifying mean recomputing an already existing checksum? Wondering what use case you had in mind.  I could be wrong, but I don't currently know of a keyword or option that lets you compute an object checksum without storing it in the catalog.

**Comment by kjsanger** [comment]
In the case of a data object like this:

```
$ ils -L
/testZone/home/irods:
  irods             0 replResc;unixfs2         3360 2021-08-31.21:25 & README
        generic    /var/lib/irods/iRODS/VaultRy/home/irods/README
  irods             1 replResc;unixfs1         3360 2021-08-31.21:25 & README
        generic    /var/lib/irods/iRODS/VaultRx/home/irods/README
```

By "auto-vivifying" I mean that however I've tried to use `iRODSDataObject.checksum to simply read the checksum and report that it's empty (or `None`, maybe?), it always calculates the checksum for one of the replicas and returns that (but just one replica. not both).

In `baton` I can use the various keywords available to `rcDataObjChksum` to achieve the available options of
- reporting empty without creating
- creating if empty and reporting 
- forcibly creating and reporting
the checksum.

https://github.com/wtsi-npg/baton/blob/devel/src/read.c#L536-L552

How do I achieve these with `iRODSDataObject.checksum`? Thanks.

**Comment by kjsanger** [comment]
> @Kjames In this case does ...

BTW, I think you @'ed someone else by accident there ... that isn't me.

**Comment by d-w-moore** [comment]
@kjsanger I see that, whoops - sorry.
I just now made a tentative fix and it looks like passing the NO_COMPUTE and VERIFY_CHKSUM keywords achieves what  you wanted.  More mods are necessary than just the addition of the NO_COMPUTE_KW = 'no_compute' definition, because the server response becomes None (unparseable) which causes an exception, when using that keyword combination.

Will be submitting the PR for this soon.
