### ISSUE TITLE
Put operation ignores kw.FORCE_FLAG_KW flag

### ISSUE THREAD

**Issue by kjsanger** [irods/python-irodsclient#286]
iRODS server version: 4.2.10
python-irodsclient version: 1.0

What did you do?:

Called iRODSSession.data_objects.put to upload a file passing:

```
    options = {kw.FORCE_FLAG_KW: ""}

    obj = sess.data_objects.put(str(local), str(remote),
                                return_data_object=True, **options)
```

**What happened:**

The call raises an error (see https://github.com/irods/python-irodsclient/issues/285) when the data object already exists.

**What did you expect:**

The data object to be overwritten.

**Comment by d-w-moore** [comment]
@kjsanger I assume this is a small file , not going through the parallel put API ?

**Comment by kjsanger** [comment]
No, it's ~ 1 GiB. The stacktrace is as in the linked issue.

**Comment by d-w-moore** [comment]
session.data_objects.put( ) has historically ignored  FORCE_FLAG_KW. If that's undesirable, we should definitely discuss.
Otherwise, this issue seems a repeat of #285, so we'll close it for the present.

**Comment by kjsanger** [comment]
So that I'm clear on the decision - `put` ignores the flag by design?

We have cases in production where data need updating and the final data object name must not change. how should be achieve that with the Python API.

Thanks.

**Comment by trel** [comment]
> So that I'm clear on the decision - put ignores the flag by design?

Yes.

---

As I understand it...

A PRC put is not an iRODS put... but rather an iRODS open/write/close.   And the force flag is not honored on the iRODS open/write/close series of operations.

So, yes, #285 is the reason your `sess.data_objects.put()` is failing.

Your use case for "data need updating and the final data object name must not change" should work fine for production... once we get #285 fixed up.
