### ISSUE TITLE
client API endpoints  don't convey back an RError stack

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#287]
It would be convenient if the PRC library could facilitate the conveyance (to user|application), or at least logging, of messages coming back from the iRODS server as part of the response to an API call ( say a checksum-with-verify, or a rule exec )

**Comment by d-w-moore** [comment]
This has been done for chksum and can easily be done for rule execution, too.  If anything resurfaces  anew within that effort, will re-open this issue.

**Comment by trel** [comment]
let's make a new issue if we need rule-execution-specific stuff - can always link to this issue in that description.
