### ISSUE TITLE
Get of data object fails when data object is accessible through ticket and by anonymous user

### ISSUE THREAD

**Issue by chStaiger** [irods/python-irodsclient#294]
I am trying to download data objects by ticket and with the anonymous user. If I set the local_path variable, the data is indeed downloaded but the data_object_manager.get still fails due to the iCAT query which is disabled for the anonymous user (https://github.com/irods/python-irodsclient/blob/6acba9a5df99f3f4f9dde6323bc40a9dcbea9696/irods/manager/data_object_manager.py#L93)

Steps to reproduce:
I created a ticket to a collection that contains a data object.
```py
session = iRODSSession(user='anonymous',
                                    password='',
                                    zone=zone,
                                    port=1247,
                                    host=host)

ticket = Ticket(self.session, self.token)
ticket.supply()
coll = session.collections.get(self.path)
obj = coll.data_objects[0]

options = {kw.TICKET_KW: token}
session.data_objects.get(obj.path, local_path="testfile", **options)
```

The error that is thrown:
```
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/irods/connection.py in recv(self)
    102             try:
--> 103                 err_msg = iRODSMessage(msg=msg.error).get_main_message(Error).RErrMsg_PI[0].msg
    104             except TypeError:

/usr/local/lib/python3.6/dist-packages/irods/message/__init__.py in get_main_message(self, cls)
    191         logger.debug(self.msg)
--> 192         msg.unpack(ET.fromstring(self.msg))
    193         return msg

/usr/lib/python3.6/xml/etree/ElementTree.py in XML(text, parser)
   1313         parser = XMLParser(target=TreeBuilder())
-> 1314     parser.feed(text)
   1315     return parser.close()

TypeError: a bytes-like object is required, not 'NoneType'

During handling of the above exception, another exception occurred:

CAT_SQL_ERR                               Traceback (most recent call last)
<ipython-input-27-c25c07a21857> in <module>()
----> 1 ic.session.data_objects.get(coll.path+'/loading_circle.gif', local_path="/home/christine/test.gif", **options)

/usr/local/lib/python3.6/dist-packages/irods/manager/data_object_manager.py in get(self, path, local_path, num_threads, **options)
     96             .add_keyword(kw.ZONE_KW, path.split('/')[1])
     97 
---> 98         results = query.all() # get up to max_rows replicas
     99         if len(results) <= 0:
    100             raise ex.DataObjectDoesNotExist()

/usr/local/lib/python3.6/dist-packages/irods/query.py in all(self)
    187 
    188     def all(self):
--> 189         result_set = self.execute()
    190         if result_set.continue_index > 0:
    191             self.continue_index(result_set.continue_index).close()

/usr/local/lib/python3.6/dist-packages/irods/query.py in execute(self)
    172             conn.send(message)
    173             try:
--> 174                 result_message = conn.recv()
    175                 results = result_message.get_main_message(GenQueryResponse)
    176                 result_set = ResultSet(results)

/usr/local/lib/python3.6/dist-packages/irods/connection.py in recv(self)
    103                 err_msg = iRODSMessage(msg=msg.error).get_main_message(Error).RErrMsg_PI[0].msg
    104             except TypeError:
--> 105                 raise get_exception_by_code(msg.int_info)
    106             raise get_exception_by_code(msg.int_info, err_msg)
    107         return msg

CAT_SQL_ERR: None
```

The file is downloaded correctly, checksums are also ok.

**Comment by d-w-moore** [comment]
It seems like something may not be right within iRODS core code with regard to tickets and GenQuery.
I tried:
  1. creating `/tempZone/home/rods/dir`
  2. granting a read ticket to the **anonymous** user using `iticket`
  3. query (as **anonymous**) for `/tempZone/home/rods/dir` using `iquest "select COLL_NAME"`. It wasn't listed....

@korydraughn @alanking @trel - I don't see a way to apply the 'TICKET_KW' in an iquest command, so maybe that's the problem if the keyword were applied, core code would modify the genquery properly with permissions for anonymous ? Is writing a custom C/C++ client the only way to test this ?

**Comment by d-w-moore** [comment]
@chStaiger I have experimented with general queries in PRC/ticket scenarios and learned a bit, but do not yet know if I can repair the data_objects.get( ) function.  I do have a sort of workaround that might be satisfactory for the time being:

Having created a test collection with some subobjects and a subfolder, if I grant a read ticket for it:
```
irods:~$ iticket create read  /tempZone/home/rods/test
ticket:W37sTxsApwj9jU5
irods:~$ iticket mod W37sTxsApwj9jU5 add user anonymous
```
and use a script such as this one:
```
#get_objects.py
from irods.session import iRODSSession
from irods.ticket import Ticket

ses = iRODSSession(host='localhost',port=1247,user='anonymous',password='',zone='tempZone')

import sys
if len(sys.argv) > 1:
    t = Ticket(ses,sys.argv[1])
    t.supply()

c = ses.collections.get('/tempZone/home/rods/test')

for (folder, subfolder_list, data_obj_list) in c.walk():
    for d in data_obj_list:
        data_obj_path = folder.path + '/' + d.name
        print (data_obj_path, end = '\t\t')
        print ('contents => ', repr( d.open('r').read() ))
```
I can then read all data objects and see all collections subordinate to the ticketed collection.
```
anon-user:~$ python get_objects.py  W37sTxsApwj9jU5
/tempZone/home/rods/test/data1		contents =>  b'ataalkfjas;ldja;sldkfja;sldfkjasda;sdlkfja;lsfjaskldjf\n'
/tempZone/home/rods/test/subdir/data2		contents =>  b'ataalkfjas;ldja;sldkfja;sldfkjasda;sdlkfja;lsfjaskldjf\n'

```

So, even though session.data_objects.get(..) "as-is" is unusable for ticket access,
you could
   -  simulate get( )  by writing the output of read( ) to a local file, and 
   - in the c.walk( ) loop, compare the generated data object path(s) to the desired download path(s) to find the target object
Having done so, you would then have re-implemented the data_object get( ) to work for your specific purpose.

**Comment by chStaiger** [comment]
@d-w-moore  Many thanks, that works and for the download of data objects I created a little wrapper which ignores the Exception thrown by the query. So for tickets pointing to collections we have a workflow which is for our use case at the moment sufficient.

**Comment by d-w-moore** [comment]
@chStaiger - the necessary changes for tickets allowing anonymous user access would now seem to be merged into the tip of master.  Will close this issue now, but please feel free to re-open if you find problems !
