### ISSUE TITLE
`walk()` only returns 250 `iRODSDataObject`s per collection

### ISSUE THREAD

**Issue by tamasgal** [irods/python-irodsclient#30]
We have a few hundred of files per collection and when I try to access the data objects within subcollections of a collection, I only get maximum 250 objects returned:

    sess = iRODSSession(...)
    coll = sess.collections.get('/a/path')
    for collection, subcollections, data_objects in coll.walk():
        print len(data_objects)

prints

    0
    250
    250
    250

although there are much more files in each subcollection.

**Comment by adetorcy** [comment]
Thanks for reporting this

**Comment by tamasgal** [comment]
Many thanks for the quick fix! :+1:
