### ISSUE TITLE
feature request: add rule execution

### ISSUE THREAD

**Issue by petrrr** [irods/python-irodsclient#31]
We are wondering if there is the possibility to execute a rule by the irods python client? Was this already implemented? I there some documentation on this?

Where would we have to look at if we would like to add this to the packages?

TNX!

**Comment by adetorcy** [comment]
Executing rules has not been implemented and you're certainly welcome to take a crack at it.

I would suggest looking at how queries are implemented and doing something similar: no manager, a rule.py module that defines a Rule class with an execute() method.

From a quick look at it you will need to implement an equivalent to execMyRuleInp_t in [message](../blob/master/irods/message/__init__.py):

class RuleExecutionRequest(Message):
    _name = 'ExecMyRuleInp_PI'
    ...

You might also have to define classes for rodsHostAddr_t and msParamArray_t...

Let me know if you have any more questions. Looking forward to your pull request.

**Comment by petrrr** [comment]
Thanks for the info. 
We will try to get at this (and hopefully come up with a first PR) as soon as we some other stuff done. Will edit the title.

**Comment by adetorcy** [comment]
I added basic support for rule execution. See examples [here](https://github.com/irods/python-irodsclient/blob/master/irods/test/rule_test.py). Feel free to try it and provide feedback.
