### ISSUE TITLE
Rule execution should allow the 'null' input parameter for the rule_file (.r)

### ISSUE THREAD

**Issue by mstfdkmn** [irods/python-irodsclient#314]
Hello,

Once I would like to call any rule (in rule engines) by a rule file (.r) which doesn't need INPUT parameter via PRC,  I am hitting 'ValueError'.

In other words, if the rule file's (.r) input parameter is 'null', you then get "ValueError: need more than 1 value to unpack" error. I think this is because of L58, 59.

However, if I provide a dummy parameter for the input of .r file, then I can execute the rule but throws a parser error - -1201000.

**Example:**

PRC execution:
```
import os
import ssl
from irods.session import iRODSSession
from irods.rule import Rule
try:
    env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
    env_file = os.path.expanduser('~/.irods/irods_environment.json')
ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)
ssl_settings = {'ssl_context': ssl_context}

with iRODSSession(irods_env_file=env_file, **ssl_settings) as session:
    rule_file_path = "/path/to/test.r"
    myrule = Rule(session, rule_file = rule_file_path)
    myrule.execute()
```
My test file:

```
def main(rule_args, callback, rei):
    callback.writeLine('stdout', 'Execute command to print out hello')
    callback.print_hello()
INPUT null
OUTPUT ruleExecOut
# It does expect a value here instead of "null".
```
Logs:

```
Nov 19 16:50:09 pid:154259 remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:1c:5ede ERROR: Rule Engine Plugin returned [-130000].
Nov 19 16:50:09 pid:154259 DEBUG: parseRuleSet: error parsing rule.
line 0, col 8
def main(rule_args, callback, rei):
        ^

Nov 19 16:50:09 pid:154259 NOTICE: execMyRule @external
def main(rule_args, callback, rei):

    callback.writeLine('stdout', 'Execute command to print out hello')
    callback.print_hello()


 Failed with status -1201000
Nov 19 16:50:09 pid:154259 remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:1c:5ede ERROR: [addMsParamToArray] - type is null for [ruleExecOut]
Hello
```

Could you tell me if I am doing something wrong here. Thanks.

**Comment by d-w-moore** [comment]
This is a bug I encountered too, on the way to getting other rule execution enhancements in.  I've now singled it out as its own commit... see the one labeled "[314] allow null parameter on INPUT line of a rule file" in this [development branch](https://github.com/d-w-moore/python-irodsclient/commits/288.Inst_Name)

**Comment by mstfdkmn** [comment]
Hello,

It seems I encountered another type of this null input issue of the rule call. That is:

Specifying the rule engine instance in the rule call is **not** throwing `-1201000`.
`Rule(session, instance_name = 'irods_rule_engine_plugin-python-instance', rule_file = 'test.r').execute()`

But the call below seems hitting the **same error**  - no referral to the rule engine instance, btw:
`Rule(session, rule_file = 'test.r').execute()`

Logs:
`NOTICE: execMyRule @external#012def main(rule_args, callback, rei):#012    """#012    A test rule in python#012    """#012#012    callback.print_hello()#012    callback.writeLine('serverLog', 'IDENTIFIER: Test delay rule for server')#012    callback.testZone()#012#012 Failed with status -1201000`

Could you test this?
And if using `instance_name `keyword argument here is always required, then may not be optional? - or we might expect to see another error?

PRC - 1.1.5
iRODS server - 4.2.10

**Comment by d-w-moore** [comment]
Oops.
