### ISSUE TITLE
Add clarification for python rule execution in Readme

### ISSUE THREAD

**Issue by mstfdkmn** [irods/python-irodsclient#338]
I think it might be nice to add a remark in README (https://github.com/irods/python-irodsclient#Rule%20Execution) about the fact that only `rodsadmin` users can execute python rules available in the core.py file. There is a reference here at the link below for `irule ` usage but I think this is also valid for the PRC. https://github.com/irods/irods_rule_engine_plugin_python#Admin%20rights%20required%20for%20irule%20with%20Python

Here is my test result:
test rule imported to the `core.py` in the rule engine/server:
```
import session_vars
def testZone(rule_args, callback, rei):
   callback.writeLine("serverLog", "Hello, the zone - {} - is being tested.".format(session_vars.get_map(rei)["client_user"]["irods_zone"]))
```

client script:
```
import ssl
from irods.session import iRODSSession
from irods.rule import Rule
from irods import exception

try:
    env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
    env_file = os.path.expanduser('~/.irods/irods_environment.json')

ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)
ssl_settings = {'ssl_context': ssl_context}
with iRODSSession(irods_env_file=env_file, **ssl_settings) as session:
    try:
        Rule(session, body = 'testZone', instance_name = 'irods_rule_engine_plugin-python-instance' ).execute()
    except exception.RuleEngineException:
        print('Rule execution failed!')
        exit(1)
    print('Rule execution succeeded!')
```
Result for the `non-rodsadmin` users:
```
 raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.SYS_NO_API_PRIV: None
```

**Comment by d-w-moore** [comment]
@mstfdkmn This is more an aspect of the iRODS core (irule has the same behavior), although I have no problems stating it in this README if that seems apt.

**Comment by mstfdkmn** [comment]
Thanks. For end users, seeing this in an example in README could be understood like a new feature. Hence I thought a remark about it might be useful once an example with the python rule is mentioned in Readme.
