### ISSUE TITLE
Fixed bug in cleanup of stale connections

### ISSUE THREAD

**Issue by kxk302** [irods/python-irodsclient#341]
When releasing a connection that was created 'connection_refresh_time' seconds ago, must clean up the connection before creating a new connection and assigning it to the same variable. Previous call to connection_release() with destroy flag set to true only attempted to remove an already popped connection from the idle set (acted as basically a no-op), and the connection destructor had an erroneous if-clause for the call to disconnect() method, which prevented connection from being cleaned up. This fixes both issues.

**Comment by d-w-moore** [comment]
Indeed my logic in the destructor seems to have been the reverse of what was needed! thanks for that check and fix @kxk302 !

**Comment by kxk302** [comment]
> Indeed my logic in the destructor seems to have been the reverse of what was needed! thanks for that check and fix @kxk302 !

No problem @d-w-moore!

**Comment by d-w-moore** [comment]
@kxk302 , can we close this and call it resolved?  If i recall correctly, this line is the fix: https://github.com/irods/python-irodsclient/blob/8f53d2e25eb1ddd134539f01e1537242f3193f2f/irods/connection.py#L294

**Comment by kxk302** [comment]
This is resolved/fixed.

**Comment by kxk302** [comment]
> @kxk302 , can we close this and call it resolved? If i recall correctly, this line is the fix:
> 
> https://github.com/irods/python-irodsclient/blob/8f53d2e25eb1ddd134539f01e1537242f3193f2f/irods/connection.py#L294

Done!

**Comment by alanking** [comment]
For posterity...

#368 fixed this...

And the PR can be found here: https://github.com/irods/python-irodsclient/pull/367
