### ISSUE TITLE
Update connection disconnect logic. 

### ISSUE THREAD

**Issue by kxk302** [irods/python-irodsclient#345]
This ticket is to address some minor issues in logic to disconnecting a connection in connection destructor and adds a unit test. 

Moved connection disconnect logic from connection destructor to disconnect() method. 
Updated connection disconnect logic (No need to disconnect connections where file descriptor is -1). 
Added a log message to connection destructor and wrote a test to check the message is logged after destructor is called.
Removed no-op call to release_connection() in pool.py's get_connection()

**Comment by trel** [comment]
@d-w-moore you can reopen if you've got a couple more test things to add.

**Comment by d-w-moore** [comment]
> @d-w-moore you can reopen if you've got a couple more test things to add.

Went ahead and made another pull request using "continuing" issue #274 instead.

**Comment by trel** [comment]
Let's use this one and [3], [274]'s been closed for a while.

**Comment by d-w-moore** [comment]
Ok sounds good

**Comment by d-w-moore** [comment]
Reopening to rectify testing status and compatibility with old versions of Python.

**Comment by alanking** [comment]
@d-w-moore: Please close if finished. Thanks!
