### ISSUE TITLE
Fix possible infinite loop in _recv_message_in_len()

### ISSUE THREAD

**Issue by kxk302** [irods/python-irodsclient#352]
The _recv_message_in_len() method, in irods/message/__init_.py, has a while loop (while size_left > 0). 'size_left is initialized to the input parameter 'size', which is the number of bytes we'd like to read. Inside the loop, sock.recv() is called and the length of the read buffer is deducted from 'size_left', eventually causing the while loop to terminate (when 'size' bytes are read, the loop terminates).

We had a situation where our irods server was not available, and the sock.recv() call within the while loop returned an empty buffer of length zero. The existing logic for terminating the while loop did not work, causing the loop to never terminate and halting our app. I've came up with a fix and will create a PR for it plus the fix for issue #345

**Comment by alanking** [comment]
If this has been resolved, please close the issue. Thanks!
