### ISSUE TITLE
fcntl not available on windows

### ISSUE THREAD

**Issue by jefscheepers** [irods/python-irodsclient#358]
Some context: At KU Leuven, we have a lot of users who use Windows, rather than Linux. 
For those who want to use the Python client, we have created a small code snippet which scrambles their password and logs them in (using irods.password_obfuscation). 

A user has recently indicated that he couldn't use the most recent version of the Python-iRODSclient on Windows.
The reason seems to be the use of the module fcntl, which is not available on windows and was introduced in https://github.com/irods/python-irodsclient/commit/8ccba34cacd59c0e4d3c4edb7fb3eeb51fdc1cf2. 

Are there any plans to change this so the client is again available for windows?
Or is there perhaps something I'm missing?

Thanks in advance, 
Best regards,

Jef

**Comment by d-w-moore** [comment]
@jefscheepers This is an easy fix, I think.  The `fcntl` is only for detecting the blocking/non-blocking behavior of a socket, but that is only for debug logging.  We can easily opt out on the fcntl call under Windows.

**Comment by jefscheepers** [comment]
That's great to hear, Daniel. Thank you!

**Comment by d-w-moore** [comment]
Potential fix here : https://github.com/d-w-moore/python-irodsclient/tree/358.m .
We'll include a definitive fix on next release of PRC, possibly corresponding with the upcoming 4.3.0 release of iRODS
