### ISSUE TITLE
Query object doesn't throw `CAT_NO_ROWS_FOUND` once required

### ISSUE THREAD

**Issue by mstfdkmn** [irods/python-irodsclient#360]
Hello, both PRC queries below dont print out anything for nonexistent collections. This seems not consistent with iCommands. Thanks.

general and criterion queries' results:
```
from irods.models import Collection
from irods.column import Criterion

with iRODSSession(irods_env_file=env_file, **ssl_settings) as session:
    result = session.query(Collection)
    result = result.filter( Collection.name == '/u0137480/home/user/noCol')
    for item in result:        
        print(item[Collection.name])

with iRODSSession(irods_env_file=env_file, **ssl_settings) as session:
    criterion_result = Criterion ('=', Collection.name , '/u0137480/home/user/noCol')
    r = session.query(Collection).filter(criterion_result)
    for i in r:
        print(i[Collection.name])
```

iquest result:
```
-bash-4.2$ iquest "SELECT COLL_NAME WHERE COLL_NAME = '/u0137480/home/rods/noCol'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

**Comment by trel** [comment]
Doesn't an empty `result` tell you that nothing was found?

You'd like to see an actual error raised?

**Comment by d-w-moore** [comment]
@mstfdkmn Did the PRC at one time behave differently?  Ie., is it exhibiting new behavior that  breaks old code?

**Comment by mstfdkmn** [comment]
Hello Daniel, I don't know...I just wanted to let you know what I encountered -especially bearing in mind the fact that mostly iCommands behaviors are referenced for consistency. Perhaps I could not manage to find a good way using PRC in the following use case (we are developing scripts that will be called by a git hook and will logs milestones into iRODS -for all interactions with iRODS we use PRC in this script except the mentioned part). So instead of using subprocess, I had wanted to implement the same logic by PRC.

If the behavior is normal, then please close this accepting it as a question. Sorry about!
```
cmd1 = '''iquest "SELECT COLL_NAME WHERE COLL_NAME = '{}'"'''.format(irods_path)
_, out = subprocess.getstatusoutput(cmd1)
if out.startswith('CAT_NO_ROWS_FOUND'):
    project_name = input('Please describe the project: ')
    with SimpleiRODSSession() as session:
        session.collections.create(irods_path)
        collection = session.collections.get(irods_path)
        collection.metadata.add('PROJECT', '{}'.format(project_name))}

```

**Comment by d-w-moore** [comment]
Ah, I see.  Yes, the PRC is less likely to output incidental (though possibly helpful) things to the console, unlike the icommand clients....  Are you attempting a substitution of a Python client script for an iquest command?  You could always test the length of the query by using 
   *  (a) list( results ) or
   *  (b) list( itertools.islice (results, 0, 1) ) 
in the Python, and printing CAT_NO_ROWS_FOUND  if the resulting list were zero-length.  (Caveat: the PRC query iterator would resume from that point with, respectively, either (a) all rows or (b) one row having been consumed)

**Comment by mstfdkmn** [comment]
Thanks, those were what I needed, I should not have focused on seeing the same result of iCommand:(

**Comment by trel** [comment]
Excellent - closing.
