### ISSUE TITLE
Allow access to ADMIN_KW in AVU operations

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#364]

**Comment by d-w-moore** [comment]
As of v1.1.3, MetadataRequest object needs to conform with a modified ModAVUMetadata API when connecting to servers >4.2.11. Specifically, this will allow us to use  ADMIN_KW, a capability has been added to the API for those future releases (see https://github.com/irods/irods/issues/6124)

**Comment by alanking** [comment]
Please close if completed. Thanks!
