### ISSUE TITLE
allow direct calls to set via object handles

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#365]
Currently, we can do, eg.:
```
d = session.data_objects.get( <data_obj_path> )
d.metadata['a'] = iRODSMeta ('a','v','u')  # equivalent to :
                                           # session.metadata.set(DataObject, s.path, iRODSMeta('a','v','u'))
d.metadata.add( 'a2','v2','u2') 
```
However, we cannot do:
```
d.metadata.set('a2','v2','u2') # this could be implemented similarly to "d.add(...)" and would effect the previously
                      # mentioned call to session.metadata.set 
```
For cases involving setting a single AVU, this simplified `set `syntax would be convenient and self-explanatory.

**Comment by trel** [comment]
this is just new support for a `d.set()` syntax?    seems good.

but is it ... too short?    can `.set()` be misinterpreted as anything else in the 'data object' namespace?    should it be `d.set_metadata()` and `d.add_metadata()`?    `.set` could be misinterpreted as ... timestamp?  permissions?  resource location?   comments?    

how long has `.add()` been supported in this way?   same questions about that...

**Comment by d-w-moore** [comment]
`.add()` has been there a long time.  I think `.set( )` is fine since this is only done in the context of the metadata manager, and it seems it would be hard to mistake the intention of:
```
   myDataObj.metadata.set('a','v','u')
   myDataObj.metadata.add('a','v2','u2')
```
in the namespaced context in which it's being called.  This doesn't necessarily keep us from making aliases like set_metadata => set and add_metadata => add, so I'm open to that, but obj.metadata.set_metadata(...) is more verbose.

**Comment by trel** [comment]
Oh, certainly - I reacted to your code above as *not* having that context... 

```
d = session.data_objects.get( <data_obj_path> )
d.add( 'a2','v2','u2') 
```

You're saying it would actually be...

```
d.metadata.add('a2','v2','u2')
```

and then of course...

```
d.metadata.set('a2','v2','u2')
```

That's certainly very clear - and should be supported.
