### ISSUE TITLE
efficient way to get size of a specified collection 

### ISSUE THREAD

**Issue by yr-wang-hit** [irods/python-irodsclient#373]
If there is an efficient way to get the size of all the data objects under specified collection(maybe recursive) like linux `du -s`
Thanks a lot.

**Comment by trel** [comment]
You can most easily issue a GenQuery for this information... something like...

```
...    results = session.query(Collection.name, DataObject.name, DataObject.size).filter( \
...        Criterion('like', Collection.name, '%myproject%'))
```

**Comment by d-w-moore** [comment]
@yr-wang-hit GenQuery is so useful at such things, it's actually called internally by routines within iRODS runtime (and clients) to do things like listing and walking collections.  In this case, there's even a higher abstraction for what you need to do:
```
total_size_in_bytes = 0
n_data_objs = 0
collection = session.collections.get('/myZone/home/myUser/home/testCollection')
for info in collection.walk( ):
    n_data_objs += len( info[2] )
    total_size_in_bytes += sum( d.size for d in info[2] )
```

**Comment by yr-wang-hit** [comment]
Exactly, Thanks moore and trel.
But the tricky situation is that the size calculated based on irods client seems not matched with the size summary based on linux 
` du -sb `(under the Vault directory.) .  maybe ` du -sb ` summary takes OS-related things(like filesystem block size) into account?

Thanks.

**Comment by d-w-moore** [comment]
du does tend to round up:
```
~$ mkdir dir
~$ du -sh dir
4.0K	dir
~$ echo "a" >dir/file
~$ du -sh dir
8.0K	dir
```

**Comment by yr-wang-hit** [comment]
That make sense.
Thx
