### ISSUE TITLE
irods.exception.SYS_NO_API_PRIV when groupadmin creates group

### ISSUE THREAD

**Issue by simstoica** [irods/python-irodsclient#374]
When connected to irods with a groupadmin user account, the following line
``` python
   self.group = self.admin_sess.user_groups.create(group_name)
```
throws    
```
raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.SYS_NO_API_PRIV: None
```

Same code works OK for rodsadmin users.

**Comment by korydraughn** [comment]
What version of iRODS and the PRC are you running?

**Comment by simstoica** [comment]
Irods 4.3.0
Python client 1.1.4

**Comment by korydraughn** [comment]
In iRODS 4.3.0, the "client_api_allowlist_policy" option in server_config.json defaults to "enforce".

I suspect that option is the reason you're getting that error. Try setting it to "disabled" and seeing what happens.

By setting it to "disabled", all APIs will have the same accessibility as in the 4.2 series.

We'll investigate this and report back here.

**Comment by simstoica** [comment]
I tried out your suggestion, but it doesn't change the outcome. The problem still persists.

**Comment by korydraughn** [comment]
Did your attempt include a reboot?

**Comment by simstoica** [comment]
> 



> Did your attempt include a reboot?

The iRODS server runs in a docker container (in case it makes any difference). I did a clean rebuild of the container.

**Comment by korydraughn** [comment]
We will look into this.

**Comment by trel** [comment]
`igroupadmin mkgroup newgroup` does exist and a groupadmin can create groups - so we must have enough distinction somewhere...

**Comment by korydraughn** [comment]
`igroupadmin` invokes `rcUserAdmin` which does not have this problem.
https://github.com/irods/irods_client_icommands/blob/ec6a635893020e560b104866ca168e72397fedd9/src/igroupadmin.cpp#L194-L199

The PRC invokes `rcGeneralAdmin` which is the reason why the operation fails.
https://github.com/irods/python-irodsclient/blob/6ae5b1f6642f579462c454a973efa8944c9f2000/irods/manager/user_manager.py#L190-L205
It should invoke the `rcUserAdmin` api instead.

**Comment by d-w-moore** [comment]
Ah good catch - sounds easy enough to change.

**Comment by korydraughn** [comment]
@d-w-moore Let's let @MartinFlores751 handle this one. This is a good opportunity for him to touch other projects outside of the core server.

**Comment by korydraughn** [comment]
@MartinFlores751 Please close if this has been resolved.

**Comment by MartinFlores751** [comment]
This issue is resolved, but unfortunately, I cannot close it. @alanking perhaps you could close this? @korydraughn couldn't close this issue either.

**Comment by trel** [comment]
Oh!  I remain relevant!
