### ISSUE TITLE
checksum when sending "data object" to iRODS

### ISSUE THREAD

**Issue by orzel** [irods/python-irodsclient#38]
Is there a way (using this python binding) to either
* provide a checksum when sending an object to irods ?
* once an object has been sent to irods, ask irods to compute (and store) a checksum ?

Using command line, there's an option to "iput" so that a checksum is computed at the origin, another one in irods, and they are compared. This enhance reliability of the transport inside irods from an external source.

It is possible the other way around, when getting an object. If a checksum is already computed/stored by irods, it is provided as ".checksum" on the python object, and we do already use this for checking the file integrity once received. What we are aiming here is to get the same level of reliability in the other direction.

**Comment by adetorcy** [comment]
Currently PRC allows you to create/write/close objects, so what you could to is add a rule like
`acPostProcForPut { msiDataObjChksum ($objPath, 'forceChksum=', *out )}`
or
`acPostProcForCreate { msiDataObjChksum ($objPath, 'forceChksum=', *out )}`

Note that you might have to set oprType to 1 (`CREATE_TYPE`) in https://github.com/irods/python-irodsclient/blob/master/irods/manager/data_object_manager.py#L42

I will add a test for that.

**Comment by orzel** [comment]
Not sure to understand it all, but what you say is that 
* you confirm it's not possible from within the python client ("PRC")
* we should change the configuration on the irods side to automatically create a checksum when an object is created

That would fit our use case I think, we always want a checksum anyway.

**Comment by adetorcy** [comment]
I tested this against an iRODS 4.1.8 server as well:
```
>>> path = '/tempZone/home/rods/foo'
>>> obj = sess.data_objects.create(path)
>>> with obj.open('w') as obj_desc:
...     obj_desc.write('blah')
... 
>>> obj = sess.data_objects.get(path)
>>> 
>>> print obj.checksum
sha2:i33xQ9kccW7PpfwXMAIva0IbBc7e6P1SsfxlqWAwrVI=
>>> 
```
Please note that the `acPostProcForPut` rule is triggered when the object is closed, hence the need to refresh the object to get its checksum (`obj = sess.data_objects.get(path)`)

**Comment by orzel** [comment]
Ok, thanks. We will try this.

**Comment by orzel** [comment]
This works perfectly, thanks again.

**Comment by muccix** [comment]
Sorry for reopening this issue: it seems to me that with iRODS 4.2 `sess.data_objects.create(path)` does not trigger the acPostProcForPut rule anymore.

**Comment by adetorcy** [comment]
One of the unit tests exercises `acPostProcForPut`. See: https://github.com/irods/python-irodsclient/blob/master/irods/test/data_obj_test.py#L223

You might want to try setting the OPR_TYPE to 1 when opening objects.
e.g:
```python
options = {kw.OPR_TYPE_KW: 1}   # PUT_OPR
with session.data_objects.open(path, 'w', options) as o: # created if not exists
    o.write(...)
obj = sess.data_objects.get(path)  # if you need the object's properties
```
If the problem persists please post a code sample.

**Comment by muccix** [comment]
It turned out to be a misconfiguration in the iRODS core.re

Thanks a lot for your help
