### ISSUE TITLE
add status property to resource class

### ISSUE THREAD

**Issue by trel** [irods/python-irodsclient#384]
this would allow client applications to make decisions based on the status of a resource

**Comment by d-w-moore** [comment]
Ah yes. even a status of "DOWN" (all caps) is seen as "UP".. hrmh : /

**Comment by trel** [comment]
I think the PRC itself should just simply reflect what's in the catalog (like the current PR does) - no interpretation - just the string.  Anything more seems like magic and would appear to invite drift and confusion.

There is an open discussion to deprecate/remove the concept of marking a resource 'down' altogether.
 - https://github.com/irods/irods/issues/4508#issuecomment-1009485419

**Comment by d-w-moore** [comment]
iRODSResource does now have a status member reflecting the query result.  So we'd be looking to replace that with this new, proposed property, right?
Or we could deprecate the old member and have new property as a boolean? Essentially:
```
class iRODSResource
# ...
@property 
def status_is_up(self): return self.manager.get ('status') != 'down'
```

**Comment by d-w-moore** [comment]
Actually, a lot of this block of members could be made into properties.  At least, the ones that are mutable.

**Comment by trel** [comment]
> have the new property as a boolean

This would require an interpretation of the string.    I don't think that's what we want in the long run.

**Comment by d-w-moore** [comment]
Fair 'nuf

**Comment by trel** [comment]
Closing.

This has been addressed sufficiently in the discussion for https://github.com/irods/python-irodsclient/pull/381.
