### ISSUE TITLE
Expose create and modify times for metadata

### ISSUE THREAD

**Issue by paulborgermans** [irods/python-irodsclient#386]
Allthough metadata items can be queried and filtered  for create_time/modify_time columns, the higher level class  iRODSMeta does not expose these fields. Consequently, they are not available when fetching metadata from collections and data objects (and resources and users).

Can these time fields be added?

**Comment by korydraughn** [comment]
So this is about returning more information with the metadata results?

For most cases, the create/modify time of metadata isn't needed. Including these additional fields increases the size of the payload, which may be okay for small resultsets. However, for large resultsets, it could become an issue.

Are there reasons why using custom GenQuery is not good enough?

**Comment by paulborgermans** [comment]
A custom GenQuery may work, haven't figured out how that could work. I guess it boil down to duplicating and modifying the queries in the API (metdata manager)... the code is the documentation albeit a but hard. So far in our use cases, the payload from the attribute values may be the dominant factor in the result set size

**Comment by paulborgermans** [comment]
See also [Pull request #387](https://github.com/irods/python-irodsclient/pull/387)

**Comment by korydraughn** [comment]
> A custom GenQuery may work, haven't figured out how that could work. I guess it boils down to duplicating and modifying the queries in the API (metdata manager)... the code is the documentation albeit a but hard. So far in our use cases, the payload from the attribute values may be the dominant factor in the result set size

@d-w-moore Can the PRC accept a normal GenQuery string and iterate over the results? If so, can you provide an example? For example, something like the following:
```python
with iRODSSession(...) as session:
    for row in session.exec_genquery('select META_DATA_ATTR_NAME, META_DATA_CREATE_TIME'):
        # Do something with row.
```

**Comment by korydraughn** [comment]
@paulborgermans Perhaps those fields become optional and then it's up to the caller to request that they be populated. That way, people using the API aren't surprised and people who need those fields can request them.

@d-w-moore Thoughts?

**Comment by paulborgermans** [comment]
Y

> @paulborgermans Perhaps those fields become optional and then it's up to the caller to request that they be populated. That way, people using the API aren't surprised and people who need those fields can request them.

Yes, that was another option I would consider, then by default no mod/create times for BC and an extra parameter to return if wanted/needed

**Comment by korydraughn** [comment]
I think that is a fine solution. Let's see what @d-w-moore thinks.

**Comment by d-w-moore** [comment]
Ok... thought we were exposing these.  I will take a look today

**Comment by paulborgermans** [comment]
Thanks guys!
