### ISSUE TITLE
removing collections results in dropped connection and removal ultimately failing

### ISSUE THREAD

**Issue by jerry57** [irods/python-irodsclient#39]
We are using Robotframework for testing applications and have a library that uses the python-irodsclient

One of our keywords is for removing collections.  This works just fine as long as the collection does not contain much data or collections.  Once there is some data (our test is about 400MBs and 30+ subcollections) and it fails with a broken connection.

The full library is available at:
https://github.com/cyverse/Robotframework-iRODS-Library.git

Here is the code for the "Delete a Collection" keyword:

```
    def delete_a_collection(self, path=None, recursive=True, force=False, alias="default_connection"):
        """ Delete an existing iRODS collection at the given path

            'path'      - the collection you want to delete (full path)
            'recursive' - boolean defaults to true
            'force'     - boolean defaults to false (all items sent to trash)
            'alias'     - Robotframework alias to identify the connection

        Example usage:
        | Delete A Collection | /tempZone/home/jdoe/NewCollectionName | connectionAlias
        | Log | ${output}
        | Should Not Contain | ${output} | error

        """
        logger.info('Delete a Collection : alias=%s, path=%s, recursive=%s, force=%s' % (alias, path, recursive, force))
        alias = str(alias)
        path = str(path)
        session = self._cache.switch(alias)
        coll = session.collections.remove(path, recursive, force)

```

**Comment by jerry57** [comment]
Here is the only thing I have been able to find in the irods log:

Apr 28 08:38:10 pid:30180 NOTICE: execRule: applyRule Failed: ipc_amqpSend with status -1091000
Apr 28 08:38:10 pid:30180 ERROR: svrSendCollOprStat: client reply 0 != 99999997.
Apr 28 08:38:10 pid:30180 ERROR: _rsPhyRmColl: svrSendCollOprStat failed for /iplant/home/ipctest/Jer_iRODSLibrary_Regression3/iPlant-TestData/.git/objects/8a. status = -313000 status = -313000 UNMATCHED_KEY_OR_INDEX
Apr 28 08:38:10 pid:30238 NOTICE: readAndProcClientMsg: received disconnect msg from client
Apr 28 08:38:10 pid:30238 NOTICE: Agent exiting with status = 0

**Comment by adetorcy** [comment]
Which iRODS version is the server running?

**Comment by jerry57** [comment]
3.3.1 or 4.1.8  The above logs are from 3.3.1

**Comment by adetorcy** [comment]
Possibly related to irods/irods#3160
