### ISSUE TITLE
Getting permission does not bring `g:` prefix for groups

### ISSUE THREAD

**Issue by mstfdkmn** [irods/python-irodsclient#395]
Querying acl on (getting permission of ) an object doesn't bring `g` prefix specifying group based permission although there is already an granted group permission exists. AccessManager behaves it like a normal user. On the other hand `ils -A` shows it is a group user.

ils -A:

```
 ils -A /kuleuven_tier1_pilot/home/lt1_d_pilot_004
/kuleuven_tier1_pilot/home/lt1_d_pilot_004:
        ACL - g:lt1_d_pilot_004#kuleuven_tier1_pilot:own
        Inheritance - Enabled
```

a test script:
```
import os, os.path
from irods.session import iRODSSession
import pprint

env_file = os.getenv('IRODS_ENVIRONMENT_FILE', os.path.expanduser('~/.irods/irods_environment.json'))
with iRODSSession(irods_env_file=env_file) as session:
    pp = pprint.PrettyPrinter(indent=4)
    coll = session.collections.get('/kuleuven_tier1_pilot/home/lt1_d_pilot_004')
    acl_coll = session.permissions.get(coll)
    [print(f'     {i.user_name}#{i.user_zone}:{i.access_name}') for i in acl_coll]
    print(acl_coll)
```
result of test script:
```
python test.py
     vsc42644#kuleuven_tier1_pilot:own
     lt1_d_pilot_004#kuleuven_tier1_pilot:own
     vsc44192#kuleuven_tier1_pilot:own
[   <iRODSAccess own /kuleuven_tier1_pilot/home/lt1_d_pilot_004 vsc42644 kuleuven_tier1_pilot>,
    <iRODSAccess own /kuleuven_tier1_pilot/home/lt1_d_pilot_004 lt1_d_pilot_004 kuleuven_tier1_pilot>,
    <iRODSAccess own /kuleuven_tier1_pilot/home/lt1_d_pilot_004 vsc44192 kuleuven_tier1_pilot>]
 
```

**Comment by alanking** [comment]
Looks like we could add `user_type.type` to the `query` and `iRODSAccess` will need to learn about `user_type` as well:

https://github.com/irods/python-irodsclient/blob/8f53d2e25eb1ddd134539f01e1537242f3193f2f/irods/manager/access_manager.py#L56-L64

Does this break anything in the existing model(s), @d-w-moore?

**Comment by d-w-moore** [comment]
@alanking, yes  that should be possible, looking into it now....

**Comment by d-w-moore** [comment]
Presently, #411 adds a `user_type` attribute to the iRODSAccess ( per @alanking 's recommendation above ).  This will have the value "rodsgroup" in the analogous situation where ils -A would print a "g:" prefix.  Does this check ok with your expectations, @mstfdkmn ?

**Comment by mstfdkmn** [comment]
Yes, this seems exactly what we needed. Thanks.
