### ISSUE TITLE
`put()` ignoring `minimum_free_space_for_create_in_bytes` and `resc_status`

### ISSUE THREAD

**Issue by kript** [irods/python-irodsclient#399]
Using the script in #398 I was regularly hitting upload errors. In the Consumer logs I saw lots of

```
Oct 10 11:25:44 pid:25295 remote addresses: xxx.xxx.xxx.xxx  ERROR: [-]      ../server/api/src/rsFileWrite.cpp:115:int _rsFileWrite(rsComm_t *, fileWriteInp_t *, bytesBuf_t *) :  status [UNIX_FILE_WRITE_ERR]  errno [No space left on device] -- message [fileWrite for [/irods-seq-i03-fg/home/jc18#Sanger1-dev/irods_test/1mb.bgf]]
        [-]     ../server/drivers/src/fileDriver.cpp:135:irods::error fileWrite(rsComm_t *, irods::first_class_object_ptr, void *, int) :  status [UNIX_FILE_WRITE_ERR]  errno [No space left on device] -- message [failed to call 'write']
                [-]     ../plugins/resources/passthru/libpassthru.cpp:229:irods::error passthru_file_write(irods::plugin_context &, void *, int) :  status [UNIX_FILE_WRITE_ERR]  errno [No space left on device] -- message [passthru_file_write_plugin - failed calling child write.]
                        [-]     /irods_source/plugins/resources/replication/librepl.cpp:772:irods::error repl_file_write(irods::plugin_context &, void *, int) :  status [UNIX_FILE_WRITE_ERR]  errno [No space left on device] -- message [repl_file_write - Failed while calling child operation.]
                                [-]     ../plugins/resources/random/librandom.cpp:298:irods::error random_file_write(irods::plugin_context &, void *, int) :  status [UNIX_FILE_WRITE_ERR]  errno [No space left on device] -- message [Failed calling operation on child resource.]
                                        [-]     ../plugins/resources/random/librandom.cpp:298:irods::error random_file_write(irods::plugin_context &, void *, int) :  status [UNIX_FILE_WRITE_ERR]  errno [No space left on device] -- message [Failed calling operation on child resource.]
                                                [-]     ../plugins/resources/unixfilesystem/libunixfilesystem.cpp:804:irods::error unix_file_write(irods::plugin_context &, void *, int) :  status [UNIX_FILE_WRITE_ERR]  errno [No space left on device] -- message [Write file: "/irods-seq-i03-fg/home/jc18#Sanger1-dev/irods_test/1mb.bgf", errno = "No space left on device", status = -513028.]
```

However both the tree and the resc status should vote no write;
```
$ iadmin lr irods-seq-i03-fg
resc_id: 12380
resc_name: irods-seq-i03-fg
zone_name: seq-dev
resc_type_name: unixfilesystem
resc_net: irods-r2-dev.internal.sanger.ac.uk
resc_def_path: /irods-seq-i03-fg
free_space: 0
free_space_ts: 2022-10-10.11:22:05
resc_info:
r_comment:
resc_status: down
create_ts: 2016-06-14.11:48:38
modify_ts: 2022-10-10.11:22:05
resc_children:
resc_context: minimum_free_space_for_create_in_bytes=5150212096
resc_parent: 12172
resc_objcount: 22
resc_parent_context:
```
and for good reason;
```
$ df -h /irods-seq-i03-fg/
Filesystem                                       Size  Used Avail Use% Mounted on
/dev/mapper/irods_resources-irods--seq--i03--fg  4.8G  4.6G     0 100% /irods-seq-i03-fg
```

**Comment by kript** [comment]
It's _also_ odd that the 4.2.7 server isn't giving it a different resource every time `put(0` is called, no?

**Comment by kript** [comment]
OK, further testing reveals that `iRODSSession.data_objects` doesn't check the state of the catalogue once its created.

The marking down and setting `minimum_free_space_for_create_in_bytes` =  disk size was done _while) the script was uploading. 

When it was re-run after the resource tidying  it correctly bypassed the downed & full resource and uploaded without errors (which is going to make #398 tricky to continue to investigate!).

**Comment by kript** [comment]
So there appear to be two issues;

1. `iRODSSession.data_objects.put()` doesn't refresh the state of the catalogue after/before each call.
2. `iRODSSession.data_objects.put()` appears to ignore `minimum_free_space_for_create_in_bytes` / `free_space`

**Comment by d-w-moore** [comment]
Solution seems contingent on making the Python client conform to PUT api - or maybe just simulate the necessary server negotiation per-call to respect those settings.  @alanking @trel ?

**Comment by trel** [comment]
Well, it seems as long as we can propagate an error back to the client - the client can react however it wants/should.  
 Right now, there's no signal for @kript to react to.

Regarding the put() semantics... python `put` is actually an open/write/close - and that's not going to change without significant discussion / upheaval.

Then...

Point 1) .... I'm not terribly surprised that the catalog is not being consulted again within the same session.  It seems the current behavior is the most expected.  Happy to be convinced otherwise.

Point 2)... is a bit more surprising.  Is it true it's being ignored?   Given this statement?
> When it was re-run after the resource tidying it correctly bypassed the downed & full resource and uploaded without errors

**Comment by kript** [comment]
> 
> Then...
> 
> Point 1) .... I'm not terribly surprised that the catalog is not being consulted again within the same session. It seems the current behavior is the most expected. Happy to be convinced otherwise.
> 

This isn't the behaviour for `iput`, so I wouldn't expect it to be the behaviour for python client put(). 

> Point 2)... is a bit more surprising. Is it true it's being ignored? Given this statement?
> 
> > When it was re-run after the resource tidying it correctly bypassed the downed & full resource and uploaded without errors

It certainly seems to ignore the `status down`, as it did so on a fresh session as well as during a session where the status was changed. 

If there is no catalog refresh of state happening this needs documenting, I would say, and to what degree - for example, in #398 the only way to ensure a clean catalog each time is to have the  `put()` happen after an `session = iRODSSession` and immediately followed by an `session.cleanup()`. 
It's inefficient but arguably no worse than an `iput`, however, the README examples and documentation need to state this explicitly.
