### ISSUE TITLE
Expose errno code in string representation of an `irods.exception`

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#400]
It was noted in this previous [issue and comment](https://github.com/irods/python-irodsclient/issues/398#issuecomment-1279984262) that more information could be given in the product of repr(e), with `e` being an irods.exception returned to the PRC client from the iRODS server.  Specifically the **errno** code provided by the OS (and propagated back to the client was `e.code` is  28 -> ENOSPC -> 'No space left on device'. That is essential information which rightfully should be expected as part of the `repr(e)` output.

Presently, if we do a too-large put with this script 
```
#!/usr/bin/env python3
import sys
from irods.test.helpers import make_session
import irods.keywords as kw
s=make_session()
args=sys.argv[1:3]
try:
  s.data_objects.put( *args,
        **{kw.DEST_RESC_NAME_KW:'resc1'}
        )
  pass
except Exception as e:
  print(repr(e))
  print(e.code)
irods@precision-5530:/iRods/exper$ irm -fr abc.put
```
(abc.put being too large to fit on iRODS resource `resc1`), we get:
```
UNIX_FILE_WRITE_ERR(None,)
-513028
```
The first line of output  (from repr(e)) should  expose the error code instead of simply the args member of the exception, ie.: `(None,)`, as is the base `Exception.__repr__` behavior.

**Comment by alanking** [comment]
@d-w-moore - Please close if finished. Thanks
