### ISSUE TITLE
Rule execution with a file with null input throws an error `-1201000`

### ISSUE THREAD

**Issue by mstfdkmn** [irods/python-irodsclient#403]
Hello,

It seems I encountered another type of [this ](https://github.com/irods/python-irodsclient/issues/314) null input issue of the rule call. That is:

Specifying the rule engine instance in the rule call is **not** throwing `-1201000`.
`Rule(session, instance_name = 'irods_rule_engine_plugin-python-instance', rule_file = 'test.r').execute()`

But the call below seems hitting the **same error**  - no referral to the rule engine instance, btw:
`Rule(session, rule_file = 'test.r').execute()`

Logs:
`NOTICE: execMyRule @external#012def main(rule_args, callback, rei):#012    """#012    A test rule in python#012    """#012#012    callback.print_hello()#012    callback.writeLine('serverLog', 'IDENTIFIER: Test delay rule for server')#012    callback.testZone()#012#012 Failed with status -1201000`

Could you test this?
And if using the `instance_name `keyword argument here is always required, then may not be optional? - or we might expect to see another error?

PRC - 1.1.5
iRODS server - 4.2.10

**Comment by trel** [comment]
What is the output of running `irule -a`?

This will show the ordered listing of the configured rule engine plugin instances on the connected server.

I believe `instance_name` is optional because we default to using the 'first' instance in the above listing.

**Comment by mstfdkmn** [comment]
The output of `irule -a` is as follows:

```
Level 0: Available rule engine plugin instances:
        irods_rule_engine_plugin-irods_rule_language-instance
        irods_rule_engine_plugin-cpp_default_policy-instance
        irods_rule_engine_plugin-python-instance
```
Then I guess we should not expect to see `-1201000` for a call via the file that has `null` input. And we can expect as many calls as how many the configured rule engines exist, right?

**Comment by trel** [comment]
With that configuration...
```
Rule(session, rule_file = 'test.r').execute()
```
will be run by `irods_rule_engine_plugin-irods_rule_language-instance` first.  Once it fails (because it's the wrong syntax for that rule engine plugin ... `-1201000 RE_PARSER_ERROR`), it will then be attempted to be run by `irods_rule_engine_plugin-cpp_default_policy-instance` (and fail) and then finally by `irods_rule_engine_plugin-python-instance` (success).

So, if this is python rule you're trying to run - I would expect to see two `-1201000` failures before a successful attempt by `irods_rule_engine_plugin-python-instance`.

**Comment by mstfdkmn** [comment]
Ah okay, if I understood correctly, this issue is not related to the old one (null input) - in fact this is not an issue. I guess then we could close this. Thanks Terrell for clarifying.

**Comment by trel** [comment]
Agreed - thanks.   Closing.

**Comment by d-w-moore** [comment]
Wonderful - thanks for that answer @trel

**Comment by mstfdkmn** [comment]
> With that configuration...
> 
> ```
> Rule(session, rule_file = 'test.r').execute()
> ```
> 
> will be run by `irods_rule_engine_plugin-irods_rule_language-instance` first. Once it fails (because it's the wrong syntax for that rule engine plugin ... `-1201000 RE_PARSER_ERROR`), it will then be attempted to be run by `irods_rule_engine_plugin-cpp_default_policy-instance` (and fail) and then finally by `irods_rule_engine_plugin-python-instance` (success).
> 
> So, if this is python rule you're trying to run - I would expect to see two `-1201000` failures before a successful attempt by `irods_rule_engine_plugin-python-instance`.

to clarify:
I could see only one `-1201000` failure for `irods_rule_engine_plugin-irods_rule_language-instance` before a successful attempt by `irods_rule_engine_plugin-python-instance`. For `irods_rule_engine_plugin-cpp_default_policy-instance`, following is seen
`ERROR: [addMsParamToArray] - type is null for [ruleExecOut]`
