### ISSUE TITLE
Fix password_obfuscation in Windows

### ISSUE THREAD

**Issue by jpmcfarland** [irods/python-irodsclient#404]
The Python `os` library module in Windows does not implement the `getuid()` function.  As a result, attempting to `encode()`/`decode()` a password with the `password_obfuscation` module results in an `AttributeError`.  The `getlogin()` function, however, is implemented for Windows.  Provided the `login` can be assumed to be as unique as a `uid`, this can be used as replacement _salt_ for the process.  Converted to an `int` with, e.g.:

```python
sum((ord(char) for char in os.getlogin()))
```

it can be dropped-in directly when `os.getuid()` is not available.  PR #405 implements this.

**Comment by alanking** [comment]
Please close if the changes merged in #405 resolve this issue. Thanks!

**Comment by jpmcfarland** [comment]
Absolutely!
