### ISSUE TITLE
Open socket connections can still cause log noise when gc-collected in Python

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#410]
Intimately related to, and arguably the same as, #269.

Failing to call cleanup( ) (by omission or by allowing the session to persist to interpreter exit) on an active session under Python2 is already known to cause  the log errors discussed in #269, although Python3 had apparently dealt better with this particular problem since that issue was closed.

But this problem still prevails, for example when cyclic references are created the above-mentioned error still is generated, even under Python3 (try as we might to ensure a deliberate call to cleanup( )):
```python
from irods.test.helpers import (make_session, home_collection)
class X:
    def __del__(self):
      self.s.cleanup()
    def __init__(self):
      self.s = make_session( )
      c = self.s.collections.get(home_collection(self.s))
def main( ):
    x = X( )
    y = X( )
    x.z = y
    y.z = x  # circular ref

if __name__ == '__main__':
    main( )
```
Additionally, in both Python2/3, SSL sockets fail to destruct cleanly in the simplest of cases. This example:
```python
sess = irods.session.iRODSSession( irods_env_file = '/path/to/env-file', ssl_context = ssl.create_default_context( ssl.Purpose.SERVER_AUTH,...))
home = irods.test.helpers.home_collection(s)
s.collections.get(home)'

# allow sess to exit scope
```
dumps into the error log:
```
                [-]     /repos/irods/plugins/network/ssl/libssl.cpp:572:irods::error ssl_read_msg_header(irods::plugin_context &, void *, stru[1001/1001]*) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]
                                                                                                              
Nov  9 00:23:32 pid:7694 remote addresses: 127.0.0.1 ERROR: [-] /repos/irods/server/core/src/rodsAgent.cpp:566:int runIrodsAgentFactory(sockaddr_un) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']
        [-]     /repos/irods/lib/core/src/sockComm.cpp:160:irods::error sockAgentStop(irods::network_object_ptr) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']                    
                [-]     /repos/irods/plugins/network/ssl/libssl.cpp:952:irods::error ssl_agent_stop(irods::plugin_context &) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error completing shutdown of SSL connection]          
                                                                                                              
Nov  9 00:23:32 pid:116  ERROR: Agent process [7694] exited with status [64]   
```

**Comment by trel** [comment]
Shouldn't the session's `__del__` be called when the program exits cleanly and/or the session exits scope?

**Comment by d-w-moore** [comment]
That was the original idea, and why the cleanup call was placed in that method. The issue seems to be the order in which the various __del__ methods are called (`irods.connection.Connection` has a __del__ method too), which is a `gc` implementation detail. There's PEP442 which is implemented in Python3.4+.  Also, this: https://docs.python.org/3/faq/programming.html?highlight=_del_#my-class-defines-del-but-it-is-not-called-when-i-delete-the-object

**Comment by d-w-moore** [comment]
> Shouldn't the session's `__del__` be called when the program exits cleanly and/or the session exits scope?
That turns out to be the better idea possibly: to make sure that happens.  I am finding, by experiments [on this alternate dev branch](https://github.com/d-w-moore/python-irodsclient/tree/406-alt.m) , that the logs are indeed quieter when the manager objects' backward refs to their session objects are weak!

**Comment by trel** [comment]
Oh, nice.   Is that a pattern that is well-known or defined by others?   Is there a down-side?

**Comment by d-w-moore** [comment]
Yes, that pattern is pretty much quoted as 
> Tree data structures, for instance, should use weak references for their parent and sibling references (if they need them!).

In the link to the python docs I gave above.  And I can't think of any downsides yet.  Pretty much the child node in the tree (the manager object) should go away  when the parent (i.e. the session object) does, and wouldn't used any longer, anyway, as it's only thru the parent that it's typically accessed.

**Comment by d-w-moore** [comment]
Well... as painful as it is to admit, the more popular pattern seems to be the wrong one for solving this issue. It turns out that we do some stuff with manager objects directly, and thus implicitly rely on the session object to outlive objects that have derived from their use.  Example follows:
```
import irods.test.helpers as h
s=h.make_session()
n=h.home_collection(s)
c=s.collections.get(n)
del s
c.subcollections
```
This raises a ReferenceError using the sanctioned approach of using weak refs to parent objects in tree-like object hierarchies, (to reiterate I played with that [here](https://github.com/d-w-moore/python-irodsclient/tree/406-alt.m)) but not with the atexit-oriented approach i've been taking all along.  Bah.... I could mitigate the tree approach somewhat, perhaps, but I think we're facing a choice of lesser evils here.

**Comment by d-w-moore** [comment]
>  the more popular pattern seems to be the wrong one for solving this issue. 

(To quote myself.) Yes indeed, the test suite runs with no Fails or Errors if I stay with this PR the way it is and ditch the weak-ref-to-parent-session idea.  Unfortunate, but I think we must choose the uglier solution in this case : /

**Comment by trel** [comment]
Yes, it seems we desire standalone functionality, but also easy/free cleanup...

Interesting.

**Comment by d-w-moore** [comment]
Yes, I mean it's not like anyone has complained about the messy cleanup.  But, it does make the "real things" harder to find in the logs!

**Comment by d-w-moore** [comment]
> Yes, it seems we desire standalone functionality ...

@kory , @MartinFlores751  and I discussed this yesterday.  I think we concluded the likely scenario a PRC rewrite would be largely free functions to handle API and only a veneer of OOP-type design where for example state needs to be kept. As in, you would want objects around to represent the catalog objects, if not also queries and connections. "Pythonic-ness" (pythonicity?) seemed to be a dubious advantage here, although I have my doubts as to whether career Python users would be receptive to the lack of a high-level abstraction if we didn't manage provide that on top of the lower level things.

But yeah, just the idea of having to book-keep these objects and enforce the cleanup( ) call on sessions goes way, way beyond the "Python client as bare api endpoint " idea.

**Comment by korydraughn** [comment]
Correct. We provide the low level facilities and then build high level facilities on top of them. This also gives other python devs the freedom to experiment and be creative.

The rewrite would require that the low level and high level facilities exist before a 1.0.0 release.

**Comment by trel** [comment]
Rather than just... add new things to this one and call it 2.0.0 and phase out the old(?) stuff by 3.0.0?

**Comment by korydraughn** [comment]
That is perfectly acceptable to me if the line between the two implementations is clear.

We can introduce a new module that holds only the new interfaces and its components. The first thing it could hold would be the connection/networking code. If the existing PRC networking code is well designed, then we turn that into its own module.

Everything else is built on top of that.

**Comment by trel** [comment]
and i think the community would have a good time playing python experts too.    quality feedback opportunity.
