### ISSUE TITLE
raise error in testing if server is more recent than advertised IRODS_VERSION

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#418]
`irods.message.IRODS_VERSION` is the highest version of iRODS for which the PRC advertises compatibility. This variable is used in the generation of the `StartupPack` message.
By raising an error condition when the test suite is run if  the server is more recent than what IRODS_VERSION variable indicates appropriate, we can ensure a reminder to update the variable.

**Comment by trel** [comment]
We want an error, or just a warning?   I suppose a failure is a failed test - which is the point.

**Comment by korydraughn** [comment]
I think a failure is appropriate because we want the PRC to always match the latest server version.

**Comment by d-w-moore** [comment]
I do need to see how this will play out in reality.  It's just throwing a custom exception right now. Perhaps there is a way to abort the suite as a whole.

**Comment by trel** [comment]
a single failing test is fine - whatever we build should care about that at the 'suite' level, regardless.

**Comment by alanking** [comment]
@d-w-moore - Please close if finished. Thanks!
