### ISSUE TITLE
iput-like command?

### ISSUE THREAD

**Issue by fikipollo** [irods/python-irodsclient#42]
Hey!

First congrats for this great work, I love this API!

I want to send a local file to iRODS using your API but I'm not sure how should I proceed. Using iCommand, I'd use the "[iput](https://docs.irods.org/master/icommands/user/#iput)" command for this purpose however I can't find a equivalent for "iput" on your API. 

Am I missing something?

Thanks and best regards.

Rafa

**Comment by trel** [comment]
@adetorcy answered this on the chat list a month or so ago.

https://groups.google.com/forum/#!msg/iROD-Chat/dWEHYzNfMgo/gSeeJ2XGAQAJ

> You will have to read your local file's content and write it to a new irods object, e.g:
> 
> ```
> obj = session.data_objects.create(obj_path)
> with obj.open('w') as obj_desc:
>     obj_desc.write(content)
> 
> # refresh object after write
> return session.data_objects.get(obj_path) 
> ```
> 
> You might also want to take a look at the test code in https://github.com/irods/python-irodsclient/tree/master/irods/test for further examples.
>

**Comment by fikipollo** [comment]
OK, that sounds like a solution but could be slightly slow when working with big files, right?

**Comment by adetorcy** [comment]
Correct. There is an open issue (#28) to improve transfer speeds, which I plan on addressing in the near future. Probably once iRODS 4.2 is out.

**Comment by Chriou** [comment]
Hello, 

Thanks a lots for your API! 
I would like to know if there is further progress on this feature, because I am going to have to transfer large files with irods. 

I get your example to "iget" file : 
obj = session.data_objects.get("yourfile.txt")
f = obj.open('r+')
str1 = f.read(1024)

Is there an other way to "iget" file with your API?

Regards

Chloe
