### ISSUE TITLE
Show iRODS Permission Model - List Access Levels

### ISSUE THREAD

**Issue by mstfdkmn** [irods/python-irodsclient#420]
We are now in testing phase of 4.3.0. Regarding with the 10 level access controls of iRODS 4.3.0; I am not sure how much this will be important or needed at this moment but I think it looks that end users may need this and also portal clients running on top of PRC may find it useful once PRC is used against iRODS 4.3.0 server.

I guess getting ACLs (names) of available iRODS Permission Model in a list by an attribute or a method like `session.permissions.list` or `session.permissions.show` could be useful. Or a function in #412 that we can call can also help.

Because as known there are 10 different names that users should memorize/know in order to use them. As an alternative they can use `ichmod -h` in iCommands or look into documentations exist.

**Comment by d-w-moore** [comment]
This could open up a danger of multiple sources of truth, unless there's a server API that supplies these strings to a client, which I don't think exists.

**Comment by d-w-moore** [comment]
Ok, that fits. we do something similar for `irods.keywords` and the names of exceptions.

**Comment by d-w-moore** [comment]
One more wrinkle here is that eg code 1130 translates to "delete object" on 4.2 but "delete_object" on 4.3.0

**Comment by trel** [comment]
True, but nothing knew about or checked 'delete object' in 4.2.x as far as we know.

**Comment by d-w-moore** [comment]
Good point.  Which reminds me, the access levels map returned will depend on server we're connecting to.

**Comment by trel** [comment]
or... we don't create an API and get a return... we just put the list in the PRC.

**Comment by d-w-moore** [comment]
Yes I suppose anything more could be considered an enhancement. Sold!

**Comment by trel** [comment]
@d-w-moore how would @mstfdkmn be able to see the permissions you've named/added?

he originally asked about `session.permissions.list` or `session.permissions.show`

**Comment by d-w-moore** [comment]
Looking at it again, it needs to be simplified.  Within the context of these changes, it would be something like `irods.access.iRODSAccess.codes()` or  ` iRODSAccess.strings( )` 

In the light of day, something like iRODSAccess.keys() would make more sense. See [this new pull request](https://github.com/irods/python-irodsclient/pull/423).

**Comment by trel** [comment]
reopening for additional work

**Comment by d-w-moore** [comment]
Is this sufficient to close this issue?

**Comment by d-w-moore** [comment]
Will assume so, I think this does it....

**Comment by alanking** [comment]
Yes, we can always open another one if an issue is encountered or further enhancements are requested.
