### ISSUE TITLE
irods.exception.SYS_NO_API_PRIV when groupadmin adds user to group

### ISSUE THREAD

**Issue by simstoica** [irods/python-irodsclient#426]
When a group_admin users tries to add an user to the recently group, `irods.exception.SYS_NO_API_PRIV` exception is raised   

```python
        self.group = self.admin_sess.user_groups.create(self.group_name, group_admin=True)

        # add user 
        self.group.addmember(self.user_name, self.sess.zone)
```

I think that the group admin should be able to manage users in the group, just as it is available in the 'igroupadmin' icommand. 

Similar to #374, which fixes the creation of the group.

**Comment by simstoica** [comment]
I tried a fix in the same line as @MartinFlores751 for #374, but somehow I still end up in the wrong api, because I get  (Or could be that I did something wrong,) 

Here is what I tried (to no avail), in `user_manager.py` with `group_admin = True` (and the corresponding calls ). But maybe that is too simplistic. 

```python
def addmember(self, group_name, user_name, user_zone="", group_admin=False):
        if group_admin:
            message_body = UserAdminRequest(
                "atg",
                group_name,
                user_name,
                user_zone
            )            
            api_to_use = api_number['USER_ADMIN_AN']
        else:
            message_body = GeneralAdminRequest(
                "modify",
                "group",
                group_name,
                "add",
                user_name,
                user_zone
            )
            api_to_use = api_number['GENERAL_ADMIN_AN']
            
        request = iRODSMessage("RODS_API_REQ", msg=message_body,
                               int_info=api_to_use)
        with self.sess.pool.get_connection() as conn:
            conn.send(request)
            response = conn.recv()
        logger.debug(response.int_info)
```

**Comment by korydraughn** [comment]
Based on the implementation of `igroupadmin`, it looks like both APIs take the same arguments.

Try constructing `UserAdminRequest` with the same arguments as `GeneralAdminRequest`.

**Comment by d-w-moore** [comment]
#427 added

**Comment by d-w-moore** [comment]
Taking @korydraughn's advice: 

> Based on the implementation of `igroupadmin`, it looks like both APIs take the same arguments.
> 
> Try constructing `UserAdminRequest` with the same arguments as `GeneralAdminRequest`.

I've added a stab at this in #427 ; seems to work based on manual tests.

**Comment by simstoica** [comment]
The changes also worked for me (including the fact that the `groupadmin` cannot manage the group members if he does not add himself to the group as the first member, learned the hard way).  Also tested a similar change for the remove member and that one works as well. 

I wonder now, by seeing that you extract the user type from the session, is that also not possible for the create function? Because in the current version ( 1.1.6)  the calls to create a group are a bit asymmetric, since the `groupadmin` needs to pass the flag `groupadmin=True`

**Comment by korydraughn** [comment]
I forgot about that. We should follow that same pattern for these operations (i.e. add a parameter that indicates execute-as-groupadmin).

**Comment by d-w-moore** [comment]
> I forgot about that. We should follow that same pattern for these operations (i.e. add a parameter that indicates execute-as-groupadmin).

They should be consistent, right? either both would have the extra parameter, or neither.

**Comment by d-w-moore** [comment]
Looking back at the create function, it appears group_admin refers to whether the user being created is to be a group or not. @MartinFlores751 ?

**Comment by korydraughn** [comment]
Correct. We spent some time discussing this as a team back in November and landed on an extra parameter. That provides more control over the API.

**Comment by korydraughn** [comment]
> Looking back at the create function, it appears group_admin refers to whether the user being created is to be a group or not. (Not a question of whether the user owning the session is a group admin... @MartinFlores751 ?

That flag controls whether the operation should invoke rcGeneralAdmin or rcUserAdmin.

**Comment by d-w-moore** [comment]
ok ... maybe sensing the user type is the wrong thing to do, then.

**Comment by d-w-moore** [comment]
Ok, but I think this means the group_admin doesn't apply to addmember, maybe?

**Comment by d-w-moore** [comment]
My confusion stems from the fact, I think, that for user creation the parameters change  (mkgroup vs "add","user")  as well as which API is used.  Is it possible some blurring of function is going on there?

**Comment by korydraughn** [comment]
> Ok, but I think this means the group_admin doesn't apply to addmember, maybe?

It does for the same reasons as for `create()`. We give the caller the option to decide which API to invoke.

> My confusion stems from the fact, I think, that for user creation the parameters change (mkgroup vs "add","user") as well as which API is used. Is it possible some blurring of function is going on there?

Yes. `create()` is too loose. It would be better to separate the functionality into `create_user()` and `create_group()`. We can discuss that in a separate issue.

For now, I think we introduce the `group_admin` parameter and verify that all groupadmin operations are honored when executed as a groupadmin (i.e. mkuser, atg, rfg, lg, etc).

**Comment by d-w-moore** [comment]
I agree. Maybe we'll have session.users.create and session.user_groups.create handle those different (or what should be different) functions.

**Comment by trel** [comment]
or just `session.groups.create()`?

**Comment by korydraughn** [comment]
Even better.

**Comment by d-w-moore** [comment]
There are other `igroupadmin` type things the python client doesn't do, which maybe it should, like mkuser USER INITPW and such. Making a new issue.

**Comment by alanking** [comment]
@d-w-moore - Please close if complete. Thanks
