### ISSUE TITLE
more igroupadmin functions could be implemented by the Python client

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#428]
PRC does not do certain things on behalf of a group admin yet, which it easily could. For example:
   - rfg (remove users from groups)
   - mkuser ( create a new user and simultaneously initialize the password field ) 

> There are other `igroupadmin` type things the python client doesn't do, which maybe it should, like mkuser USER INITPW and such. Making a new issue.

_Originally posted by @d-w-moore in https://github.com/irods/python-irodsclient/issues/426#issuecomment-1413178719_

**Comment by alanking** [comment]
@d-w-moore - Please close if complete. Thanks
