### ISSUE TITLE
Python-irodsclient needs different irods_authentication_scheme than iCommands in iRODS 4.3.0.

### ISSUE THREAD

**Issue by jefscheepers** [irods/python-irodsclient#430]
Since iRODS 4.3.0., iCommands require the irods_authentication_scheme to be 'pam_password' instead of 'PAM' in the irods_environment.json if you are using PAM.

However, the Python-irodsclient still seems to require 'PAM', even if the server is 4.3.0.
This means that on a 4.3.0., users cannot use the same irods_environment.json for iCommands and the Python client.

This is inconvenient for two reasons:
- A lot of users use iCommands next to the python-irodsclient to quickly be able to check the effect of their scripts etc.
- Authenticating with iinit is for Linux the easiest way to authenticate for the Python-irodsclient

Could some changes be made so that the Python-irodsclient also accepts 'pam_password'?

Slightly related to:
https://github.com/irods/irods/issues/3164
https://github.com/irods/irods/issues/6785
https://github.com/irods/python-irodsclient/issues/370

**Comment by alanking** [comment]
We are hoping to integrate the authentication plugin framework for PRC and other clients in the near future which would allow for using the new authentication scheme.

@d-w-moore - What do you think about adding a shim for the `pam_password` authentication scheme from the client environment until we are able to port the authentication plugin framework to python?

**Comment by korydraughn** [comment]
When you say shim, are you saying to have the PRC accept `pam_password` as an alias for `PAM`?

**Comment by alanking** [comment]
Right, until we get the framework ported over. It could possibly trip up users and admins depending on how it's implemented, so it might be better to just prioritize porting the authentication framework.

**Comment by korydraughn** [comment]
I think prioritizing the porting of the auth framework is the right way to go. I sense that making the PRC treat `pam_password` like `PAM` will lead to confusion for users.

With that said, let's aim at starting the port next week.

**Comment by d-w-moore** [comment]
I'd have agreed to a shim as well, maybe , but I guess a port is cleaner?  Yes, let's look into it next week.

**Comment by alanking** [comment]
@d-w-moore - I think that the workaround to use the legacy auth plugins is working as of #461. The client-driven authentication flow will be implemented in #499. If agreed, please close when ready.
