### ISSUE TITLE
enable non-default string types for AVUs in Python 2 and 3

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#442]
1. improve flexibility for string types in AVU calls; for example, allow `obj.metadata.set( b'1', b'2', b'3')`  in Python3
2. similarly, allow obj.metadata[stringvar] to work even when stringvar is not the default string type , ie a `bytes` in Python3 or `unicode` in Python2.

**Comment by alanking** [comment]
@d-w-moore - Please close if complete
