### ISSUE TITLE
Add functionality to Manage zones

### ISSUE THREAD

**Issue by kript** [irods/python-irodsclient#45]
Missing tick box in the features list in the README that we would use if implemented.

**Comment by adetorcy** [comment]
Feel to reopen this with more specific requirements (or make a new issue) if there are iRODS zone related capabilities that you need in PRC.

**Comment by kript** [comment]
Sorry, that wasn't clear was it! Lets try again;

Using the python iRODS client, I would like to be able to run the equivalent of of `iadmin`

- lz
- mkzone
- modzone
- modzonecollacl
- rmzone

However, this is not a high priority.
