### ISSUE TITLE
tickets supply( )'d to session are not mapped to individual connections

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#455]
1. Basic problem description

Currently, the ticket API within the Python iRODS Client  enables the ticket for only one connection, the one happening to be popped from the idle pool (or newly created, if there is none there) at the time of the `supply( )`  method call. When we later take connections from the session's pool, we are not guaranteed one with a  ticket-enabled status.

A possible way to solve this is to track which cached connections have had ticket enabled for them (assuming one has been supply( )'d for the session). For example, we could keep the connections as keys in a  dictionary-like data structure at the session level.  When peeled off of the idle pool for service, a connection can then get the ticket applied to it if that has not already been done.  Note that if we make the dictionary an instance of `weakref.WeakKeyDictionary`, and conn's are used as keys, then whenever connections get destroyed, those connections will then disappear from the data structure automatically.

2. Another effect of this issue , which we use here to demonstrate it, is:

Since calling cleanup( ) on an iRODSSession object empties the idle and active pools of all cached connections, the result is that no connections henceforth created and used by the session will have the ticket activated.  The `iRODSSession`'s  `cleanup( )`  call is very useful in some applications, and since the ticket is supply( )'d at the session level, one would intuitively assume that subsequently formed connections (which are lower level objects corresponding one-to-one with inet sockets) _should_ inherit it.  However, as noted above,  a ticket that has been `supply( )`'d in the session does not get reapplied any subsequently formed connections after a `cleanup( )`.  Which explains why the in the following demo script outputs the "ticket had no effect".

```
import sys
import irods
import irods.test.helpers as h
from irods.ticket import Ticket
from irods.session import iRODSSession
from irods.exception import CollectionDoesNotExist

t = u = c = None

rodsuser_name = 'alice'
rodsuser_pass = 'upass'

try:
    s = h.make_session()

    # Create a rodsuser with whom ticket will be shared.
    u = s.users.create(rodsuser_name,'rodsuser')
    u.modify('password',rodsuser_pass)

    # Generate a collection and a ticket granting read access to it.
    c = s.collections.create(h.home_collection(s)+"/test")
    t = Ticket(s, ticket = 'mystring').issue('read', c.path)

    # login as the rodsuser
    user_sess = iRODSSession( user = rodsuser_name,
                              password = rodsuser_pass,
                              host = s.host,
                              port = s.port,
                              zone = s.zone )

    # Apply ticket to high-level session object
    Ticket(user_sess,t.ticket).supply()

    # Effectively, remove all of the session's cached connections.
    user_sess.cleanup()

    try:
        user_sess.collections.get(c.path)
    except CollectionDoesNotExist:
        print ('ticket had no effect')
    else:
        print ('it worked')

finally:
    if u: u.remove()
    if t: t.delete()
    if c: c.remove()

```

**Comment by trel** [comment]
I think this can be closed.
