### ISSUE TITLE
`iRODSSession.data_objects.put` does not specify data size

### ISSUE THREAD

**Issue by alanking** [irods/python-irodsclient#462]
The `put` API takes a local file which exists and puts it into iRODS. The file should be stat-able, which means we should be able to convey the size. The file size should be passed along to `open` here (`kw.DATA_SIZE_KW`):
https://github.com/irods/python-irodsclient/blob/bb03bb5bccf650838ae6468e6f90c60325a07997/irods/manager/data_object_manager.py#L157-L162

As it stands, the `open` passes -1 as the data size, which can and does cause problems.

The "parallel" transfer case should be inspected as well.

**Comment by d-w-moore** [comment]
@alanking related to this, is it enough (in your experiments with ingest) to apply the DATA_SIZE_KW in open( )?
I ask because, in the following PRC invocation of open( ):
```
session.data_objects.open('<some_data_path>','w',**{kw.DATA_SIZE_KW:500})
```
The operative string sent to the server is:
```
<MsgHeader_PI><type>RODS_API_REQ</type><msgLen>310</msgLen><errorLen>0</errorLen><bsLen>0</bsLen><intInfo>602</intInfo></MsgHeader_PI><DataObjInp_PI><objPath>/tempZone/home/rods/abc.dat</objPath><createMode>0</createMode><openFlags>577</openFlags><offset>0</offset><dataSize>-1</dataSize><numThreads>0</numThreads><oprType>0</oprType><KeyValPair_PI><ssLen>1</ssLen><keyWord>dataSize</keyWord><svalue>500</svalue></KeyValPair_PI></DataObjInp_PI>
```
So it appears the dataSize is sent twice: once as a direction to set the `dataSize` member of the `dataObjInp_t`, and again as part of the `condInput` in the same structure. Do we know yet which takes precedence?

**Comment by trel** [comment]
oh, very interesting.

**Comment by alanking** [comment]
It still seems to me from inspection of the code that the `dataSize` member of the `dataObjInp_t` is used to initially populate the L1 descriptor, which goes on to populate the `file_object`, which causes the problem described in https://github.com/irods/irods/issues/7154.

So, it is not clear to me when, if ever, the `DATA_SIZE_KW` has an effect in the open API. It certainly takes effect when the data object (or, more precisely, the replica) is registered in the catalog, but I am not sure when it affects the `dataObjInp_t`.

I realize that's not the most helpful answer. :)
