### ISSUE TITLE
keep pip package up to date with git repo

### ISSUE THREAD

**Issue by kript** [irods/python-irodsclient#47]
Following on from the [iRODS chat discussion](https://groups.google.com/forum/#!topic/irod-chat/_Nn1r8BqVJ8), can we keep the pip package up to date with the git repo please? I understand that it may be desirable to keep a release schedule but the pip version is enough behind the curve that if the standard advice is to clone it from the repo, its probably too far out of date!

**Comment by katbeaulieu** [comment]
Yes I was wondering the same thing, if it would be possible to keep the pip package up to date? I am trying to develop a tool that specifies to resource you are saving to which isn't a feature in the old pip package and need to be able to download the api without being prompted for a github username and password.

**Comment by adetorcy** [comment]
Agreed. I have asked the original package owners to grant me permission to push updates.
In the meantime if you need to do a pip install from github without being prompted for github credentials you can try the plain git protocol, as follows:
`pip install git+git://github.com/irods/python-irodsclient.git`

**Comment by adetorcy** [comment]
FYI I have uploaded a release candidate for version 0.5.0:
https://pypi.python.org/pypi/python-irodsclient/0.5.0rc1

**Comment by TD-er** [comment]
You have changed so much in this branch (and I'm happy about that), but it is hard to compare installed versions when we have to clone from the branch and not having a single version number to fetch.
I think it would be nice to have a new version label every now and then.
The latest version has so many improvements, it is hardly comparable with the .5.0 version.

**Comment by adetorcy** [comment]
Sure. I would like to address #69 first, and once it is closed we can make a .6.0 release.

**Comment by kript** [comment]
That would be great, thanks, as I'm looking to use this across our estate and deploying a pip via config management is _much_ easier than managing a git clone across ~70 servers.

**Comment by trel** [comment]
I think we've done this through the latest 0.7.0 - although the process needs to be documented so we can follow through in the future...

**Comment by trel** [comment]
0.8.0 is out - and will keep things up to date moving forward.
