### ISSUE TITLE
Allow loading and saving of library configuration

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#471]
We'd maybe like to optionally be able to save and (auto-)load settings that affect library behavior.

Use case:
When #457 does get merged, we'll already be able to change the data object auto-close feature by adding the lines:
```
import irods.client_configuration as config
config.data_objects.auto_close = True
```
However, in some cases it may be impractical or intrusive to add these lines to all Python scripts within a project that depend on a particular configuration setting.  We may prefer to place the corresponding setting into a configuration file which can be designated as a source for (optionally) auto-loading such settings.  An environment variable could then control whether the PRC is to be run with library defaults (ie, leave the env-variable unset) or loading the altered settings on library import (ie using the settings file at the path specified by the env-variable).

**Comment by trel** [comment]
Please close if complete.
