### ISSUE TITLE
In Python2, #471's settings autoload prints cryptic message if settings file is missing

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#472]
In response to the command
```
PYTHON_IRODSCLIENT_CONFIGURATION_PATH='' python2 -c 'import irods'
```
Pull request #471 under Python2.7 (not Python3) produced a cryptic message if the  settings file doesn't exist at the default path:
```
No handlers could be found for logger "irods.client_configuration"
```

It would be preferable if it instead logged this message (as it does under Python3):
```
Config file not available at: "/home/daniel/.python_irodsclient"
```

This doesn't ordinarily occur for logging calls in the irods module and submodules if the developer calls `logging.basicConfig` at the appropriate times in an application's setup.  So it seems we need to insert this call into the `irods/__init__.py` and additionally protect the logging call in `irods.client_configuration.load( )` by accessing the logger itself via `logging.getLogger`.  See: https://stackoverflow.com/questions/44188270/no-handlers-could-be-found-for-logger

**Comment by trel** [comment]
If this is easy to remedy, please go for it.    If it is not, this issue can be one of the first candidates for a Python3-only PRC release.

**Comment by d-w-moore** [comment]
> If this is easy to remedy, please go for it. If it is not, this issue can be one of the first candidates for a Python3-only PRC release.

A commit has now been added in #457 to address this : )

**Comment by trel** [comment]
Please close if complete.
