### ISSUE TITLE
add Quota model

### ISSUE THREAD

**Issue by trel** [irods/python-irodsclient#474]
In trying to retrieve the equivalent information as this GenQuery from PRC...

```
$ iquest "select QUOTA_USER_NAME, QUOTA_USER_ZONE, QUOTA_LIMIT, QUOTA_OVER"
QUOTA_USER_NAME = quota_group_for_alice
QUOTA_USER_ZONE = tempZone
QUOTA_LIMIT = 20401094656
QUOTA_OVER = -20389538199
```

I realized these columns are not yet supported / available.

We should make these available.

Separately, we should consider a generic GenQuery operator that just takes a querystring.  This would allow an escape hatch for models that are not directly implemented in PRC.  This could be turned into a new issue itself.

**Comment by korydraughn** [comment]
> Separately, we should consider a generic GenQuery operator that just takes a querystring. This would allow an escape hatch for models that are not directly implemented in PRC. This could be turned into a new issue itself

Definitely. GenQuery2 only accepts query strings so that aligns perfectly.

**Comment by d-w-moore** [comment]
Do we also wish for PRC to be able to set up quotas in the manner of `iadmin` ?

**Comment by trel** [comment]
Yes.  Please create a new issue for that.

**Comment by alanking** [comment]
Created https://github.com/irods/python-irodsclient/issues/479 for managing quotas.

**Comment by alanking** [comment]
Do we need to add a bit to the README about the new quota things?

**Comment by alanking** [comment]
Created https://github.com/irods/python-irodsclient/issues/484 for README effort.
