### ISSUE TITLE
Add quota management capability (a la `iadmin sgq`)

### ISSUE THREAD

**Issue by alanking** [irods/python-irodsclient#479]
As suggested here: https://github.com/irods/python-irodsclient/issues/474#issuecomment-1781849391

**Comment by alanking** [comment]
I know this has been discussed but just wanted to put it in writing somewhere...

User quotas were removed in 4.3.0: https://github.com/irods/irods/issues/4481. Do we want to add the ability to set user quotas to something other than 0 in order to support PRC talking to 4.2.x servers, which still have/use user quotas?

**Comment by korydraughn** [comment]
We could support user quotas, but I don't think we should. By not supporting them, we force people to start thinking about migrating from 4.2 to 4.3. However, we also want to give people time to plan.

With that said, I think we have to introduce a new branch to distinguish 1.x and 2.x (or 3.x) implementations.

**Comment by d-w-moore** [comment]
> I know this has been discussed but just wanted to put it in writing somewhere...
> 
> User quotas were removed in 4.3.0: [irods/irods#4481](https://github.com/irods/irods/issues/4481). Do we want to add the ability to set user quotas to something other than 0 in order to support PRC talking to 4.2.x servers, which still have/use user quotas?

That is perhaps a good idea. There are still a few of those out there ....

**Comment by d-w-moore** [comment]
> We could support user quotas, but I don't think we should. By not supporting them, we force people to start thinking about migrating from 4.2 to 4.3. However, we also want to give people time to plan.
> 
> With that said, I think we have to introduce a new branch to distinguish 1.x and 2.x (or 3.x) implementations.

So we should allow the user quotas only on the 2.x branch, yes?  3.x should be Python3 only and not cater to past features like 4.2.x user quotas (Just to make sure I'm getting the correct sense of your suggestion : ) )

**Comment by korydraughn** [comment]
User quotas would be allowed on the 1.x branch. We haven't determined what the next major version is yet, but 2.x and 3.x are candidates (since support for Python 2 would be dropped).

**Comment by d-w-moore** [comment]
> User quotas would be allowed on the 1.x branch. We haven't determined what the next major version is yet, but 2.x and 3.x are candidates (since support for Python 2 would be dropped).

Oh, got it. Of course. (1/2/3).x refers to major PRC version.
