### ISSUE TITLE
Make version of PRC available as tuple

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#483]
`irods.__version__` gives the current python-irodsclient version as a string (like `'1.1.9'`) but it's conceivable we might want to compare versions at some point.  tuples provide this facility more directly.  With session.server_version( ) already yields a tuple [for example:  `(4,2,12) < (4,3)`] , and we use this for testing: ie skip a test if not running against at least a 4.3.x server.  

With this feature we could have: if ` irods.version_as_tuple( )` yield (1, 1, 9) for PRC v1.1.9, serving a similar purpose, either for future internal use or by applications leveraging PRC

**Comment by alanking** [comment]
@d-w-moore - Please close if complete.
