### ISSUE TITLE
allow individual settings overrides using environment variables

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#489]
A variable  like, for instance:
```
PYTHON_IRODSCLIENT_CONFIG__DATA_OBJECTS__AUTO_CLOSE
```
could be used to override the value of:
```
data_objects.auto_close
```

**Comment by d-w-moore** [comment]
The most likely (or sole) application of this would be during (actually just following) autoload of the settings file.

**Comment by korydraughn** [comment]
You're saying environment variables should override options in the settings file?

**Comment by d-w-moore** [comment]
Yes

**Comment by d-w-moore** [comment]
> You're saying environment variables should override options in the settings file?

Yep, I'm thinking of it as a line-item tweak capability, if/when necessary. I could imagine it being needed in rare cases.

**Comment by korydraughn** [comment]
That makes sense.

The settings file becomes the common way to configure things and environment variables give users a way to quickly override things if absolutely needed.
