### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by katbeaulieu** [irods/python-irodsclient#49]
Would it be possible to implement the use of API keys with the python-irodsclient? Would it be very difficult to implement? The only reason I ask is because it makes it a lot easier to authenticate in irods when using it with third party applications, than using plain text passwords.

**Comment by adetorcy** [comment]
In addition to the native password based challenge-response authentication, iRODS supports PAM, Kerberos and GSI. There have been requests to add Kerberos (#34) and PAM (#8) authentication to PRC so these two are the most likely to be implemented next, once iRODS 4.2 is out.

**Comment by muccix** [comment]
Will GSI authentication be supported?
Shall I open an issue for this?

**Comment by adetorcy** [comment]
#56
