### ISSUE TITLE
Support opening data_objects in append mode

### ISSUE THREAD

**Issue by hechth** [irods/python-irodsclient#495]
Currenty, even if a data object is oppenend with 'a' in the mode, it doesn!t seek the end before returnng the file

**Comment by trel** [comment]
Can you provide example code that is not working for you?

**Comment by d-w-moore** [comment]
@trel @hechth Confirmed this is needed.  I had thought that pyfilesystem did its own seek, but (more sensibly) it relies on the underlying object to implement correctly.  I've run it through with pyfilesystem and the changes in https://github.com/d-w-moore/python-irodsclient/tree/495.m, and that seems to correct it. 

The basic problem is: ses.data_objects.open('aa.dat','a').write(b'_') should always extend the length of the object by seeking to the end automatically, and it doesn't.  Instead, it's writing always at offset 0.

Which is a general problem needing a fix.

**Comment by trel** [comment]
okay, nice - we need a test to capture this new behavior, both in the positive and negative.

**Comment by trel** [comment]
i see the branch linked above and it has three commits, just need the PR created...

**Comment by d-w-moore** [comment]
> i see the branch linked above and it has three commits, just need the PR created...

Now created: #516

**Comment by hechth** [comment]
@d-w-moore and @trel thanks a lot!
