### ISSUE TITLE
readme should recommend/use trim() for repl_and_trim example

### ISSUE THREAD

**Issue by trel** [irods/python-irodsclient#504]
We should use the safer `trim()` in this `repl_and_trim()` example.

https://github.com/irods/python-irodsclient/blob/708425e85ac652a362efa225ae0cfc2fa47b57e1/README.rst#L1159

**Comment by d-w-moore** [comment]
Yep. and, wow, that's not even the right option to specify replica number; should be REPL_NUM_KW
