### ISSUE TITLE
add query filter mode "like"

### ISSUE THREAD

**Issue by carsten-jahn** [irods/python-irodsclient#51]
please add a "like" mode to the comparison types in column.py (or, if it works out of the box somehow, please add a test case example on how to use it)

**Comment by adetorcy** [comment]
To be able to use `like` like the other comparison operators we would need to hack it (something like [this](http://code.activestate.com/recipes/384122/)), or we could overload one of the standard operators but none of them seems like a natural candidate for this. I think it's much cleaner to create a criterion on the fly, as in the above example.

**Comment by carsten-jahn** [comment]
thanks!
