### ISSUE TITLE
`Connection.__init__` no longer raises iRODS error code exceptions

### ISSUE THREAD

**Issue by alanking** [irods/python-irodsclient#518]
In the past, instantiating a `Connection` object with invalid credentials for authentication would result in an iRODS error code being `raise`d (e.g. `PAM_AUTH_PASSWORD_FAILED` or `CAT_INVALID_USER`). Now, any failed authentication causes `ValueError` to be `raise`d and the "reason" for the failed authentication is lost.

The relevant code change can be found here: https://github.com/irods/python-irodsclient/commit/89566449364673ecee3ae53d871088204a396500#diff-65db2a2628890f6590ada70f47840fedb056dec02a3e0e61e27a339bea7514d2R80-R89

I'm using the bug label, but this may be intentional and we should write down why this change has occurred if it is expected.

**Comment by d-w-moore** [comment]
If there were a valid reason for masking the original server-given exception types and codes, it might be to add some consistency to the client interface, as @alanking noted in e-mail discussions today.  We should discuss the pros and cons of that here, perhaps, but I'll just note that perhaps we should then:
  - wait for the Python3-only future
  - use the raise-from syntax to transform those errors into something "more consistent"
  - use an Exception type other than `ValueError` as our error indicator; it's too broad, though probably appropriate in the original usage to identify an invalid scheme [here](https://github.com/irods/python-irodsclient/blob/9c3958a0df35dbf35847af214b0ba32bc0bd61b2/irods/connection.py#L75).

**Comment by alanking** [comment]
I created https://github.com/irods/python-irodsclient/issues/545 for considering how to make the errors more uniform.
