### ISSUE TITLE
Change of pam to pam_password for iRODS 4.3 should be clearer

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#521]
People can easily find their python-irodsclient scripts and environments non-working on the upgrade path to iRODS 4.3
...
So, in response to #520 and to forestall future confusion, we probably need to both:
   1) make the error message more revealing of the truth than in this example:
```
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'irods.auth.pam'
```
  2) refine documentation so that the transition to use of pam_password in 4.3.x is now the only valid choice,  "pam" being obsolete.

**Comment by sameyley** [comment]
I would add that for iRODS >= 4.3, but python-irodsclient < 2.0.0, "pam" still works.

**Comment by korydraughn** [comment]
@d-w-moore Should this be part of the 2.0.1 or 2.1.0 milestone?

**Comment by d-w-moore** [comment]
> @d-w-moore Should this be part of the 2.0.1 or 2.1.0 milestone?

I think we can do this pretty easily for 2.0.1.  Let's plan it that way, anyway : )

**Comment by alanking** [comment]
@d-w-moore - Please close if complete. Thanks
