### ISSUE TITLE
Add support for GenQuery2 API

### ISSUE THREAD

**Issue by korydraughn** [irods/python-irodsclient#535]
See https://github.com/irods/irods/blob/3af66900a0189690deaece96d61f26a52b6c3f7b/lib/api/include/irods/genquery2.h

**Comment by trel** [comment]
I think it's easier to just hand a string to the server... but not sure how 'Pythonic' that is...

Can we start with 'just hand a string', and then... see how it feels?

**Comment by d-w-moore** [comment]
> I think it's easier to just hand a string to the server... but not sure how 'Pythonic' that is...
> 
> Can we start with 'just hand a string', and then... see how it feels?

That would be the first and simplest thing.  I'm not a fan of the current serialization to XML, or at least would try and simplify it for sanity's sake if we had to do it again.  But the XML does have the advantage that we wouldn't have to rely on complex escaping mechanisms when there are quotes or  other special characters to be dealt with.

**Comment by korydraughn** [comment]
Make it take a string. The actual API requires strings so there's no point in mixing it with the GenQuery1 facilities.

**Comment by alanking** [comment]
I think we did it. Anything else to do here, @korydraughn?

**Comment by korydraughn** [comment]
We're all good here. Closing.
