### ISSUE TITLE
Document auxiliary test script setupssl.py

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#537]
Consider reserving `-h` for printing the help text. Or add a few lines to the README explaining how to view the help text.

_Originally posted by @korydraughn in https://github.com/irods/python-irodsclient/pull/527#discussion_r1562522032_

**Comment by alanking** [comment]
I don't think `-h` is reserved for printing help text in any standard (counter-example: `df -h`). Plus, `-h` as an option for a hostname parameter has precedent in `docker run` and possibly other well-known programs.

The `setupssl.py` script already has a line saying how to view the help text: https://github.com/irods/python-irodsclient/blob/0c9600e898b33e184c97f1dfc219375074e201a0/irods/test/setupssl.py#L86

So, what is this issue about?

**Comment by trel** [comment]
https://github.com/irods/python-irodsclient/blob/0c9600e898b33e184c97f1dfc219375074e201a0/irods/test/setupssl.py#L81

Since we already appear to have a collision, then... we use `--help` as well as 'any invalid option' if that is easily supported with getopt.

We should move to argparse in 3.0 as well... (https://github.com/irods/python-irodsclient/issues/598)

**Comment by korydraughn** [comment]
> So, what is this issue about?

It was about `-h` being reserved for displaying help text.

That comment stemmed from the fact that when I want to see help text for a command, I always attempt to use `-h`. Of course, we don't have to standardize on that.

> Since we already appear to have a collision, then... we use `--help` as well as 'any invalid option' if that is easily supported with getopt.

I agree.

**Comment by trel** [comment]
if getopt allows 'long' options... i think so.

**Comment by trel** [comment]
looks like it ... does.    https://docs.python.org/2.7/library/getopt.html
