### ISSUE TITLE
(in iRODS 4.3.2) an iRODSGroup cannot be removed 

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#539]
as of iRODS 4.3.2 (specifically [the #7380 fix ](https://github.com/irods/irods/commit/39f1d92e18dd9bc5ea5e03db4276a7d2355200c7)) v2.0.0 can no longer remove groups due to the new differentiation required in the user/group parameter, in the `rmgroup` command:
```
>>> g = session.groups.create('mygroup')
>>> g.remove()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/irods/python-irodsclient/irods/user.py", line 93, in remove
    self.manager.remove(self.name)
  File "/var/lib/irods/python-irodsclient/irods/manager/user_manager.py", line 103, in remove
    response = conn.recv()
  File "/var/lib/irods/python-irodsclient/irods/connection.py", line 152, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_INVALID_USER: None
```

The solution needs to allow `session.<MANAGER>.remove(groupName) `with` <MANAGER>` being either `users` or `groups`. It should also function for earlier iRODS servers, ie ["rm","group"] is necessary/appropriate in the **rsGeneralAdmin** `rmgroup` API for iRODS 4.3.2+, but for iRODS 4.3.1 and previous servers, might cause an error . For the older servers, `["rm","user"]` is needed even if the "username" being removed is that of a Group.

**Comment by alanking** [comment]
@d-w-moore - Please close if complete. Thanks!
