### ISSUE TITLE
Have PRC keep the connection open during checksum calculation

### ISSUE THREAD

**Issue by luijs** [irods/python-irodsclient#564]
During transfer of large files(100's of GB's) with checksumming enabled, the PRC can break the connection when the checksum is being calculated. Is there a way for the PRC to see this and make sure the connection stays open?

See https://groups.google.com/g/irod-chat/c/k7Y7UXdXJ5Y for detailed discussion

Regards,

Joris

edit:
To be  a bit more complete, seen with:
irods 4.3.1
Ubuntu 20.04
PRC 2.0.1

**Comment by mstfdkmn** [comment]
To contribute: we had the same or similar issue reported [at](https://github.com/irods/python-irodsclient/issues/377#issuecomment-1467653393) and I supposed this was fixed with [this](https://github.com/irods/python-irodsclient/commit/b17f1e70a1b0351b5577195207198653793f0e19) after https://github.com/irods/python-irodsclient/issues/377#issuecomment-1487986787.

**Comment by korydraughn** [comment]
@luijs Is this the same issue we discussed / worked-out during the UGM troubleshooting session _(i.e. it was fixed by upgrading)_?

**Comment by d-w-moore** [comment]
@luijs - I now have verified from experimentation that a patch from #570 (a fix for #569), along with an assignment to the connection timeout : 
```
s.connection_timeout = None
```
should do the trick of preventing the `NetworkException` during large (eg >=100G) puts with checksum, as also with just calling `session.data_objects.chksum( ...) `on those large objects with the verifyChecksum option enabled.  
So, I'm pretty much ready to close this issue and consider it solved as soon as #570 is merged.  

Please let us know if you have input on this one.

**Comment by alanking** [comment]
Resolved by changes in https://github.com/irods/python-irodsclient/pull/570.
