### ISSUE TITLE
Exception class Bad_AVU_Value should inherit ValueError directly 

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#565]
- `irods.message.Bad_AVU_Value` should be descended from `ValueError` for  `irods.test.meta_test.TestMeta.test_add_obj_meta_empty`  to pass.
 

_Originally posted by @d-w-moore in https://github.com/irods/python-irodsclient/issues/531#issuecomment-2162318604_

**Comment by alanking** [comment]
Is this effort to fix a failing test, or a refactor / enhancement?

**Comment by d-w-moore** [comment]
Yes. Pretty much that, a fix of a failing test.  But it does fit : Bad_AVU_Value should or at least can be considered a type of value error..

**Comment by d-w-moore** [comment]
#588 will include a fix for this.

**Comment by alanking** [comment]
Addressed by changes in https://github.com/irods/python-irodsclient/pull/588.
