### ISSUE TITLE
login_auth_test.py should not be run in full suite

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#566]
`login_auth_test.py` [...] requires specific setups, so shouldn't be run as a matter of course in the PRC suite.  That will be fixed in v2.1.0 (see issue #502. we'll be renaming it to run in a BATS test and that should defeat the pattern matching that causes it to be picked up in the routine run of the full suite).  

_Originally posted by @d-w-moore in https://github.com/irods/python-irodsclient/issues/531#issuecomment-2162318604_

**Comment by alanking** [comment]
This file has been renamed to login_auth_test_must_run_manually.py to prevent it from running with the full suite. #502 will include the effort to turn this into a BATS test, and the BATS tests will be made to run alongside the regular suite of tests in order to prevent regressions.
