### ISSUE TITLE
Running on a terminal, test suite prints reams of logging output to stderr

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#567]
Once run, pool_test.py permanently turns on output of irods.connection logger at a DEBUG level.  To be balanced, it should turn that logger off again.

Alone this mightn't have been a problem, but  because of `propagation` being set to `True` by default,  the RootLogger streamhandler, which outputs Everything passing over the socket to the iRODS server, for each test running after the pool_test.

**Comment by alanking** [comment]
Addressed by changes in https://github.com/irods/python-irodsclient/pull/568.
