### ISSUE TITLE
Admin mode metadata(admin=True) is not honored for apply_atomic_operations

### ISSUE THREAD

**Issue by paulborgermans** [irods/python-irodsclient#576]
- [x] code change
- [x] test

---

While implementing some workflows with bulk operations on metadata, we noticed that Admin mode is not working for atomic metadata operations. 

The admin_mode parameter is actually not sent in the json message
PR that fixes it for us follows

**Comment by paulborgermans** [comment]
PR: https://github.com/irods/python-irodsclient/pull/577

**Comment by alanking** [comment]
Thanks, @paulborgermans and @d-w-moore!
