### ISSUE TITLE
test helper function unique_name(...) broken for Python >=3.11

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#587]
This function tries to hand its argument tuple directly to the `random` module for use as a random seed.

The bottom line is: The ability to feed the `random.seed` method a `tuple`-type argument was deprecated in Python 3.9 and removed in Python 3.11, so that now only primitive types such as `str` and `int` are permissible as arguments  In the most recent versions of Python, one must instead perform the step of  hashing the tuple argument first, and then feed the resulting integer to the `random.seed` function.

Demonstration:
```python
Python 3.11.9 (main, May 14 2024, 08:04:54) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import random
>>> t=(3,4)
>>> random.seed(t)   # --> this was fine in Python 3.8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/random.py", line 160, in seed
    raise TypeError('The only supported seed types are: None,\n'
TypeError: The only supported seed types are: None,
int, float, str, bytes, and bytearray.
>>> random.seed( hash(t) )
>>> 

```

**Comment by alanking** [comment]
Addressed by changes in https://github.com/irods/python-irodsclient/pull/588.
