### ISSUE TITLE
Run formatter on entire project

### ISSUE THREAD

**Issue by alanking** [irods/python-irodsclient#615]
We have used Black formatter for the automated ingest repo: https://github.com/irods/irods_capability_automated_ingest/pull/179/commits/a4f4f51235283aadd9abe78a7c1e9e370633ae59

Ruff looks promising: https://github.com/astral-sh/ruff

Other options are welcome for consideration.

**Comment by d-w-moore** [comment]
Let's keep this for v3.0.0 but make it the last commit applied broadly to the Python source.

**Comment by alanking** [comment]
Another data point for Ruff (linter) and Black (formatter): https://github.com/irods/irods_testing_environment/pull/234

**Comment by alanking** [comment]
Done in #677
