### ISSUE TITLE
`imcoll` mounted collection are not seen by the python client

### ISSUE THREAD

**Issue by glyg** [irods/python-irodsclient#618]
Hi!

We have a setup with a local iRODS server (and storage resource localResc) we use as a buffer or staging server,  before we synchronize the data on the central resource

We "ingest" data by running 

```sh
imcoll -m filesystem -R localResc /path/on/local/server/collection /tempZone/home/user/collection
```

After this, we can list the content of the collection with `ils` on the icat server, but `session.collections.exists("/tempZone/home/user/collection")` returns `False` 

Is this a known limitation of `imcoll`? 

Thanks for any pointers :)

Best,

Guillaume

cc @technics3

**Comment by glyg** [comment]
Ok we missed that part of the `imcoll` doc

> Only the top level collection/directory will be registered.

And indeed our issue is with sub-directories of the mounted collection.

Is there another way to achieve our desired effect, i.e. data put in that directory is automatically registered by irods?

Thanks :)

**Comment by glyg** [comment]
Thanks for the swift answer @d-w-moore !
We started with that (though we copied the files, not just registered them). Now that we know better we'll come back to that

**Comment by trel** [comment]
You could also use `ireg -r`?

https://docs.irods.org/4.3.3/icommands/user/#ireg

But this is a singular event - new/updated/removed items in the 'source' will not be represented/updated in the iRODS catalog after initial registration.

**Comment by glyg** [comment]
yes we're looking into that. As we ask the user for an action (a click) to import data in our system anyway, it might be easier to run `ireg` at that time and not automate it with the ingest tool

**Comment by trel** [comment]
`ireg` has fewer moving parts, but is serial and will block until it returns complete.

The end result 'should' be the same.

**Comment by trel** [comment]
I think we can close this issue as there is nothing to do at this time.

**Comment by d-w-moore** [comment]
> Thanks for the swift answer @d-w-moore ! We started with that (though we copied the files, not just registered them). Now that we know better we'll come back to that

No problem, glad to help!
