### ISSUE TITLE
connection timeouts for iRODSSession have a maximum practical value

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#623]
Beyond a  value of [9223372036.854775](https://stackoverflow.com/questions/45704243/value-of-c-pytime-t-in-python
) seconds - around 290 years - large connection timeouts tend to blow up on actual use.

This is actually more of a Python library or OS-related issue, but it behooves us to handle it in PRC as well. So I propose we hard-limit it at the maximum value and log a warning that this action was taken.

See also [the source issue](https://github.com/UtrechtUniversity/iBridges/issues/263) for this one.

**Comment by trel** [comment]
it's such a long time... let's just pick an int that is 290 years (or less)... and be done with it.    that's not a reasonable value for a session anyway, so we're just protecting users of the library.

**Comment by alanking** [comment]
@d-w-moore - Please close if complete. Thanks
