### ISSUE TITLE
Replica information

### ISSUE THREAD

**Issue by kript** [irods/python-irodsclient#63]
Apologies if I've missed this, but is it possible to access replica details of an object? 
I'm thinking an analog of `ils -L`

This would be very helpful when you need to target a particular replica (in my use case, by replica ID, place in the compound resource tree (happy to parse that myself if required), or data_path) of an object.

**Comment by adetorcy** [comment]
An iRODSDataObject has a list of its replicas, sorted by replica number. See https://github.com/irods/python-irodsclient/blob/v0.5.0/irods/data_object.py#L35-L40

You can do:
```python
        for replica in obj.replicas:
            print replica.resource_name
            print replica.path
            print replica.status
```

Is this what you need?

**Comment by kript** [comment]
spot on, thank you. Could that example be added to the sample code on the README?
