### ISSUE TITLE
check for preexisting PAM credentials in .irodsA before overwriting

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#635]
In issue #621, the free function `write_pam_credentials_to_secrets_file` is created to provide iinit-like capability for writing a .irodsA containing PAM credentials.  However, unlike iinit, this function's use might be insensitive to, and destroy, a pre-existing .irodsA file.

So, we need to examine this.  At the very least, we could add an option to the function, specifying whether an already existing `.irodsA` should be checked for , prior to negotiating a new PAM password and overwriting the existing `.irodsA`.

**Comment by alanking** [comment]
@d-w-moore - Please close if complete. Thanks
