### ISSUE TITLE
Wrong name for CollectionMeta id

### ISSUE THREAD

**Issue by mstfdkmn** [irods/python-irodsclient#642]
It seems like there’s a minor issue with the column ID name in the following lines.

https://github.com/irods/python-irodsclient/blob/main/irods/models.py#L144 (should be COL_META_COLL_ATTR_ID)  and L154 (COL_META_RESC_ATTR_ID)

**Comment by korydraughn** [comment]
Nice catch. We'll get that fixed for the next release.

**Comment by trel** [comment]
11.5 year old bug!

https://github.com/irods/python-irodsclient/commit/e931fabfb1ee67b97ba860ba903c2a2b2c0dc1f9

**Comment by korydraughn** [comment]
The following lines:
https://github.com/irods/python-irodsclient/blob/f2394e01fa9194741776258fed771c0842f07192/irods/models.py#L144
https://github.com/irods/python-irodsclient/blob/f2394e01fa9194741776258fed771c0842f07192/irods/models.py#L154

should be:
```diff
-   id = Column(String, 'COL_META_COLL_ATTR_UNITS', 613)
+   id = Column(String, 'COL_META_COLL_ATTR_ID', 613)
```
```diff
-   id = Column(String, 'COL_META_RESC_ATTR_UNITS', 633)
+   id = Column(String, 'COL_META_RESC_ATTR_ID', 633)
```

**Comment by trel** [comment]
And we'll need a test to validate these (and perhaps others).

**Comment by d-w-moore** [comment]
That's a good catch.  I'm not convinced there's an easy way to test, though, unless we assert its compabitility with other clients (like `imeta`).

**Comment by d-w-moore** [comment]
Oh . i see, not a swap of two fields in the same row, but different tables. Wow, how did we not catch it before?

**Comment by trel** [comment]
Nobody's used that field in their own code before.

**Comment by d-w-moore** [comment]
Ok.  And I see that we can test by extracting the dict keys from query results labelled with COL_META_COLL_ATTR_UNITS  to make sure they (all) have an icat_id of 612

**Comment by d-w-moore** [comment]
```
$ python meta_coll_query.py 
[{<irods.column.Column 615 COL_META_COLL_MODIFY_TIME>: datetime.datetime(2024, 10, 21, 14, 17, 33),
  <irods.column.Column 614 COL_META_COLL_CREATE_TIME>: datetime.datetime(2024, 10, 21, 14, 17, 33),
  <irods.column.Column 612 COL_META_COLL_ATTR_UNITS>: 'c',
  <irods.column.Column 611 COL_META_COLL_ATTR_VALUE>: 'b',
  <irods.column.Column 610 COL_META_COLL_ATTR_NAME>: 'a',
  <irods.column.Column 613 COL_META_COLL_ATTR_UNITS>: '28000'}]
```
source:
```
#!/usr/bin/python3
from irods.models import CollectionMeta
from irods.helpers import make_session
s = make_session()
a = list(s.query(CollectionMeta))
import pprint
pprint.pprint(a)

```

**Comment by d-w-moore** [comment]
Wrote this script as a basis for a test - it compares the loaded columns against a copy of rodsGenQuery.h

```
import re
r=re.compile(r'\s*#\s*define\s\s*(?P<column_name>COL_\w+)\s+(?P<column_value>[0-
9]+)\s*')  
fn = 'rodsGenQuery.h'
l=open(fn,'r').readlines()
column_name_to_integer = dict((m.group('column_name'),m.group('column_value')) f
or m in (r.match(ln) for ln in l) if m)
import irods.models
import pprint
#pprint.pprint(irods.models.ModelBase.columns)
#exit()
for n,col in irods.models.ModelBase.columns.items():
    mne = col.icat_key
    num = col.icat_id

    if n == 0:
        continue
    assert n == num

    num_from_irods_header_lookup = column_name_to_integer[
        'COL_'+mne if not mne.startswith('COL_')
        else mne]

    # The check:
    if num_from_irods_header_lookup == str(num):
        print('y',end='')
    else:
        print(f'\n a column named {mne} had {num} instead of '
              f'{num_from_irods_header_lookup}')

```

Ran it a couple times, found some things 
```
$ (cd ~;python check_column_numeric_keys_against_header.py )
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
 a column named COL_META_COLL_ATTR_UNITS had 613 instead of 612
yyyyy
 a column named COL_META_RESC_ATTR_UNITS had 633 instead of 632
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyTraceback (most recent call last):
  File "./tmp.py", line 20, in <module>
    else mne]
KeyError: 'COL_TICKET_ALLOWED_USER'
```

This turned up not just a wrongly assigned UNITS fields from issue 642 but also some misnamed column names `COL_TICKET_ALLOWED_USER` and  `COL_TICKET_ALLOWED_GROUP` (both need _NAME appended to the end).

**Comment by d-w-moore** [comment]
Ran it with those corrections and got all "y" (the scirpts code for "yes", or "checks out".)
Sorry for the cryptic output.  But it will all be converted to a test function anyway...

**Comment by trel** [comment]
nice.    so we'll see a diff and can decide if those other two are what we want.     good find.
