### ISSUE TITLE
Possible PAM Authentication failure on iRODS 4.2.11

### ISSUE THREAD

**Issue by iychoi** [irods/python-irodsclient#649]
I introduced special characters escaping in PAM passwords to go-irodsclient and gocommands after I found the code in python-irodsclient (676b1f808058fb1c2c4c16872c86719285fc6cd0). 

PAM authentication worked very well with iRODS >= 4.3, however, it did not work with iRODS 4.2.11. 
Especially when there is a special character `@` in PAM password, it failed. It worked when I disabled the escaping. 

I believe python-irodsclient may have the same issue although I did not test.

The problematic line is at 497 of connection.py.

https://github.com/irods/python-irodsclient/blob/main/irods/connection.py#L497

The `pamPassword` parameter should be `self.account.password` to avoid the issue.

**Comment by d-w-moore** [comment]
@iychoi Should I be reading in this, that `@` doesn't need escaping in 4.2.11, but maybe does in 4.3+ ? 
Guess I need to run my testing again and  possibly re-design to be more thorough.

**Comment by iychoi** [comment]
Because of the line below, iRODS 4.3.0 will not fall into the _login_pam().
https://github.com/irods/python-irodsclient/blob/main/irods/connection.py#L69

For iRODS servers < 4.3, I believe special characters ("@", "=", "&", ";") should not be escaped when using PamAuthRequest.

**Comment by d-w-moore** [comment]
> Because of the line below, iRODS 4.3.0 will not fall into the _login_pam(). https://github.com/irods/python-irodsclient/blob/main/irods/connection.py#L69
> 

It should still get into _login_pam() via  [this line](https://github.com/irods/python-irodsclient/blob/5c1ba1e1051a11a22b517c1008e10fd817b943f2/irods/auth/pam_password.py#L2)

> For iRODS servers < 4.3, I believe special characters ("@", "=", "&", ";") should not be escaped when using PamAuthRequest.

Will look into that... thanks!

**Comment by iychoi** [comment]
>> Because of the line below, iRODS 4.3.0 will not fall into the _login_pam(). https://github.com/irods/python-irodsclient/blob/main/irods/connection.py#L69
>
>For versions of iRODS >= 4.3.0 we should still get into _login_pam() via [this line](https://github.com/irods/python-irodsclient/blob/5c1ba1e1051a11a22b517c1008e10fd817b943f2/irods/auth/pam_password.py#L2)

I didn't know that. Then, I believe special characters should not be escaped with using PamAuthRequest regardless of iRODS server versions.
I only tested and confirmed that "@" should not be escaped. "&" and ";" may need to be escaped as they are parsed by XML parser.

**Comment by iychoi** [comment]
I confirm that all of these characters "@=&;" should not be escaped for iRODS < 4.3. I tested with an account that has all these 4 special characters in the password and it worked when they are not escaped.

**Comment by alanking** [comment]
This issue has been addressed (alongside #650) in this commit: https://github.com/irods/python-irodsclient/commit/f4ef3a12716441619db186ddf156ebe4510de859 Closing.
