### ISSUE TITLE
Un-fork this forked repo

### ISSUE THREAD

**Issue by c-mart** [irods/python-irodsclient#66]
It appears we're in a situation where a fork (irods/python-irodsclient) has now become "upstream", and the original upstream repo (iplantcollaborativeopensource/python-irodsclient) is no longer maintained. Aside from being unintuitive, this is a usability issue as github.com doesn't let users search the code inside a fork.

I suggest the maintainers do something [like this](https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting). Also, perhaps iplantcollaborativeopensource/python-irodsclient should be deprecated if it's no longer maintained; I can help with this on our end.

**Comment by adetorcy** [comment]
Agreed. We will look into this and be in touch. Thank you.

**Comment by adetorcy** [comment]
Done
