### ISSUE TITLE
some pam-login-based test scripts not working for iRODS 4.2

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#665]
Two test scripts were failing for the authentication scheme of "pam" because of an inflexible Bash statement asserting a match against "pam_password":
```
test003_write_pam_credentials_to_secrets_file.bats
test004_prc_pam_password_internal_secrets_file_generation.bats
```

**Comment by alanking** [comment]
@d-w-moore - Please close if complete. Thanks

**Comment by d-w-moore** [comment]
ah...  need to correct test004 before closing.

**Comment by alanking** [comment]
Good catch.
