### ISSUE TITLE
Allows data insert when quota exceeded

### ISSUE THREAD

**Issue by keithj** [irods/python-irodsclient#68]
iRODS icommands and server 4.1.10

python-irodsclient built from https://github.com/irods/python-irodsclient/commit/f48f0fe714fb22838879e11e05aeed8047e64183

In circumstances where I have exceeded my quota (`iput` is failing with its normal quota exceeded error), I can still insert apparently unlimited GiB of data using the Python API (driven by the Python ingest tool). I'm reporting here because I suspect that it is an iRODS issue that clients can avoid quota.

**Comment by kellerb** [comment]
I have made an issue in the main iRODS repository for this:

https://github.com/irods/irods/issues/3513
