### ISSUE TITLE
use .irods files if present

### ISSUE THREAD

**Issue by kript** [irods/python-irodsclient#71]
At present, the code requires providing the irods environment and authentication information, such as username, password etc. 
As this often exists within the `~/.irods/irods_environment.json` and `~/.irods/irodsA` files, it would be helpful if those were sources first and the values could be overwritten if required, or a function provided to import them.

**Comment by adetorcy** [comment]
Example usage:

```python
try:
    env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
    env_file = os.path.expanduser('~/.irods/irods_environment.json')

with iRODSSession(irods_env_file=env_file) as session:
    #do stuff
    pass
```

**Comment by kript** [comment]
Awesome, thank you. I see it does the password, too! 
Is there any chance we can get it rolled into a pip release as @TD-er suggests in #47

**Comment by adetorcy** [comment]
Yes certainly. There will be a .6.0 release shortly.
