### ISSUE TITLE
Support for iRODS tickets for access control

### ISSUE THREAD

**Issue by alexlemann** [irods/python-irodsclient#74]
See the relevant documentation for the [overall tickets documents](https://docs.irods.org/4.2.0/system_overview/users_and_permissions/#tickets-guest-access) and the [iticket](https://docs.irods.org/4.1.1/icommands/tickets/) command.

> Users are able to create tickets and associate them (one to one) with a Data Object or Collection. [...] Users are able to access Data Objects or Collections using tickets even if they do not have regular access permissions

Is there any plan to support these features in the Python bindings? Either generation, use for login, or both?

**Comment by adetorcy** [comment]
We can definitely start the conversation if hydroshare needs ticket generation and ticket based access.
Looking at the client-side ticket code in iRODS, for the most part this looks like a fairly straightforward addition. I will want to confirm that with some tests though.

**Comment by alexlemann** [comment]
As you can see from the linked Hydroshare ticket, there is some still discussion about how this will be implemented. So, this Issue does not constitute an official Hydroshare team request :). That said, it might help make my argument in the related ticket if it were available.

Either way, this is a place for work towards reaching parity with other iRODS clients and this Github issue can serve to let people who have looked for ticket support in Python vote for it, or chime in.

**Comment by adetorcy** [comment]
I pushed a very raw (and subject to change) first pass at tickets for you to try out.
For example:
- User `rods` creates a ticket giving read access on a file they own:
```bash
iticket create read /tempZone/home/rods/LICENSE.txt qwertyuiop
``` 
- User `foo` uses said ticket to read the file
```python
import sys
from irods.session import iRODSSession
from irods.ticket import Ticket


with iRODSSession(host='icat',
                  port=1247,
                  user='foo',
                  password='foo',
                  zone='tempZone') as session:

    # test object 
    obj_path = '/tempZone/home/rods/LICENSE.txt'
    objs = session.data_objects    

    # options for open/close
    options = None

    # set session ticket
    ticket = Ticket("qwertyuiop")
    ticket.set_for_session(session)

    # read object
    with objs.open(obj_path, 'r', options) as o:
        buf = o.read(2120).decode('utf-8')

    print buf

sys.exit(0)
```

**Comment by alexlemann** [comment]
@adetorcy Cool! I'll try it out. I can also add this in a branch to [python-irods-cli](https://github.com/alexlemann/python-irods-cli) to help test it out once ticket generation is stubbed out too.

**Comment by adetorcy** [comment]
Updated example:
- User `rods` issues a ticket giving read access on a file they own
```python
import sys
from irods.session import iRODSSession
from irods.ticket import Ticket

with iRODSSession(host='icat',
                  port=1247,
                  user='rods',
                  password='*********',
                  zone='tempZone') as session:
 
    # our test object 
    obj_path = '/tempZone/home/rods/LICENSE.txt'
 
    # create ticket
    ticket = Ticket(session)
    ticket.issue('read', obj_path)
    print ticket.ticket
 
sys.exit(0)
``` 
- User `foo` uses said ticket to read the file
```python
import sys
from irods.session import iRODSSession
from irods.ticket import Ticket

with iRODSSession(host='icat',
                  port=1247,
                  user='foo',
                  password='********',
                  zone='tempZone') as session:

    # our test object 
    obj_path = '/tempZone/home/rods/LICENSE.txt'   

    # use ticket for access
    ticket = Ticket(session, ">xJ}T5%T%_0Q~ig")
    ticket.supply()

    # read object
    with session.data_objects.open(obj_path, 'r') as o:
        buf = o.read(2120).decode('utf-8')
    
    print buf

sys.exit(0)
```

**Comment by adetorcy** [comment]
If you are happy with this so far I will merge those changes into master for increased visibility, but with the expectation that the ticket interface won't be finalized until at least 0.7.0.

**Comment by alvacouch** [comment]
I will give this a try (same project as Alex). I only need ticket-based read and write..... I generate tickets separately......

**Comment by adetorcy** [comment]
Closing this for now. If anyone needs changes to the ticket interface, please reopen.

**Comment by pdonorio** [comment]
Hello, I've tested today the example to create a ticket and ended up with:

```bash
  File "/usr/local/lib/python3.6/dist-packages/irods/ticket.py", line 52, in issue
    response = conn.recv()
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 100, in recv
    raise get_exception_by_code(msg.int_info)
irods.exception.CAT_UNKNOWN_COLLECTION: None
```

Note that the `iticket` icommand on the same server and on the same path works as expected.

Would you help?

Also as a side question: is it possible to list the current existing tickets like `iticket ls` does?
Thank you as usual

**Comment by trel** [comment]
So you're looking to create a ticket for a collection?  Rather than a data object?

**Comment by pdonorio** [comment]
Uhm no sorry, my test is on a data object path like `/tempZone/home/user/test.txt`. 

I can't say why it tells me unknown collection.

**Comment by trel** [comment]
You get that error when the requested path doesn't exist or you don't have permission via the session you've created.

The example above works for creating and using a ticket for a data object
https://github.com/irods/python-irodsclient/issues/74#issuecomment-306313092

**Comment by pdonorio** [comment]
Uhm, still very weird because I've used the same user to create the ticket on the same object from icommands and it works. Maybe I made a mistake somewhere, let me double check.

**Comment by trel** [comment]
Okay, I've created a new issue for listing of tickets from PRC...  https://github.com/irods/python-irodsclient/issues/120
