### ISSUE TITLE
How difficult would it be to expand the client to support changing a user's password?

### ISSUE THREAD

**Issue by jchansen** [irods/python-irodsclient#76]
I noticed changing a user's password is not currently supported. Doing so returns the error "Password modification is not yet supported", per this code:

https://github.com/irods/python-irodsclient/blob/master/irods/manager/user_manager.py#L61-L62

Is there something complex about that command, that requires intentionally looking for it and returning an error, while the other commands fall through to the `GeneralAdminRequest`?

I'm asking because I'd like to use the `python-irodsclient` in a Django server, but changing a user's password is one of the critical commands I need, for which the lack of support is currently preventing me from using the client. The interim approach I'm following involves using Python's `subprocess` module to invoke `iCommands` directly or invoke scripts that invoke `iCommands`. Admittedly not a great solution, but working for the moment.

I'd be willing to submit a PR to add support for changing a user's password, if you can provide guidance on why it's not currently implemented, and how difficult it might be for me to include it, or maybe some pointers on what I should be aware of in attempting to do so.

Is that something you'd be willing to advise on?

**Comment by adetorcy** [comment]
The difference with modifying passwords is you need to _obfuscate_ them. I would look at [password_obfuscation.py](../blob/master/irods/password_obfuscation.py) and use that code to replicate what [ipasswd](https://github.com/irods/irods_client_icommands/blob/master/src/ipasswd.cpp) does.
I can look into that sometime next week. It should be a quick addition. Of course you are also welcome to submit a PR (if you do please include unit tests for any new functionality).

**Comment by jchansen** [comment]
Thanks @adetorcy! The guidance is much appreciated. I don't know if I'll get to it today, but should be able to start on the PR tomorrow, and will look at the existing tests for the format to follow.

**Comment by jchansen** [comment]
Hi @adetorcy. I think this task has defeated me : (

The obfuscation process might be a bit too obscure for me to follow. I spent about 7 hours on it, but at this point I have very little confidence I'll ever figure it out, and since the generated value changes every time, and is dependent on a timestamp and the id of the process executing the code, I can't write a test and compare it to a "known true value" generated by iCommands (or the knowledge to do so is currently beyond me). And given how complex the process is, and how much uncertainty I have about many areas of it after investigating and trying some things out (unsuccessfully), I have very low confidence I'll actually figure it out.

**Since you think it would be a quick addition, is this something you could help with?** The key thing we need to use the `irods-pythonclient` for is creating iRODS accounts for new users, so the ability to set a user's password is a critical feature. Currently (as mentioned above) we're having Python execute shell scripts, but the error handling is proving to be problematic in production, and it's comparatively difficult to isolate errors and figure out where they came from (compared to the very clear errors I can get from try/except statements in the `irods-pythonclient` like `CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME`).

### Notes on What I Tried
Some notes, to provide context for what I learned and tried, if it's helpful:

I traced the CPP code for `iadmin moduser <username> password <password>` in iCommands that you linked to, and found that it appends a random character string to the beginning of the password, and that the same random character string must be present on the server as well (though I didn't see that string in the CPP code for iRODS itself).

Then I saw it extracts a client side session signature, that is sent by the server and stays constant for that connection (but changes on every connection). I couldn't see a way to get that from within the Python client though.

The `iadmin` commands seems to authenticate the request (to provide administrative permission for the action) by generating a key using a combination of the **"random character string + admin password + `\0` + the client side session signature"**. Assuming I _could_ figure out how to get the session signature, my understanding of Python is fuzzy enough that I'm not sure if it automatically inserts null characters, or if I need to "drop down" into the lower level details to do it. Finally it performs an MD5 hash on that result.

Next the password seems to be modified to equal a **"random value (based on the current time) + a prefix like "A.ObfV2" + the actual password for the user"**, which is then encoded to become the password sent to the server.

Regarding the encoding, the CPP code and the Python method (from `password_obfuscation.encode`) reads different enough that combined with my ignorance and general fuzziness of what Python does at a lower level, I can't be confident the code does the same thing (though I assume it does).

Somewhere in there I think it also gets the process ID and uses that in the encoding scheme, but I can't find where that was in my notes.

After a number of failed attempts, I decided to admit I was drowning and gave up : )

### Simplest Approach I Tried
The simplest approach I tried (first, before diving into the CPP code) was simply using the `password_obfuscation.encode` method directly, but that didn't work, so that's when I started parsing the CPP code to see what else I needed to do. This was the code I tried out (where I removed the code that threw the exception when trying to execute `iadmin moduser <username> password <password>` from within the python client code.

```python
from irods.session import iRODSSession
from irods.password_obfuscation import encode, decode, scramble, unscramble

session = iRODSSession(
    host='irods.example.com',
    port=1247,
    user='admin_username',
    password='admin_password',
    zone='the_zone'
)

new_user_name = "test_user"
new_user_type = "rodsuser"
new_user_password = "password123"

// create the test user
user = session.users.create(new_user_name, new_user_type)

// encode user password
encoded_password = encode(new_user_password)

// set the password
sess.users.modify(new_user_name, 'password', encoded_password)

new_user_session = session = iRODSSession(
    host='irods.example.com',
    port=1247,
    user=new_user_name,
    password=new_user_password,
    zone='the_zone'
)

collection = new_user_session.collections.get("/the_zone/home/test_user")
```

But that code throws the exception `CAT_INVALID_AUTHENTICATION`, so I'm clearly not sending the correct password to iRODS when I set it.

**Comment by adetorcy** [comment]
Thanks for looking into this and sorry that got you stuck. I have a few other things on my plate at the moment but I will try to pick that up sometime in the beginning of July. I'll update this issue.

**Comment by jchansen** [comment]
@adetorcy thanks! Much appreciated. In the meantime, I'll work on integrating the client into our app in the places we can use it.

**Comment by adetorcy** [comment]
Feel free to try this if you get a chance. In terms of code it wasn't that big of a change, but it took a lot of trial and error to get it right so I can see why you got stuck.

**Comment by jchansen** [comment]
@adetorcy that works great! Thank you so much :D This will make my life much easier, and our code simpler and more reliable.

I'll start pulling the package from GitHub directly, and then switch back to pypi when it's published.

Feel free to close this issue if you'd like. I consider it resolved.

**Comment by adetorcy** [comment]
Great, thanks! I have been observing an intermittent password encoding error with iRODS 4.2.1 in CI so it looks like I still have a bit more work to do until I can close this...
