### ISSUE TITLE
session.data_objects.get() raises a CollectionDoesNotExist exception

### ISSUE THREAD

**Issue by alexlemann** [irods/python-irodsclient#77]
Given a structure:
```
/collection1/subcollection1/
/collection1/subcollection2/data_object.txt
/collection1/subcollection3/
```
Given a typo in the subcollection which adds a zero while trying to access the data object:
 ``session.data_objects.get('/collection1/subcollection20/data_object.txt')`` 
a ``CollectionDoesNotExist`` exception is raised because the parent collection cannot be found before looking for the data_object. This is unintuitive to me because while, I have asked for a data_object, the error reported is indicating a collection problem.

Maybe this is clear to other folks, but it should at least have clear documentation. See: #46 and #21.

For reference and inspiration, it looks like these exceptions have [changed relatively recently in Python](https://www.python.org/dev/peps/pep-3151/), but typically ``FileNotFoundError`` would be used for both cases.

**Comment by adetorcy** [comment]
I have slightly rearranged the exception hierarchy so that you have a more generic exception to catch if you prefer, e.g:
```python
import irods.exception as ex

try:
    obj = session.data_objects.get('/collection1/subcollection20/data_object.txt')
except ex.DoesNotExist:
    ...
```

**Comment by alexlemann** [comment]
Ah, that's nice that DoesNotExist was already there! This will solve the problem nicely and still captures some more of the subtly of "not there" means.

Looking through this diff just now, I noticed that the two exceptions defined in irods/exceptions.py are imported in one place, but completely unused.

**Comment by adetorcy** [comment]
Fixed, thanks.

**Comment by alexlemann** [comment]
Closing this out. Thanks for the speedy response.
