### ISSUE TITLE
iRODSDataObject.unlink clarification

### ISSUE THREAD

**Issue by haganf** [irods/python-irodsclient#78]
Hi,

First off, thanks for this great python library! I'm re-writing some code that had been using icommands via python subprocess calls and using this has been extremely helpful.

Anyways, I'm trying to remove data emulating an `irm` command and I see in `iRODSCollection` there is a `remove()` option that I believe removes everything including registered objects. My question, for an `iRODSDataObject`, does the `unlink() `work in the same manner as `irm -U </blah/....>` or does it remove the registered object as well? If it doesn't remove registered objects, is that possible? And if not obvious i'm new to irods....

thanks,

-hagan

**Comment by adetorcy** [comment]
Thanks. By default `iRODSDataObject.unlink()` is equivalent to `irm` without options. The object will be moved to the trash.
To force remove objects and collections you can do:
```python
my_collection.remove(recurse=True, force=True)
my_object.unlink(force=True)
```

**Comment by haganf** [comment]
Thanks Antoine! That answers my question....
