### ISSUE TITLE
PAM Auth

### ISSUE THREAD

**Issue by MatthewTurk** [irods/python-irodsclient#8]
Logging in via PAM would be very useful.  I think this will require overriding the `_login` method of connection, and using a different API call and response.

**Comment by kript** [comment]
:+1:

**Comment by burnce** [comment]
Hello,

We would also be very interested in seeing PAM authentication working. In its current state the client is unusable for us.

 Thanks

**Comment by jamespjh** [comment]
Yep, needed here also.

**Comment by jamespjh** [comment]
PS Hello @MatthewTurk

**Comment by mikkonie** [comment]
Hi,

Just wondering, what is the current status of this issue? Are there plans to work on it now that 4.2 is out, as was hinted in the comments of issue #49 ? PAM support would also be very useful in the project we're currently working on in our team.

Thank you in advance for any updates.

**Comment by adetorcy** [comment]
I don't have an estimated date of completion at this point. The first step will be to implement SSL support and then PAM, which will probably be a couple days work with testing.

**Comment by TD-er** [comment]
We are also waiting for PAM support for our project.

**Comment by GregAbram** [comment]
We'd like PAM as well.

**Comment by pdonorio** [comment]
Hello @adetorcy, can I make a contribution to help this move further? It seems that the SSL support is already solved. How may I help? Thank you

**Comment by adetorcy** [comment]
First of all thank you for your multiple contributions. Nobody that I know of is actively working on PAM at  the moment so you are certainly welcome to submit a PR like you did for GSI.

I should let you know that I have accepted a new job unrelated to iRODS and that starting next week I will be much less involved with python-irodsclient. The iRODS Consortium will continue to support this project.

**Comment by pdonorio** [comment]
> First of all thank you for your multiple contributions

Very happy to help since I use it :)

> you are certainly welcome to submit a PR like you did for GSI

Ok. Can you give directions for a minimal starting setup?
In the GSI case I've tried to follow the C++ library, what would be the difference between credentials and PAM authentication for Python?

> starting next week I will be much less involved with python-irodsclient

Wow, I hope the best for your new adventure!

> The iRODS Consortium will continue to support this project

The European infrastructure is very much interested in it, I wish there will be someone to follow at least the minimal development required, let's see

**Comment by trel** [comment]
Thanks @adetorcy.

@pdonorio, we'll still be here.  Definitely pull requests most welcome.

**Comment by pdonorio** [comment]
Thank you @trel.

I can't say how I have to start a skeleton for this feature, so maybe you can help me with "give directions for a minimal starting setup" as I asked before :)

**Comment by trel** [comment]
PAM should be simpler than the GSI plugin (famous last words).

The C++ for PAM is here:
  https://github.com/irods/irods/blob/master/plugins/auth/pam/libpam.cpp

The four necessary functions should follow the same pattern as `libpam.cpp`:
```
irods::error pam_auth_client_start(
irods::error pam_auth_client_request(
irods::error pam_auth_establish_context(
irods::error pam_auth_client_response(
```
The client side follows this template from clientLogin.cpp where some of those functions will be stubbed out:
  https://github.com/irods/irods/blob/master/lib/core/src/clientLogin.cpp#L294

**Comment by pdonorio** [comment]
Thanks for the hints. I will ask my colleagues who are experts in c++ to help me out here.

**Comment by jbcmarsman** [comment]
We are also looking forward to this feature, which would render the python libs usable!

**Comment by mgougerot** [comment]
Hello,
do you have any update about this subject ?
We would be very interested in PAM authentication.
Thanks

**Comment by michael-conway** [comment]
I can take a crack at it as a PR. We need it too.

**Comment by jbcmarsman** [comment]
Unfortunately, It is not my priority. So I think we are all waiting for this.
Kind regards,

Jan-Bernard
    On Monday, July 9, 2018, 4:23:23 PM GMT+2, mgougerot <notifications@github.com> wrote:  
 
 
Hello,
do you have any update about this subject ?
We would be very interested in PAM authentication.
Thanks

**Comment by jbcmarsman** [comment]
Cool! I haven't been working on this yet.
Kind regards,
Jan-Bernard
    On Monday, July 9, 2018, 4:28:38 PM GMT+2, Mike Conway <notifications@github.com> wrote:  
 
 I can take a crack at it as a PR. We need it too.

**Comment by mdantonio** [comment]
Hello, I'm working to implement the PAM support and I already obtained a first prototype (it is working, but only tested on my server)

Who is interested to have a look, the code is here:

https://github.com/mdantonio/python-irodsclient

To test it, simply use `authentication_scheme='pam'` when creating the `iRODSSession` object

`iRODSSession(user='yourPAMuser', password='yourPAMpassword, authentication_scheme='pam', [...])`

Once stable i can provide you with a PR

The protocol currently implemented:

1 . an `AUTH_PLUG_REQ_AN` is sent (`PAM_AUTH_REQUEST_AN` does not work to me) by passing a context containing `a_user`, `a_pw` and `a_ttl` (defaulted to 60)

2 . irods server responds with a new password (validity = a_ttl, I suppose)

3 . I create a new connection (disconnect + connect). Without this operation the following step has no effect (maybe a less invasive solution can be found?)

4 . The new password is used to login as a native password (by passing it to _login_native function)

I hope to get feedbacks from you to enhance and complete this implementation

**Comment by trel** [comment]
Excellent.   We'll take a look here and have some feedback.

Will need to get some automated tests included before merging.

Thanks!

**Comment by mdantonio** [comment]
> Will need to get some automated tests included before merging.
Of course, i can help with this task too... just give me enough information to write tests and i can work on this

**Comment by trel** [comment]
We are looking at the best way to implement this.

The test will need to:
1. create a pam.d file
2. create a unix user (e.g. 'pamtestuser') with a password
3. create an irods user of the same name, but without a password
4. log in as 'pamtestuser' using 'pam' scheme

**Comment by mdantonio** [comment]
I had a look to other unit tests like [connection_test.py](https://github.com/irods/python-irodsclient/blob/master/irods/test/connection_test.py))

Operations 1, 2 and 3 should be implemented into the setUp(self) method or provided as an external script?

**Comment by trel** [comment]
Perhaps - the setUp runs for every test in a class, and the tearDown runs regardless of the test completing cleanly...

The biggest question is how to create a unix user -  presumably the user running this test will not have permission to create a unix user or set their password.

**Comment by mdantonio** [comment]
Hello, did you find a working setup to run unit tests? Once resolved this, I can help you to write required tests.

In the meanwhile I'm using with success the PAM module and found no particular bug with my use case. If more users will test the contribute I'm of course available to improve the implemented, if needed.

**Comment by trel** [comment]
Thanks for the update.  The implementation looks good to me, and it's good to know you've seen no issues.  Would you like to create a pull request, so others would have easier access to the working code?

We are working to move our testing infrastructure to Docker, which will give us more control over the system on which the tests run.

**Comment by mdantonio** [comment]
Of course, it is done (https://github.com/irods/python-irodsclient/pull/147)
Added some comments on the code to help you in the review

**Comment by trel** [comment]
This is merged due to demand.   Closing for now.   Thanks!

We have opened a new issue #151 for putting a test around this new codepath.

**Comment by mdantonio** [comment]
I am pleased to have contributed

Now that PAM is on master probably you want to update the main [README ](https://github.com/irods/python-irodsclient/blob/master/README.rst)with features list

**Comment by trel** [comment]
README.rst updated in 5e41bdb9d3e79a744f1ad1feeecaf2e697492f63
