### ISSUE TITLE
Is it possible to recursively set the inherit bit on a collection?

### ISSUE THREAD

**Issue by jchansen** [irods/python-irodsclient#85]
I'm using `python-irodsclient` in a project, to replace our current iRODS solution that invokes iCommands directly through via `subprocess.call`.

One of the commands I'm trying to replace creates a new collection, and then sets the inheritance bit on that collection. The iCommand calls look like this:

```
imkdir /some/new/collection
ichmod -r inherit /some/new/collection
```

I figured out I can create a collection, mirroring the `imkdir` comamnd by doing this:

```python
from irods.session import iRODSSession

session = iRODSSession(host='irods.example.com', port=1247, user='username', password='password', zone='zone')
collection = session.collections.create("/some/new/collection")
```

What I can't figure out is whether it's possible to mirror the `ichmod -r inherit /some/new/collection` command.

Is it? If yes, can you help me understand how to do that? That doesn't look like something I can do using the `iRODSAccess` object.

**Comment by adetorcy** [comment]
You should be able to do that by using `inherit` or `noinherit` as the access level and leaving the user name blank, e.g:
```python
acl = iRODSAccess('inherit', '/some/new/collection', '')
session.permissions.set(acl, recursive=True)
```
I'll add a default value so that you can simply do:
```python
acl = iRODSAccess('inherit', '/some/new/collection')
```

**Comment by jchansen** [comment]
Thanks @adetorcy! That work : )
