### ISSUE TITLE
irods.manager.DataObjectManager.put doesn't trigger acPostProcForPut PEP

### ISSUE THREAD

**Issue by tedgin** [irods/python-irodsclient#86]
I'm using version 0.6.0 of irods-pythonclient and iRODS version 4.1.10.

When I use the put() method of irods.manager.DataObjectManager to upload a file, it completes without any error messages returned and no error messages in the iRODS log files. However, I have a rule attached to the acPostProcForPut PEP, and this rule isn't executed.

**Comment by adetorcy** [comment]
You can pass the operation type parameter as part of the put options, e.g:
```python
import irods.keywords as kw

options = {kw.OPR_TYPE_KW: 1}   # PUT_OPR
session.data_objects.put('/some/local/file', '/tempZone/home/rods/', options)
```
But this should be set by default since this is a put operation. I'll push a fix.
