### ISSUE TITLE
Set timeout on socket connection

### ISSUE THREAD

**Issue by pdonorio** [irods/python-irodsclient#88]
Hello,
would it be possible to let the user specify a timeout for the socket connection when creating the `iRodsSession`? This may help us a lot in debugging the server when it's down, otherwise the default is `None` and it hangs forever.

Note: I may create a pull request for this but I have no idea on how to unittest the parameter.

Thanks

**Comment by adetorcy** [comment]
I'm not certain but this sounds like it might involve killing the iRODS agent in the middle of a connection.
If we are only talking about an optional connection timeout parameter and a call to socket.settimeout() then don't worry about a unit test as long as all the existing tests pass.

**Comment by pdonorio** [comment]
> If we are only talking about an optional connection timeout parameter and a call to socket.settimeout() then don't worry about a unit test as long as all the existing tests pass.

Yes, that is the case. Working on it.
