### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by adetorcy** [irods/python-irodsclient#91]
- [x] Client-Server negotiation
- [x] SSL/TLS support

**Comment by felipegutierrez** [comment]
so, is it working? can I use python + SSL to connect to iRODS?

**Comment by adetorcy** [comment]
Hopefully so. If you are already using the icommands with SSL you should be able to open sessions in python-irodsclient using your existing `~/.irods/` configuration files with SSL enabled. If you are not already using SSL see [here](https://docs.irods.org/4.2.2/system_overview/ssl/).

**Comment by pdonorio** [comment]
Hello, I am encountering problems against an SSL encrypted iRODS connection.
We first do the `iinit` and then use the environment file for creating the session with the `with` block.

Even if I give the right certificate path as `irods_ssl_ca_certificate_file` I get `SSL: CERTIFICATE_VERIFY_FAILED` error, although It works with icommands.

I've seen the `session.py` code and it seems that the parameter is not read or passed to the session. Am I doing something wrong?

**Comment by adetorcy** [comment]
This line might need updating:
https://github.com/irods/python-irodsclient/blob/master/irods/connection.py#L129

Please try:
```python
context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH, cafile=CA_file)
```
where CA_file is the value of your `irods_ssl_ca_certificate_file`.

Is this helping?

**Comment by pdonorio** [comment]
Thanks @adetorcy, by putting the CA file path in that variable it works.

Could you patch the file to read the file and put it there?

Or maybe even better: read this parameter directly from the session creation as a new parameter?

Let me know!

**Comment by adetorcy** [comment]
How does this latest commit work for you?

**Comment by pdonorio** [comment]
Just tested the `ssl` branch and it works, thank you.

Does this fix takes the information from the environment file?
Can we support also to pass the SSL request and file via Session instance creation?

**Comment by adetorcy** [comment]
Yes, the CA file setting is read from your irods environment file as the value of `irods_ssl_ca_certificate_file`, if present.

If you want more flexibility in creating your SSL context, this latest commit allows you to do it outside of the session and pass it to the session constructor, e.g:

```python
from irods.session import iRODSSession
import ssl

env_file = os.path.expanduser('~/.irods/irods_environment.json')

context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)

with iRODSSession(irods_env_file=env_file, ssl_context=context) as session:

    coll = session.collections.get('/tempZone/home/rods')
    print(coll)

sys.exit(0)
```

If these changes work for you I'll merge them into the main branch.

**Comment by pdonorio** [comment]
Thanks Antoine, very close to what I need.

I'd like to be completely independent from the JSON file, something like:
```python
with iRODSSession(user='me', password=..., ssl_context=context) as session:
    ...

```

I've tried it by creating the ssl_context with the `cafile` path I know, but it does not work.
Do you think it is possible?

**Comment by adetorcy** [comment]
The culprit is this line: https://github.com/irods/python-irodsclient/blob/ssl/irods/session.py#L62

If an environment file is not provided we return early, before the SSL bits. I'll try to push a fix today...

**Comment by adetorcy** [comment]
Ignore my last comment, I read the code too fast. All the session keyword arguments are passed on properly. When using SSL though you might want to make sure to include SSL specific settings. The following code works for me:
```python
from irods.session import iRODSSession
import ssl

context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)

with iRODSSession(irods_client_server_negotiation = 'request_server_negotiation',
                  irods_client_server_policy = 'CS_NEG_REQUIRE',
                  irods_encryption_algorithm = 'AES-256-CBC',
                  irods_encryption_key_size = 32,
                  irods_encryption_num_hash_rounds = 16,
                  irods_encryption_salt_size = 8,
                  host = 'icat.example.org',
                  port = 1247,
                  user = 'rods',
                  password = '1234',
                  zone = 'tempZone',
                  ssl_context = context) as session:

    coll = session.collections.get('/tempZone/home/rods')
    print(coll)

sys.exit(0)
```
Which you can re-write as follows:
```python
from irods.session import iRODSSession
import ssl

context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)

ssl_settings = {'irods_client_server_negotiation': 'request_server_negotiation',
                'irods_client_server_policy': 'CS_NEG_REQUIRE',
                'irods_encryption_algorithm': 'AES-256-CBC',
                'irods_encryption_key_size': 32,
                'irods_encryption_num_hash_rounds': 16,
                'irods_encryption_salt_size': 8,
                'ssl_context': context}


with iRODSSession(host = 'icat.example.org',
                  port = 1247,
                  user = 'rods',
                  password = '1234',
                  zone = 'tempZone',
                  **ssl_settings) as session:

    coll = session.collections.get('/tempZone/home/rods')
    print(coll)

sys.exit(0)
```

**Comment by pdonorio** [comment]
I needed to add this line to ssl_settings:

```
'irods_ssl_ca_certificate_file': '/path/to/irods/crt',
```

Then it worked!
Thank you so much :)

**Comment by trel** [comment]
So... are we able to close this issue?    That's exciting.

**Comment by pdonorio** [comment]
Since the commit was merged into master, it can be closed for me.

**Comment by trel** [comment]
perfect - thanks!
