### ISSUE TITLE
Pickable session

### ISSUE THREAD

**Issue by pdonorio** [irods/python-irodsclient#92]
Hello there,

I've been finding the need to store irods sessions inside a `postgresql blob`, and looked up how to make them be as binary strings.

I've seen that python uses the `pickle` library for this. So I've been trying:

```python
$ ipython

In [1]: from irods.session import iRODSSession

In [2]: sess = iRODSSession(...)

In [3]: sess.users.get('guest')
Out[3]: <iRODSUser 10019 guest rodsuser tempZone>

In [4]: import pickle

In [5]: pickle.dumps(sess)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-a81a58406cef> in <module>()
----> 1 pickle.dumps(sess)

TypeError: can't pickle _thread.lock objects
```

So I've been digging this and it seems that the `Pool` irods class stores a lock for threads that blocks the *serialization*. Do we want to fix this?

I can create a pull request to update the session class adding private methods`__getstate__` and `__setstate__` (see the [docs](https://docs.python.org/2/library/pickle.html#object.__getstate__)). Would it be fine? Should this a new child class or would that be applied to the existing one?

Finally unittests should do `dumps` and then `load` from pickle without errors.

**Comment by adetorcy** [comment]
If you are looking for serialization you might want to use [dill](https://pypi.python.org/pypi/dill) instead of pickle:
```python
>>> import dill
>>> import threading
>>> 
>>> 
>>> lock = threading.Lock()
>>> dump = dill.dumps(lock)
>>> 
>>> print(dump)
b'\x80\x03cdill.dill\n_create_lock\nq\x00\x89\x85q\x01Rq\x02.'
>>>
>>> dill.loads(dump)
<unlocked _thread.lock object at 0x7fc8f56c62d8>
>>> 
```

**Comment by pdonorio** [comment]
Thank you, I didn't know about dill. I just test it and it works.

There is still the problem of adding "yet another dependency" to the project. I created an example class that works with pickle, would you mind looking at it? Here's the gist:

https://gist.github.com/pdonorio/06f334685ea4b3e9cbbe04527790c3c2

**Comment by adetorcy** [comment]
I understand your concern about third party libraries but in this case this is an actively supported pure python library that has established itself as a "standard" for serializing python. Unless we are talking about performance issues or limitations in dill I would rather not add complexity to PRC just to solve a problem that dill already solves.

**Comment by pdonorio** [comment]
Very well, dill works and I have a solution for pickle that can be applied outside of PRC anyway.

Thank you!
